<?php
declare(strict_types=1);
namespace Artdon\CommercialCenter\Services;
use Artdon\CommercialCenter\Repositories\QuoteRepository;
final class LegacyOrderConversionService{
 private \PDO $db;private QuoteRepository $quotes;private QuotePermissionService $permissions;private QuoteWorkflowService $workflow;private LegacyDocumentTemplateAdapter $adapter;
 public function __construct(){ $this->db=db();$this->quotes=new QuoteRepository($this->db);$this->permissions=new QuotePermissionService($this->db);$this->workflow=new QuoteWorkflowService(null,$this->quotes,null,$this->permissions);$this->adapter=new LegacyDocumentTemplateAdapter();}
 public function convert(int $quoteId,array $actor):array{$this->permissions->assert($actor,'convert');$q=$this->quotes->find($quoteId)??throw new \RuntimeException('报价不存在。');
  if(!in_array($q['status'],['approved','customer_confirmed'],true))throw new \RuntimeException('只有审核通过或客户确认的报价可以转订单。');
  $find=$this->db->prepare('SELECT * FROM cc_quote_order_links WHERE quote_id=?');$find->execute([$quoteId]);$old=$find->fetch(\PDO::FETCH_ASSOC);if(is_array($old))return $this->result($old);
  $this->db->beginTransaction();try{$orderNo='SO-'.date('ymd').'-'.str_pad((string)$quoteId,5,'0',STR_PAD_LEFT);$snapshot=$this->adapter->orderSnapshot($q,$orderNo);$json=json_encode($snapshot,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$customer=$snapshot['customer'];$items=$snapshot['items'];
	   $s=$this->db->prepare('INSERT INTO quote_sales_orders(order_no,quote_no,source_quote_id,customer_id,customer_name,customer_json,header_json,bank_json,template_json,items_json,snapshot_json,qty,amount,currency,exchange_rate,quote_date,order_date,status,shipment_status,payment_status,paid_amount,balance_amount,order_doc_title,contract_title,note,user_name,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,\'待确认\',\'未出货\',\'未收款\',0,?,?,?,?,?,?,NOW())');
   $title=in_array(strtoupper((string)$q['currency']),['CNY','RMB'],true)?'订购合同':'PROFORMA INVOICE';
   $s->execute([$orderNo,$q['quote_no'],$quoteId,(string)($q['legacy_customer_id']??''),$customer['company'],json_encode($customer,JSON_UNESCAPED_UNICODE),'{}','{}','{}',json_encode($items,JSON_UNESCAPED_UNICODE),$json,$snapshot['total']['qty'],$q['total_amount'],$q['currency'],$snapshot['exchange_rate'],$q['quote_date'],date('Y-m-d'),$q['total_amount'],$title,$title,$q['customer_note']??'',$actor['display_name']??$actor['username']??'',$actor['display_name']??$actor['username']??'']);
   $orderId=(int)$this->db->lastInsertId();$itemIds=[];
   foreach($items as $idx=>$it){$x=$this->db->prepare('INSERT INTO quote_sales_order_items(order_id,item_index,customer_code,product_code,product_name,specification,color,qty,unit_price,amount,shipped_qty,image,item_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,0,?,?,NOW())');$x->execute([$orderId,$idx+1,$it['customer_code'],$it['product_code'],$it['product_name'],$it['specification'],$it['color'],$it['qty'],$it['unit_price'],$it['amount'],$it['image'],json_encode($it,JSON_UNESCAPED_UNICODE)]);$itemIds[]=(int)$this->db->lastInsertId();}
   $ship=$this->db->prepare('INSERT INTO quote_shipments(order_id,shipment_no,ship_date,packing_list_no,commercial_invoice_no,status,total_qty,total_cartons,total_nw,total_gw,total_cbm,note,created_by,created_at,updated_at) VALUES(?,?,?,?,?,\'单证草稿\',?,0,0,0,0,?,?,NOW(),NOW())');$ship->execute([$orderId,'DOC-'.$orderNo,date('Y-m-d'),'PL-'.$orderNo,'CI-'.$orderNo,$snapshot['total']['qty'],'由报价转换，包装数据待补充',$actor['display_name']??'']);$shipmentId=(int)$this->db->lastInsertId();
   foreach($items as $idx=>$it){$x=$this->db->prepare('INSERT INTO quote_shipment_items(shipment_id,order_id,order_item_id,item_index,customer_code,product_code,product_name,specification,color,qty,pcs_per_ctn,cartons,carton_size,nw,gw,cbm,unit_price,amount,image,note,item_json) VALUES(?,?,?,?,?,?,?,?,?,?,0,0,\'\',0,0,0,?,?,?,?,?)');$x->execute([$shipmentId,$orderId,$itemIds[$idx],$idx+1,$it['customer_code'],$it['product_code'],$it['product_name'],$it['specification'],$it['color'],$it['qty'],$it['unit_price'],$it['amount'],$it['image'],$it['note'],json_encode($it,JSON_UNESCAPED_UNICODE)]);}
   $link=$this->db->prepare('INSERT INTO cc_quote_order_links(quote_id,quote_version_id,legacy_order_id,order_no,conversion_snapshot,snapshot_hash,converted_by_legacy_user_id,converted_by_name,converted_at) VALUES(?,?,?,?,?,?,?,?,NOW())');$link->execute([$quoteId,(int)$q['version']['id'],$orderId,$orderNo,$json,hash('sha256',$json),(int)($actor['id']??0)?:null,$actor['display_name']??$actor['username']??'']);
   $this->db->prepare('UPDATE cc_quote_details SET converted_order_id=?,converted_order_no=?,converted_at=NOW(),converted_by_legacy_user_id=? WHERE quote_id=?')->execute([$orderId,$orderNo,(int)($actor['id']??0)?:null,$quoteId]);
   foreach(['pi', 'ci','pl'] as $type){$no=$type==='pi'?$orderNo:($type==='ci'?'CI-'.$orderNo:'PL-'.$orderNo);$d=$this->db->prepare('INSERT INTO cc_legacy_document_snapshots(legacy_order_id,shipment_id,document_type,document_no,version_no,snapshot_json,snapshot_hash,template_version,generated_by_legacy_user_id,generated_at) VALUES(?,?,?,?,1,?,?,\'legacy_v1\',?,NOW())');$d->execute([$orderId,$type==='pi'?null:$shipmentId,$type,$no,$json,hash('sha256',$type.'|'.$json),(int)($actor['id']??0)?:null]);}
   $this->workflow->transition($quoteId,'converted',$actor,'审核报价转正式订单');$this->db->commit();return $this->result(['legacy_order_id'=>$orderId,'order_no'=>$orderNo],$shipmentId);
  }catch(\Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}
 private function result(array $link,?int $shipmentId=null):array{$orderId=(int)($link['legacy_order_id']??0);if($shipmentId===null){$s=$this->db->prepare('SELECT id FROM quote_shipments WHERE order_id=? ORDER BY id LIMIT 1');$s->execute([$orderId]);$shipmentId=(int)$s->fetchColumn();}return ['order_id'=>$orderId,'order_no'=>$link['order_no'],'shipment_id'=>$shipmentId,'documents'=>['pi'=>'legacy_document_bridge.php?type=pi&order_id='.$orderId,'pi_excel'=>'legacy_document_bridge.php?type=pi&format=excel&order_id='.$orderId,'ci'=>'../quote_order_doc.php?type=ci&shipment_id='.$shipmentId,'ci_excel'=>'../quote_order_doc.php?type=ci&format=excel&shipment_id='.$shipmentId,'pl'=>'../quote_order_doc.php?type=pl&shipment_id='.$shipmentId,'pl_excel'=>'../quote_order_doc.php?type=pl&format=excel&shipment_id='.$shipmentId]];}
}
