<?php
function render_material_workspace(array $config,array $rows,array $pagination=[]):void{
 $tabs=['全部'=>'all','待整理'=>'pending','待确认'=>'review','正式'=>'formal','异常'=>'abnormal'];
 $categoryCode=(string)($config['category_code']??'');
 $usesCategoryDrawer=in_array($categoryCode,['chip','optical','profile','connector','accessory','packaging'],true);
?>
<section class="mc-page mc-page--table" data-workspace data-category-code="<?=mc_h($categoryCode)?>">
 <div class="mc-page-header mc-page-header--compact"><div><h1><?=mc_h($config['title'])?></h1><p><?=mc_h($config['description'])?> · 新建仅用于 BOM 中不存在的全新物料；已有来源请使用行内“整理”。</p></div><div><button class="mc-button mc-button--primary" type="button" title="手工创建一条 BOM 中不存在的全新物料" <?=$usesCategoryDrawer?'data-open-category-editor':'data-open-modal="new-modal"'?>><?=mc_icon('plus',16)?> 新建</button></div></div>
 <div class="mc-tabs" role="tablist"><?php foreach($tabs as $label=>$value): ?><button type="button" class="<?=$value==='all'?'is-active':''?>" data-status-tab="<?=mc_h($value)?>"><?=mc_h($label)?></button><?php endforeach; ?></div>
 <div class="mc-toolbar"><label class="mc-search"><?=mc_icon('search',17)?><input type="search" placeholder="搜索品牌、型号、名称或规格" data-table-search><button type="button" data-clear-search>×</button></label><div class="mc-toolbar__actions"><button class="mc-button" data-open-drawer="filter-drawer"><?=mc_icon('filter',16)?> 筛选</button><?php if(($config['category_code']??'')==='power_supply'):?><a class="mc-button" href="<?=mc_h(mc_url('data/index.php'))?>">导入</a><a class="mc-button" href="<?=mc_h(mc_url('api/v1/export.php?include_sources=1&category=power_supply'))?>">导出</a><a class="mc-button" href="<?=mc_h(mc_url('documents/index.php?tab=logs'))?>">日志</a><?php else:?><div class="mc-dropdown-wrap"><button class="mc-button" data-dropdown-trigger="more-menu"><?=mc_icon('more',16)?> 更多</button><div class="mc-dropdown" id="more-menu" data-dropdown><a href="<?=mc_h(mc_url('data/index.php'))?>">批量导入</a><a href="<?=mc_h(mc_url('api/v1/export.php?include_sources=1'.(!empty($config['category_code'])?'&category='.rawurlencode((string)$config['category_code']):'')))?>">导出当前清单</a><a href="<?=mc_h(mc_url('documents/index.php?tab=logs'))?>">操作日志</a></div></div><?php endif;?><button class="mc-button" data-open-view-settings><?=mc_icon('columns',16)?> 视图设置</button><button class="mc-icon-button" data-refresh-table><?=mc_icon('refresh',17)?></button></div></div>
 <div class="mc-selection-bar" data-selection-bar hidden><strong>已选择 <span data-selection-count>0</span> 项</strong><button class="mc-button mc-button--soft" data-open-batch>批量设置</button><button class="mc-button" data-batch-lifecycle="approve">批量转正式</button><button class="mc-button" data-batch-lifecycle="disable">批量停用</button><button class="mc-button" data-export-selected>导出所选</button><button class="mc-link-button" data-clear-selection>取消选择</button></div>
 <div class="mc-table-shell" data-table-shell><div class="mc-table-scroll" data-table-scroll><table class="mc-table" data-table><thead><tr><th class="mc-col-check"><input type="checkbox" data-select-all></th><?php foreach($config['columns'] as $column): ?><th data-column="<?=mc_h($column[0])?>" style="--col-width:<?=mc_h($column[2])?>"><span><?=mc_h($column[1])?></span><i class="mc-col-resizer"></i></th><?php endforeach; ?><th class="mc-col-action">操作</th></tr></thead><tbody>
 <?php foreach($rows as $row): $record=['id'=>(int)($row['id']??0),'source_record_id'=>(int)($row['source_record_id']??0),'category_id'=>(int)($row['category_id']??0),'category_code'=>$categoryCode,'lock_version'=>(int)($row['lock_version']??1),'read_only'=>(bool)($row['read_only']??false),'code'=>strip_tags((string)$row[0]),'name'=>strip_tags((string)$row[1]),'brand'=>strip_tags((string)$row[2]),'model'=>strip_tags((string)$row[3]),'spec'=>strip_tags((string)$row[4]),'status'=>strip_tags((string)$row[5]),'raw_status'=>strip_tags((string)($row['raw_status']??'')),'source'=>strip_tags((string)$row[6]),'warranty'=>strip_tags((string)$row[7]),'unit'=>strip_tags((string)($row['unit']??'PCS')),'supplier_text'=>strip_tags((string)($row['supplier_text']??'')),'remark'=>strip_tags((string)($row['remark']??'')),'organize_url'=>(string)($row['organize_url']??'')];$statusKey=in_array($record['raw_status'],['draft','temporary','pending_sort'],true)?'pending':($record['raw_status']==='pending_review'?'review':($record['raw_status']==='official'?'formal':(in_array($record['raw_status'],['abnormal','duplicate','rejected','disabled','archived','source_changed'],true)?'abnormal':'all'))); ?>
 <?php
  $actionLabel=match($record['raw_status']){
   'source'=>'整理','source_changed'=>'处理','draft'=>'编辑','temporary','pending_sort'=>'整理',
   'pending_review'=>'确认','official','disabled','archived'=>'查看','abnormal','rejected'=>'处理',
   'duplicate'=>'对比合并',default=>'查看',
  };
 ?>
 <tr data-row data-status="<?=mc_h($statusKey)?>" data-source="<?=mc_h($record['source'])?>" data-read-only="<?=$record['read_only']?'1':'0'?>" data-search="<?=mc_h(implode(' ',array_map(static fn($value)=>is_scalar($value)?(string)$value:'',$record)))?>" data-record="<?=mc_json_attr($record)?>"><td class="mc-col-check"><?php if(!$record['read_only']):?><input type="checkbox" data-row-select><?php else:?><span title="只读来源">—</span><?php endif;?></td><?php foreach($config['columns'] as $column): $key=$column[0];$value=$record[$key]??'—'; ?><td data-column="<?=mc_h($key)?>" class="<?=$key==='spec'?'mc-cell-spec':''?>"><?php if($key==='status'): ?><span class="mc-badge mc-badge--<?=mc_h(mc_badge($value))?>"><?=mc_h($value)?></span><?php elseif($key==='source'): ?><span class="mc-source-chip"><?=mc_h($value)?></span><?php else: ?><?=mc_h($value)?><?php endif; ?></td><?php endforeach; ?><td class="mc-col-action"><?php if($record['read_only']&&$categoryCode===''):?><a class="mc-link-button" href="<?=mc_h($record['organize_url'])?>"><?=mc_h($actionLabel)?></a><?php elseif($record['read_only']):?><button class="mc-link-button" data-organize-source <?=$categoryCode==='power_supply'?'data-open-detail':'data-open-category-editor'?>><?=mc_h($actionLabel)?></button><?php elseif($usesCategoryDrawer):?><button class="mc-link-button" data-open-category-editor><?=mc_h($actionLabel)?></button><?php else:?><button class="mc-link-button" data-open-detail><?=mc_h($actionLabel)?></button><?php endif;?></td></tr>
 <?php endforeach; ?></tbody></table><div class="mc-table-empty" data-table-empty hidden><div class="mc-empty-icon"><?=mc_icon('search',30)?></div><strong>没有符合条件的记录</strong><span>调整搜索或筛选条件后再试。</span></div></div><div class="mc-pagination"><div class="mc-pagination__summary">共 <strong data-total-count><?=count($rows)?></strong> 条</div><div class="mc-pagination__controls"><label>每页 <select data-page-size><option value="auto">自动</option><option value="10">10</option><option value="20">20</option><option value="30">30</option><option value="50">50</option><option value="100">100</option></select></label><button data-page-prev>‹ 上一页</button><div class="mc-page-numbers" data-page-numbers></div><button data-page-next>下一页 ›</button><label>跳至 <input type="number" min="1" value="1" data-page-jump> 页</label></div></div></div>
</section>
<?php }
