<?php
function render_material_workspace(array $config,array $rows,array $pagination=[]):void{
 $tabs=['全部'=>'all','待整理'=>'pending','待确认'=>'review','正式'=>'formal','异常'=>'abnormal'];
?>
<section class="mc-page mc-page--table" data-workspace data-category-code="<?=mc_h((string)($config['category_code']??''))?>">
 <div class="mc-page-header mc-page-header--compact"><div><h1><?=mc_h($config['title'])?></h1><p><?=mc_h($config['description'])?></p></div><button class="mc-button mc-button--primary" type="button" data-open-modal="new-modal"><?=mc_icon('plus',16)?> 新建</button></div>
 <div class="mc-tabs" role="tablist"><?php foreach($tabs as $label=>$value): ?><button type="button" class="<?=$value==='all'?'is-active':''?>" data-status-tab="<?=mc_h($value)?>"><?=mc_h($label)?></button><?php endforeach; ?></div>
 <div class="mc-toolbar"><label class="mc-search"><?=mc_icon('search',17)?><input type="search" placeholder="搜索品牌、型号、名称或规格" data-table-search><button type="button" data-clear-search>×</button></label><div class="mc-toolbar__actions"><button class="mc-button" data-open-drawer="filter-drawer"><?=mc_icon('filter',16)?> 筛选</button><div class="mc-dropdown-wrap"><button class="mc-button" data-dropdown-trigger="more-menu"><?=mc_icon('more',16)?> 更多</button><div class="mc-dropdown" id="more-menu" data-dropdown><a href="<?=mc_h(mc_url('power_workbench.php?panel=bands'))?>">功率档设置</a><a href="<?=mc_h(mc_url('power_workbench.php?panel=fields'))?>">字段设置</a><a href="<?=mc_h(mc_url('data/index.php'))?>">批量导入</a><a href="<?=mc_h(mc_url('api/v1/export.php'))?>">导出</a><a href="<?=mc_h(mc_url('power_workbench.php?tab=exception&exception=duplicate'))?>">重复检查</a><a href="<?=mc_h(mc_url('power_workbench.php?panel=mappings'))?>">映射记录</a><a href="<?=mc_h(mc_url('documents/index.php'))?>">操作日志</a></div></div><button class="mc-button" data-open-view-settings><?=mc_icon('columns',16)?> 视图设置</button><button class="mc-icon-button" data-refresh-table><?=mc_icon('refresh',17)?></button></div></div>
 <div class="mc-selection-bar" data-selection-bar hidden><strong>已选择 <span data-selection-count>0</span> 项</strong><button class="mc-button mc-button--soft" data-open-batch>批量设置</button><button class="mc-button" data-batch-lifecycle="approve">批量转正式</button><button class="mc-button" data-batch-lifecycle="disable">批量停用</button><button class="mc-button" data-export-selected>导出所选</button><button class="mc-link-button" data-clear-selection>取消选择</button></div>
 <div class="mc-table-shell" data-table-shell><div class="mc-table-scroll" data-table-scroll><table class="mc-table" data-table><thead><tr><th class="mc-col-check"><input type="checkbox" data-select-all></th><?php foreach($config['columns'] as $column): ?><th data-column="<?=mc_h($column[0])?>" style="--col-width:<?=mc_h($column[2])?>"><span><?=mc_h($column[1])?></span><i class="mc-col-resizer"></i></th><?php endforeach; ?><th class="mc-col-action">操作</th></tr></thead><tbody>
 <?php foreach($rows as $row): $record=['id'=>(int)($row['id']??0),'category_id'=>(int)($row['category_id']??0),'code'=>strip_tags((string)$row[0]),'name'=>strip_tags((string)$row[1]),'brand'=>strip_tags((string)$row[2]),'model'=>strip_tags((string)$row[3]),'spec'=>strip_tags((string)$row[4]),'status'=>strip_tags((string)$row[5]),'source'=>strip_tags((string)$row[6]),'warranty'=>strip_tags((string)$row[7])];$statusKey=$record['status']==='待整理'?'pending':($record['status']==='待确认'?'review':($record['status']==='正式'?'formal':(in_array($record['status'],['异常','重复候选','停用','归档'],true)?'abnormal':'all'))); ?>
 <tr data-row data-status="<?=mc_h($statusKey)?>" data-source="<?=mc_h($record['source'])?>" data-search="<?=mc_h(implode(' ',$record))?>" data-record="<?=mc_json_attr($record)?>"><td class="mc-col-check"><input type="checkbox" data-row-select></td><?php foreach($config['columns'] as $column): $key=$column[0];$value=$record[$key]??'—'; ?><td data-column="<?=mc_h($key)?>" class="<?=$key==='spec'?'mc-cell-spec':''?>"><?php if($key==='status'): ?><span class="mc-badge mc-badge--<?=mc_h(mc_badge($value))?>"><?=mc_h($value)?></span><?php elseif($key==='source'): ?><span class="mc-source-chip"><?=mc_h($value)?></span><?php else: ?><?=mc_h($value)?><?php endif; ?></td><?php endforeach; ?><td class="mc-col-action"><button class="mc-link-button" data-open-detail>查看</button></td></tr>
 <?php endforeach; ?></tbody></table><div class="mc-table-empty" data-table-empty hidden><div class="mc-empty-icon"><?=mc_icon('search',30)?></div><strong>没有符合条件的记录</strong><span>调整搜索或筛选条件后再试。</span></div></div><div class="mc-pagination"><div class="mc-pagination__summary">共 <strong data-total-count><?=count($rows)?></strong> 条</div><div class="mc-pagination__controls"><label>每页 <select data-page-size><option value="auto">自动</option><option value="10">10</option><option value="20">20</option><option value="30">30</option><option value="50">50</option><option value="100">100</option></select></label><button data-page-prev>‹ 上一页</button><div class="mc-page-numbers" data-page-numbers></div><button data-page-next>下一页 ›</button><label>跳至 <input type="number" min="1" value="1" data-page-jump> 页</label></div></div></div>
</section>
<?php }
