const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const source=fs.readFileSync(require('node:path').join(__dirname,'../bom.php'),'utf8');
function extract(name){const start=source.search(new RegExp('^(?:async )?function '+name+'\\(','m'));assert(start>=0,name);const tail=source.slice(start),end=tail.slice(1).search(/^(?:async )?function /m);return tail.slice(0,end+1);}
function make(names,extra={}){const els={};const c=vm.createContext({crypto,Map,bomEditorId:'A',bomWriteBusy:false,bomWriteRequests:new Map(),bomSnapshotOpen:true,bomSnapshotRequest:0,bomSnapshotCurrent:null,projects:[],currentId:'A',currentPage:'edit',currentUser:{},currentCan:{cost_view:true},$:id=>els[id]??={value:'',dataset:{},style:{},disabled:false,innerHTML:''},alert:()=>{},prompt:()=>null,hasPerm:()=>true,nowText:()=> 'time',uid:()=> 'copy',getCurrent:()=>null,updateBomWorkflowUI:()=>{},setStatus:()=>{},bomRememberPlace:()=>{},showPage:()=>{},loadProject:async()=>{},collect:()=>{},bomWorkflowStatus:()=> 'draft',renderBomSnapshotList:()=>{},esc:String,money:String,rowSub:()=>0,...extra});vm.runInContext(names.map(extract).join('\n'),c);return c;}
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
(async()=>{
  let saved=0,submitted=0;let c=make(['submitBomReview'],{bomEditorReady:()=>true,getCurrent:()=>({}),saveCurrent:async()=>{saved++;return true},bomReviewAction:async()=>submitted++});await c.submitBomReview();assert.equal(saved,0);assert.equal(submitted,0);
  c=make(['totals']);assert.equal(c.totals({rowsLoaded:true,rows:[],totalsSummary:{total:123}}).total,0);
  c=make(['copyBomSnapshotToDraft'],{bomSnapshotCurrent:{project_uid:'A',profit_rate:0,rows:[]},closeBomSnapshots:()=>{}});c.copyBomSnapshotToDraft();assert.equal(c.projects[0].profitRate,0);
  const a=deferred(),b=deferred();c=make(['showBomSnapshot'],{api:(_,d)=>d.snapshot_id===1?a.promise:b.promise});const pa=c.showBomSnapshot(1),pb=c.showBomSnapshot(2);b.resolve({ok:true,snapshot:{id:2,project_uid:'A',rows:[]}});await pb;a.resolve({ok:true,snapshot:{id:1,project_uid:'A',rows:[]}});await pa;assert.equal(c.bomSnapshotCurrent.id,2);
  c.api=async()=>({ok:false,error:'failure'});await c.showBomSnapshot(3);assert.equal(c.bomSnapshotCurrent,null);assert.equal(c.$('bomSnapshotCopyBtn').disabled,true);
  c.api=async()=>({ok:true,snapshot:{id:4,project_uid:'B',rows:[]}});await c.showBomSnapshot(4);assert.equal(c.bomSnapshotCurrent,null);
  const late=deferred();c.api=()=>late.promise;const pending=c.showBomSnapshot(5);c.bomSnapshotOpen=false;c.bomSnapshotRequest++;late.resolve({ok:true,snapshot:{id:5,project_uid:'A'}});await pending;assert.equal(c.bomSnapshotCurrent,null);
  let posts=[];const detail=deferred();c=make(['loadProject','getCurrent','collect','saveCurrent','bomEditorReady','bomWorkflowLocked'],{projects:[{id:'A',rowsLoaded:true,rows:[]},{id:'B',rowsLoaded:false,rows:[]}],document:{querySelectorAll:()=>[]},renderProjectList:()=>{},closeBomSnapshots:()=>{},ensureProjectDetail:()=>detail.promise,api:async(a,d)=>{posts.push(d);return {ok:true}}});c.$('projectName').value='A content';c.loadProject('B');await c.saveCurrent();assert.equal(posts.length,0);
  let ids=[];c=make(['bomWrite'],{api:async(a,d)=>{ids.push(d.request_id);return {ok:false,error:'timeout'}}});await c.bomWrite('save_project',{project_uid:'A'});await c.bomWrite('save_project',{project_uid:'A'});assert.equal(ids[0],ids[1]);
  c.api=async(a,d)=>{ids.push(d.request_id);return {ok:true}};await c.bomWrite('save_project',{project_uid:'A'});await c.bomWrite('save_project',{project_uid:'A'});assert.notEqual(ids[2],ids[3]);
  c=make(['resolvePlmLinkedRows'],{materials:[{}]});const approved={reviewStatus:'approved',rows:[{price:0,qty:0}]};c.resolvePlmLinkedRows(approved);assert.equal(approved.rows[0].price,0);assert.equal(approved.rows[0].qty,0);
  const key=extract('loadProject');assert(!key.includes('resolvePlmLinkedRows(p)'));assert(extract('collect').includes('p.totalsSummary=null'));
  console.log('BOM workflow JS: cancel, zero values, totals, loading safety, stale snapshots, retry identity, locked data OK');
})().catch(e=>{console.error(e);process.exitCode=1});
