const fs=require('fs'),assert=require('node:assert/strict');
if(process.env.BOM_VOID_BROWSER_TEST!=='1'){console.log('Opt-in offline browser test');process.exit(0);}
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN});try{for(const width of [390,768,1440]){
 const page=await browser.newPage({viewport:{width,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const styles=[...fs.readFileSync('bom.php','utf8').matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)].map(x=>x[1]).join('\n');
 await page.route('**/*',r=>r.request().url()==='https://bom-void.test/'?r.fulfill({contentType:'text/html',body:`<meta charset="utf-8"><style>${styles}</style><div class="bom-snapshot-mask" style="display:flex"><div class="bom-snapshot-box"><div class="bom-snapshot-head">审核快照</div><div class="bom-snapshot-body"><div id="bomSnapshotList" class="bom-snapshot-list"></div><div id="bomSnapshotDetail" class="bom-snapshot-detail"></div></div></div></div>`}):r.abort());await page.goto('https://bom-void.test/');
 await page.addScriptTag({content:`const $=id=>document.getElementById(id),esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');let p={id:'TEST',revision:'r1',costPublication:{snapshot_id:2,source:'approved_snapshot'}},currentId='TEST',bomSnapshotCurrent={id:2,project_uid:'TEST',model:'52.98765'},bomSnapshotOpen=true,bomWriteBusy=false,currentCan={cost_view:true},bomSnapshots=[{id:2,model:'52.98765',version_no:'V2'},{id:1,model:'52.98765',version_no:'V1',snapshot_uid:'SAFE <img src=x onerror=alert(1)>',approved_at:'2026-09-21'}];window.allowed=true;window.sent=[];window.alerts=[];window.fail=false;window.delay=0;window.alert=s=>alerts.push(s);function getCurrent(){return p;}function hasPerm(){return allowed;}async function showBomSnapshot(){}function renderBomSnapshotList(){$('bomSnapshotList').innerHTML=bomSnapshots.map(s=>'<button>Snapshot '+s.id+'</button>').join('');}function bomApplySavedProject(v){p={...p,...v};}async function loadProject(){if(bomWriteBusy)throw Error('Reload while locked');window.reloaded=true;}async function openBomSnapshots(){window.reopened=true;}function updateBomWorkflowUI(){}async function bomWrite(action,data){sent.push({action,data});await new Promise(r=>setTimeout(r,delay));return fail?{ok:false,error:'模拟断网'}:{ok:true,project:{project_uid:'TEST',id:'TEST'},message:'已作废'};}`});
 await page.addScriptTag({content:fs.readFileSync('assets/bom-snapshot-void.js','utf8')});await page.evaluate(()=>renderBomSnapshotVoid());await page.click('summary');
 await page.click('#bomVoidConfirm');assert.equal(await page.evaluate(()=>sent.length),0);await page.fill('#bomVoidReason','Acceptance correction');await page.click('#bomVoidConfirm');assert.equal(await page.evaluate(()=>sent.length),0);
 await page.selectOption('#bomVoidReplacement','pause');await page.evaluate(()=>{fail=true;delay=100;});await page.click('#bomVoidConfirm');await page.waitForFunction(()=>!bomWriteBusy);assert.equal(await page.inputValue('#bomVoidReason'),'Acceptance correction');assert.equal(await page.evaluate(()=>sent[0].data.publication_mode),'pause');
 assert.equal(await page.locator('#bomSnapshotVoidPanel img').count(),0);assert(!(await page.locator('#bomSnapshotVoidPanel').evaluate(e=>e.scrollWidth>e.clientWidth+2)));
 if(process.env.BOM_VOID_SCREENSHOTS)await page.screenshot({path:process.env.BOM_VOID_SCREENSHOTS+'/void-'+width+'.png'});
 await page.evaluate(()=>{fail=false;sent=[];});await page.selectOption('#bomVoidReplacement','1');await page.evaluate(()=>{voidBomSnapshot();voidBomSnapshot();});await page.waitForFunction(()=>!bomWriteBusy);assert.equal(await page.evaluate(()=>sent.length),1);assert.equal(await page.evaluate(()=>sent[0].data.replacement_snapshot_id),1);assert(await page.evaluate(()=>reloaded&&reopened));
 await page.evaluate(()=>{allowed=false;renderBomSnapshotVoid();});assert.equal(await page.locator('#bomVoidConfirm').count(),0);
 await page.evaluate(()=>{bomSnapshotCurrent.voided=true;bomSnapshotCurrent.void_reason='<script>alert(1)</script>';renderBomSnapshotVoid();});assert((await page.locator('#bomSnapshotVoidPanel').textContent()).includes('已作废'));assert.equal(await page.locator('#bomSnapshotVoidPanel script').count(),0);
 assert.deepEqual(errors,[]);await page.close();
}console.log('BOM void browser: permissions, required reason/disposition, explicit replacement/pause, retry, double-click, escaping and 390/768/1440 layout passed');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
