// Fully intercepted synthetic browser fixture. No production URL or business writes.
const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base={id:4,order_no:'AT-TEST-A',customer_name:'验收客户',currency:'USD',customer_json:'{}'};
const item={id:41,order_id:4,order_no:base.order_no,qty:100,ordered_qty:100,available_qty:100,product_code:'TEST-MODEL',customer_code:'WH',unit_price:2,source_hash:'synthetic',packaging_options:[{id:1,customer_code:'WH',match_kind:'exact',pcs_per_ctn:16,carton_size:'40x36x30',carton_nw:11.6,carton_gw:12.6,carton_cbm:0}]};
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN});try{
const page=await browser.newPage(),errors=[],actions=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept(d.type()==='prompt'?'验收测试':undefined));let saved;
await page.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${fs.readFileSync('assets/quote-shipment-batch.css','utf8')+fs.readFileSync('assets/quote-shipment-links.css','utf8')}</style><div id="orderDetail"></div><script>var openCombinedShipmentModal,openShipmentModal;function renderOrderDetail(){document.getElementById('orderDetail').innerHTML='<h3 class="order-subtitle">出货批次 / Shipments</h3><div>暂无出货批次</div>';}async function orderApi(action,data){return (await (await fetch('/quote_order_api.php?action='+action,{method:'POST',body:JSON.stringify(data)})).json()).data;}</script><script>${fs.readFileSync('assets/quote-shipment-batch.js','utf8')}</script><script>${fs.readFileSync('assets/quote-shipment-links.js','utf8')}</script>`});
if(url.pathname!=='/quote_order_api.php')return route.abort();const op=url.searchParams.get('action'),input=req.postDataJSON();actions.push(op);let data;
if(op==='batch_candidates')data={base,orders:[base],plans:[],total:1};
else if(op==='batch_items')data={order:base,items:[item]};
else if(op==='batch_order_batches')data={batches:[{kind:'plan',id:5,base_order_id:4,label:'装运批次 #5',state:'planning',version:3,issued_version:2,order_qty:35},{kind:'legacy',id:9,label:'OLD-9',state:'已出货',order_qty:20}]};
else if(op==='batch_save'){saved=input.data;data={id:5,base_order_id:4,version:1,state:'planning',data:{...saved,items:saved.items.map(x=>({...item,...x})),totals:{qty:35}},history:[],documents:[]};}
else return route.fulfill({json:{ok:false,msg:'Unexpected write '+op}});return route.fulfill({json:{ok:true,data}});});
for(const width of [1280,768,390]){await page.setViewportSize({width,height:900});await page.goto('http://synthetic-shipment.test/');await page.evaluate(()=>renderOrderDetail({id:4}));await page.locator('.qsl-list .qsl-card').first().waitFor();assert.equal(await page.locator('.qsl-list .qsl-card').count(),2);
await page.evaluate(()=>quickGenerateOrderDoc(4,'ci'));await page.locator('.qsl-mask a').first().waitFor();assert.match(await page.locator('.qsl-mask a').first().getAttribute('href'),/version=2&type=ci/);assert.match(await page.locator('.qsl-mask a').nth(1).getAttribute('href'),/format=pdf/);assert.equal(await page.locator('.qb-overlay').count(),0);await page.locator('[data-qsl-close]').click();
await page.evaluate(()=>quickGenerateOrderDoc(4,'pl'));await page.locator('.qsl-mask a').first().waitFor();assert.match(await page.locator('.qsl-mask a').first().getAttribute('href'),/type=pl/);await page.locator('[data-qsl-close]').click();
await page.evaluate(()=>QuoteShipmentBatch.open(4));await page.locator('[data-load="4"]').click();await page.locator('[data-all="4"]').click();await page.locator('[data-qty="41"]').first().fill('35');await page.locator('[data-tab="pack"]').click();
await page.locator('[data-pack-choice="41"]').selectOption('1');await page.locator('[data-pack-generate="41"]').click();assert.equal(await page.locator('.qb-box-fields').count(),2);assert.equal(await page.locator('[data-box-field="carton_no"]').nth(0).inputValue(),'1-2');assert.equal(await page.locator('[data-box-field="carton_no"]').nth(1).inputValue(),'3');assert.equal(await page.locator('[data-box-field="cbm"]').nth(0).inputValue(),'0.0864');assert.equal(await page.locator('[data-weight-confirm]').count(),1);
await page.locator('[data-pack-choice="41"]').selectOption('1');await page.locator('[data-pack-generate="41"]').click();assert.equal(await page.locator('.qb-box-fields').count(),2,'Second click never duplicates packing');await page.locator('[data-weight-confirm]').check();await page.locator('[data-action="save"]').click();await page.waitForFunction(()=>document.querySelector('[data-qb-status]').textContent.includes('批次 #5'));assert.equal(saved.cartons[1].weight_confirmed,true);assert.equal(saved.cartons.reduce((s,x)=>s+x.items[0].qty,0),35);assert.equal(saved.cartons[0].carton_count,2);
const overflow=await page.evaluate(()=>[...document.querySelectorAll('.qb-shell input,.qb-shell select,.qb-shell button')].filter(e=>e.getClientRects().length).some(e=>e.getBoundingClientRect().right>innerWidth+1));assert.equal(overflow,false);await page.locator('[data-action="close"]').click();console.log('PASS '+width+'px: saved batch catalog, distinct read-only PL/CI links, profile import, carton range, remainder weight, duplicate prevention');}
assert.deepEqual(errors,[]);assert(!actions.some(x=>['batch_issue','batch_dispatch','mark_document_generated'].includes(x)));console.log('Shipment link browser regression passed.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
