const fs=require('node:fs'),assert=require('node:assert/strict');
if(process.env.BOM_VERSION_BROWSER_TEST!=='1'){console.log('Opt-in browser test; no live network.');process.exit(0);}
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN});try{
for(const width of [390,768,1440]){
 const page=await browser.newPage({viewport:{width,height:850}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',r=>r.request().url()==='https://bom-version.test/'?r.fulfill({contentType:'text/html',body:'<!doctype html><meta charset="utf-8"><style>'+fs.readFileSync('assets/quote-bom-versions.css','utf8')+'</style><div id="productLinkHint"></div><input id="manualPrice" value="88"><button id="start" onclick="QuoteBomVersions.open()">版本</button>'}):r.abort());
 await page.goto('https://bom-version.test/');
 await page.addScriptTag({content:`let S={product:{id:1,code:'52.98765',cost_rmb:50,quote_spec:{driver:{label:'LED Driver',value:'OLD'}}},items:[],editingIndex:0,currentQuoteId:1,currentApprovalStatus:'pending'};
 const $=id=>document.getElementById(id),esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
 function updateProductLinkHint(){$('productLinkHint').innerHTML='Product';}function loadItemToEditor(it){S.product=it.product;}function renderParts(){}function updatePriceLevelHint(){}function renderQuoteItems(){}function render(){}function syncEditingItemFromForm(){S.items[S.editingIndex]={product:JSON.parse(JSON.stringify(S.product))};}function autoAddSelectedProductLine(){S.items.push({product:JSON.parse(JSON.stringify(S.product))});S.editingIndex=S.items.length-1;}function saveQuote(){window.saved=true;}function addOrUpdateQuoteItem(){window.added=true;}
 async function refreshQuotePricePolicy(){}window.calls=[];window.delay=0;window.fail=false;window.pub=12;window.multiple=false;
 const versions=Array.from({length:12},(_,i)=>({snapshot_id:12-i,project_uid:'TEST',snapshot_uid:'BOMS-'+(12-i),name:'Acceptance <img src=x onerror=alert(1)> long BOM name',model:'52.98765',customer:'Acceptance',variant_label:'Variant',version_no:'V'+(12-i),cost_rmb:12-i===12?20:50,approved_at:'2026-09-21 10:00:00',current:i===0,publication_snapshot_id:12,published_at:i===0?'2026-09-21 10:00:01':''}));
 async function api(action,d){calls.push({action,d});await new Promise(r=>setTimeout(r,window.delay));if(window.fail)throw Error('模拟断网');if(action==='bom_quote_versions'){const n=d.page||1;return {versions:versions.slice((n-1)*10,n*10),page:n,pages:2,total:12,projects:1,legacy:[],current_publications:[{project_uid:'TEST',snapshot_id:12}]};}if(!d.snapshot_id&&multiple)return {choose:true,message:'选择BOM'};if(d.expected_publication!==undefined&&d.expected_publication!==pub)throw Error('BOM已产生新版本');const v=versions.find(v=>v.snapshot_id===(d.snapshot_id||12));return {version:v,patch:{cost_rmb:v.cost_rmb,price_rmb:v.cost_rmb,bom_version:{snapshot_id:v.snapshot_id,project_uid:'TEST',snapshot_uid:v.snapshot_uid,version_no:v.version_no,approved_at:v.approved_at,cost_rmb:v.cost_rmb},quote_spec:{driver:{label:'LED Driver',value:v.current?'NEW':'OLD'}}}};}`});
 await page.addScriptTag({content:fs.readFileSync('assets/quote-bom-versions.js','utf8')});
 await page.click('#start');await page.waitForSelector('[data-qbv-pick]');assert.equal(await page.locator('.qbv-list article').count(),10);assert.equal(await page.locator('.qbv-list img').count(),0);
 await page.click('[data-qbv-page="2"]');await page.waitForFunction(()=>document.querySelectorAll('.qbv-list article').length===2);
 await page.click('[data-qbv-pick="1"]');await page.waitForSelector('[data-qbv-apply]');assert((await page.locator('#qbvBody').textContent()).includes('历史版本'));await page.click('[data-qbv-close]');assert.equal(await page.evaluate(()=>S.product.cost_rmb),50);
 await page.click('#start');await page.waitForSelector('[data-qbv-pick="12"]');await page.click('[data-qbv-pick="12"]');await page.waitForSelector('[data-qbv-apply]');assert.equal(await page.evaluate(()=>S.product.cost_rmb),50);
 await page.click('[data-qbv-apply]');await page.waitForFunction(()=>!document.querySelector('#quoteBomVersions'));assert.equal(await page.evaluate(()=>S.items[0].product.cost_rmb),20);assert.equal(await page.inputValue('#manualPrice'),'88');assert.equal(await page.evaluate(()=>S.items[0].product.quote_spec.driver.value),'NEW');
 await page.evaluate(()=>S.currentApprovalStatus='approved');await page.click('#start');await page.waitForSelector('[data-qbv-pick="11"]');await page.click('[data-qbv-pick="11"]');await page.waitForSelector('[data-qbv-apply]');assert(await page.locator('[data-qbv-apply]').isDisabled());await page.click('[data-qbv-close]');
 await page.evaluate(()=>{S.currentApprovalStatus='pending';pub=13;});await page.click('#start');await page.waitForSelector('[data-qbv-pick="12"]');await page.click('[data-qbv-pick="12"]');await page.waitForFunction(()=>document.querySelector('#qbvFooter').textContent.includes('新版本'));assert.equal(await page.locator('[data-qbv-apply]').count(),0);await page.click('[data-qbv-close]');
 await page.evaluate(()=>pub=12);await page.click('#start');await page.waitForSelector('[data-qbv-pick="11"]');await page.click('[data-qbv-pick="11"]');await page.waitForSelector('[data-qbv-apply]');await page.evaluate(()=>pub=13);page.once('dialog',d=>d.dismiss());await page.click('[data-qbv-apply]');await page.waitForFunction(()=>!document.querySelector('[data-qbv-apply]').disabled);assert.equal(await page.evaluate(()=>S.product.bom_version.snapshot_id),12,'publication changed after preview must not apply');await page.click('[data-qbv-close]');
 await page.evaluate(()=>{pub=12;fail=true;});await page.click('#start');await page.waitForSelector('[role="alert"]');await page.evaluate(()=>fail=false);await page.click('[data-qbv-page="1"]');await page.waitForSelector('[data-qbv-pick="12"]');
 assert(!(await page.locator('.qbv-dialog').evaluate(e=>e.scrollWidth>e.clientWidth+2)),'dialog fits '+width);
 if(process.env.BOM_VERSION_SCREENSHOTS)await page.screenshot({path:process.env.BOM_VERSION_SCREENSHOTS+'/versions-'+width+'.png'});
 await page.click('[data-qbv-close]');
 await page.evaluate(()=>{multiple=true;S.product={id:3,code:'52.98765',cost_rmb:70};});assert.equal(await page.evaluate(()=>QuoteBomVersions.prepare(S.product)),false);await page.waitForSelector('[data-qbv-pick]');assert.equal(await page.evaluate(()=>S.product.cost_rmb),70,'ambiguous BOM cannot silently apply');assert(await page.evaluate(()=>S.product._bomBlocked));await page.click('[data-qbv-close]');await page.evaluate(()=>multiple=false);
 await page.evaluate(()=>{delay=100;window.pending=QuoteBomVersions.prepare(S.product);S.product={id:2,code:'OTHER',cost_rmb:9};});await page.evaluate(()=>pending);assert.equal(await page.evaluate(()=>S.product.cost_rmb),9);
 page.once('dialog',d=>d.dismiss());await page.evaluate(()=>{S.product._bomBlocked=true;saveQuote();});assert(!(await page.evaluate(()=>window.saved)));
 assert.deepEqual(errors,[]);await page.close();
}
console.log('BOM versions browser: paging, preview/cancel/confirm, history, frozen approved quotes, stale publication/product, retry, XSS and 390/768/1440 layout passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
