<?php
declare(strict_types=1);

return [
    'version' => '20260725_001_mm2_mm4_foundation',
    'description' => 'MM2 generic materials, MM3 power specs, MM4 legacy staging',
    'up' => [
        "CREATE TABLE IF NOT EXISTS mc_material_categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, parent_id BIGINT UNSIGNED NULL, status VARCHAR(20) NOT NULL DEFAULT 'active', sort_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_materials (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, material_uuid CHAR(36) NOT NULL UNIQUE, material_code VARCHAR(64) NOT NULL UNIQUE, category_id BIGINT UNSIGNED NOT NULL, brand VARCHAR(120) NULL, model VARCHAR(160) NULL, name VARCHAR(200) NOT NULL, unit VARCHAR(30) NULL, status VARCHAR(30) NOT NULL DEFAULT 'draft', source VARCHAR(30) NOT NULL DEFAULT 'manual', is_official TINYINT(1) NOT NULL DEFAULT 0, allow_bom TINYINT(1) NOT NULL DEFAULT 0, allow_quote TINYINT(1) NOT NULL DEFAULT 0, allow_customer_display TINYINT(1) NOT NULL DEFAULT 0, is_pilot TINYINT(1) NOT NULL DEFAULT 0, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL, INDEX idx_mc_material_category(category_id), INDEX idx_mc_material_search(brand,model,name), INDEX idx_mc_material_status(status,is_official)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_material_attributes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id BIGINT UNSIGNED NOT NULL, attribute_key VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, data_type VARCHAR(30) NOT NULL, unit VARCHAR(30) NULL, is_required TINYINT(1) NOT NULL DEFAULT 0, options_json JSON NULL, sort_order INT NOT NULL DEFAULT 0, UNIQUE KEY uq_mc_attr(category_id,attribute_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_material_attribute_values (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, material_id BIGINT UNSIGNED NOT NULL, attribute_id BIGINT UNSIGNED NOT NULL, value_text TEXT NULL, value_decimal DECIMAL(18,6) NULL, value_json JSON NULL, is_confirmed TINYINT(1) NOT NULL DEFAULT 0, updated_by BIGINT UNSIGNED NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_mc_attr_value(material_id,attribute_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_suppliers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, supplier_code VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(200) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_supplier_materials (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, supplier_id BIGINT UNSIGNED NOT NULL, material_id BIGINT UNSIGNED NOT NULL, supplier_model VARCHAR(160) NULL, supplier_material_code VARCHAR(100) NULL, moq DECIMAL(14,3) NULL, lead_time_days INT NULL, status VARCHAR(20) NOT NULL DEFAULT 'active', UNIQUE KEY uq_mc_supplier_material(supplier_id,material_id,supplier_model)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_supplier_prices (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, supplier_material_id BIGINT UNSIGNED NOT NULL, purchase_price DECIMAL(18,4) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'CNY', valid_from DATE NULL, valid_to DATE NULL, created_at DATETIME NOT NULL, INDEX idx_mc_supplier_price(supplier_material_id,valid_from)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_material_alternatives (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, material_id BIGINT UNSIGNED NOT NULL, alternative_material_id BIGINT UNSIGNED NOT NULL, relation_type VARCHAR(30) NOT NULL DEFAULT 'alternative', note VARCHAR(500) NULL, created_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, UNIQUE KEY uq_mc_alternative(material_id,alternative_material_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_material_documents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, material_id BIGINT UNSIGNED NOT NULL, document_type VARCHAR(50) NOT NULL, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, version VARCHAR(50) NULL, created_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, deleted_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_material_versions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, material_id BIGINT UNSIGNED NOT NULL, version_no INT NOT NULL, snapshot_json JSON NOT NULL, change_note VARCHAR(500) NULL, created_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, UNIQUE KEY uq_mc_material_version(material_id,version_no)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_legacy_links (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, source_table VARCHAR(80) NOT NULL, source_id BIGINT UNSIGNED NOT NULL, material_id BIGINT UNSIGNED NOT NULL, link_type VARCHAR(30) NOT NULL DEFAULT 'imported', decision VARCHAR(40) NULL, created_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_mc_legacy_source(source_table,source_id), INDEX idx_mc_legacy_material(material_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_activity_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, entity_type VARCHAR(60) NOT NULL, entity_id BIGINT UNSIGNED NULL, action VARCHAR(80) NOT NULL, before_json JSON NULL, after_json JSON NULL, actor_id BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, INDEX idx_mc_activity(entity_type,entity_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_power_bands (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(60) NOT NULL, min_power_w DECIMAL(8,2) NOT NULL, max_power_w DECIMAL(8,2) NOT NULL, max_inclusive TINYINT(1) NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'active', sort_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_power_supply_specs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, material_id BIGINT UNSIGNED NOT NULL UNIQUE, installation_type VARCHAR(30) NOT NULL DEFAULT 'unknown', output_type VARCHAR(30) NOT NULL DEFAULT 'unknown', quality_grade VARCHAR(30) NULL, supplier_warranty_years DECIMAL(4,1) NULL, product_customer_warranty_years DECIMAL(4,1) NULL, status VARCHAR(30) NOT NULL DEFAULT 'draft', nominal_power_w DECIMAL(8,2) NULL, max_output_power_w DECIMAL(8,2) NULL, power_band_id BIGINT UNSIGNED NULL, input_voltage_min_v DECIMAL(8,2) NULL, input_voltage_max_v DECIMAL(8,2) NULL, input_frequency_min_hz DECIMAL(8,2) NULL, input_frequency_max_hz DECIMAL(8,2) NULL, output_current_ma DECIMAL(10,2) NULL, output_current_min_ma DECIMAL(10,2) NULL, output_current_max_ma DECIMAL(10,2) NULL, is_dip_switch TINYINT(1) NOT NULL DEFAULT 0, is_programmable TINYINT(1) NOT NULL DEFAULT 0, output_voltage_min_v DECIMAL(8,2) NULL, output_voltage_max_v DECIMAL(8,2) NULL, length_mm DECIMAL(10,2) NULL, width_mm DECIMAL(10,2) NULL, height_mm DECIMAL(10,2) NULL, shape VARCHAR(50) NULL, mounting_hole_distance_mm DECIMAL(10,2) NULL, wiring_type VARCHAR(50) NULL, ip_rating VARCHAR(20) NULL, power_factor DECIMAL(6,4) NULL, efficiency DECIMAL(6,4) NULL, thd DECIMAL(6,3) NULL, flicker_grade VARCHAR(40) NULL, standby_power DECIMAL(8,3) NULL, purchase_price DECIMAL(18,4) NULL, currency CHAR(3) NULL, moq DECIMAL(14,3) NULL, lead_time_days INT NULL, certification VARCHAR(500) NULL, stock_status VARCHAR(40) NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX idx_mc_power_filter(power_band_id,installation_type,output_type,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_power_supply_dimming_modes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, material_id BIGINT UNSIGNED NOT NULL, mode VARCHAR(30) NOT NULL, is_primary TINYINT(1) NOT NULL DEFAULT 0, UNIQUE KEY uq_mc_power_dimming(material_id,mode)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_power_supply_current_options (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, material_id BIGINT UNSIGNED NOT NULL, current_ma DECIMAL(10,2) NOT NULL, is_default TINYINT(1) NOT NULL DEFAULT 0, source VARCHAR(30) NOT NULL DEFAULT 'manual', UNIQUE KEY uq_mc_power_current(material_id,current_ma)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_material_import_staging (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, source_table VARCHAR(80) NOT NULL, source_id BIGINT UNSIGNED NOT NULL, raw_category VARCHAR(160) NULL, raw_name VARCHAR(255) NULL, raw_brand VARCHAR(160) NULL, raw_model VARCHAR(200) NULL, raw_spec TEXT NULL, raw_price DECIMAL(18,4) NULL, raw_unit VARCHAR(50) NULL, raw_updated_at DATETIME NULL, raw_data_hash CHAR(64) NOT NULL, mapping_status VARCHAR(40) NOT NULL DEFAULT 'pending', is_pilot TINYINT(1) NOT NULL DEFAULT 0, staged_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_mc_staging_source(source_table,source_id), INDEX idx_mc_staging_status(mapping_status,is_pilot)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_material_parse_results (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, staging_id BIGINT UNSIGNED NOT NULL, field_key VARCHAR(80) NOT NULL, candidate_value VARCHAR(500) NULL, original_text TEXT NULL, confidence VARCHAR(20) NOT NULL, parse_rule VARCHAR(160) NOT NULL, is_human_confirmed TINYINT(1) NOT NULL DEFAULT 0, confirmed_value VARCHAR(500) NULL, confirmed_by BIGINT UNSIGNED NULL, confirmed_at DATETIME NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_mc_parse_field(staging_id,field_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_duplicate_candidates (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, staging_id BIGINT UNSIGNED NOT NULL, candidate_material_id BIGINT UNSIGNED NOT NULL, score DECIMAL(5,2) NOT NULL, matched_fields_json JSON NULL, decision VARCHAR(40) NOT NULL DEFAULT 'pending', decided_by BIGINT UNSIGNED NULL, decided_at DATETIME NULL, created_at DATETIME NOT NULL, UNIQUE KEY uq_mc_duplicate(staging_id,candidate_material_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "INSERT IGNORE INTO mc_material_categories(code,name,status,sort_order,created_at,updated_at) VALUES ('power_supply','电源','active',10,NOW(),NOW())",
        "INSERT IGNORE INTO mc_power_bands(code,name,min_power_w,max_power_w,max_inclusive,status,sort_order,created_at,updated_at) VALUES ('1_3','1–3W',1,3,0,'active',10,NOW(),NOW()),('3_5','3–5W',3,5,0,'active',20,NOW(),NOW()),('5_8','5–8W',5,8,0,'active',30,NOW(),NOW()),('8_15','8–15W',8,15,0,'active',40,NOW(),NOW()),('15_20','15–20W',15,20,0,'active',50,NOW(),NOW()),('20_25','20–25W',20,25,0,'active',60,NOW(),NOW()),('25_35','25–35W',25,35,0,'active',70,NOW(),NOW()),('35_50','35–50W',35,50,1,'active',80,NOW(),NOW())",
    ],
    'down' => [
        'DROP TABLE IF EXISTS mc_duplicate_candidates','DROP TABLE IF EXISTS mc_material_parse_results','DROP TABLE IF EXISTS mc_material_import_staging','DROP TABLE IF EXISTS mc_power_supply_current_options','DROP TABLE IF EXISTS mc_power_supply_dimming_modes','DROP TABLE IF EXISTS mc_power_supply_specs','DROP TABLE IF EXISTS mc_power_bands','DROP TABLE IF EXISTS mc_activity_logs','DROP TABLE IF EXISTS mc_legacy_links','DROP TABLE IF EXISTS mc_material_versions','DROP TABLE IF EXISTS mc_material_documents','DROP TABLE IF EXISTS mc_material_alternatives','DROP TABLE IF EXISTS mc_supplier_prices','DROP TABLE IF EXISTS mc_supplier_materials','DROP TABLE IF EXISTS mc_suppliers','DROP TABLE IF EXISTS mc_material_attribute_values','DROP TABLE IF EXISTS mc_material_attributes','DROP TABLE IF EXISTS mc_materials','DROP TABLE IF EXISTS mc_material_categories',
    ],
];
