<?php
declare(strict_types=1);

return [
    'version' => '20260725_002_framework_settings_permissions_matching',
    'description' => 'F3 settings, F4 permission grants and F9 product power matching foundation',
    'up' => [
        "CREATE TABLE IF NOT EXISTS mc_ui_settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, setting_key VARCHAR(100) NOT NULL UNIQUE, group_key VARCHAR(40) NOT NULL, default_json JSON NOT NULL, validation_json JSON NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_ui_setting_scopes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, scope_type VARCHAR(20) NOT NULL, scope_id VARCHAR(80) NOT NULL, setting_key VARCHAR(100) NOT NULL, value_json JSON NOT NULL, is_locked TINYINT(1) NOT NULL DEFAULT 0, version INT NOT NULL DEFAULT 1, updated_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_mc_setting_scope(scope_type,scope_id,setting_key), INDEX idx_mc_setting_resolve(setting_key,scope_type,scope_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_ui_themes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, tokens_json JSON NOT NULL, is_system TINYINT(1) NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'active', created_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_ui_theme_versions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, theme_id BIGINT UNSIGNED NOT NULL, version_no INT NOT NULL, tokens_json JSON NOT NULL, change_note VARCHAR(255) NULL, created_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, UNIQUE KEY uq_mc_theme_version(theme_id,version_no)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_user_preferences (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, legacy_user_id BIGINT UNSIGNED NOT NULL, preference_key VARCHAR(100) NOT NULL, value_json JSON NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_mc_user_pref(legacy_user_id,preference_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_role_preferences (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, legacy_role_key VARCHAR(80) NOT NULL, preference_key VARCHAR(100) NOT NULL, value_json JSON NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_mc_role_pref(legacy_role_key,preference_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_setting_audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, scope_type VARCHAR(20) NOT NULL, scope_id VARCHAR(80) NOT NULL, setting_key VARCHAR(100) NOT NULL, before_json JSON NULL, after_json JSON NULL, actor_id BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, INDEX idx_mc_setting_audit(scope_type,scope_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_permissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, permission_key VARCHAR(100) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL, level VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_permission_grants (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, subject_type VARCHAR(20) NOT NULL, subject_id VARCHAR(80) NOT NULL, permission_key VARCHAR(100) NOT NULL, effect VARCHAR(10) NOT NULL DEFAULT 'allow', field_scope_json JSON NULL, data_scope_json JSON NULL, expires_at DATETIME NULL, granted_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_mc_permission_grant(subject_type,subject_id,permission_key), INDEX idx_mc_permission_subject(subject_type,subject_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_permission_audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, subject_type VARCHAR(20) NOT NULL, subject_id VARCHAR(80) NOT NULL, permission_key VARCHAR(100) NOT NULL, action VARCHAR(30) NOT NULL, actor_id BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_product_power_rules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, legacy_product_table VARCHAR(80) NOT NULL DEFAULT 'naming_models', legacy_product_id BIGINT UNSIGNED NOT NULL, rule_name VARCHAR(160) NOT NULL, installation_type VARCHAR(30) NOT NULL DEFAULT 'unknown', output_type VARCHAR(30) NOT NULL DEFAULT 'unknown', lamp_power_w DECIMAL(8,2) NULL, power_band_id BIGINT UNSIGNED NULL, output_current_min_ma DECIMAL(10,2) NULL, output_current_max_ma DECIMAL(10,2) NULL, output_voltage_min_v DECIMAL(8,2) NULL, output_voltage_max_v DECIMAL(8,2) NULL, max_length_mm DECIMAL(10,2) NULL, max_width_mm DECIMAL(10,2) NULL, max_height_mm DECIMAL(10,2) NULL, minimum_warranty_years DECIMAL(4,1) NULL, certification_required VARCHAR(500) NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_mc_product_power_rule(legacy_product_table,legacy_product_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_product_power_rule_dimming_modes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, rule_id BIGINT UNSIGNED NOT NULL, mode VARCHAR(30) NOT NULL, UNIQUE KEY uq_mc_rule_dimming(rule_id,mode)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_product_power_rule_brands (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, rule_id BIGINT UNSIGNED NOT NULL, brand VARCHAR(120) NOT NULL, UNIQUE KEY uq_mc_rule_brand(rule_id,brand)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_product_power_approved_alternatives (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, rule_id BIGINT UNSIGNED NOT NULL, material_id BIGINT UNSIGNED NOT NULL, decision VARCHAR(30) NOT NULL DEFAULT 'approved', note VARCHAR(500) NULL, approved_by BIGINT UNSIGNED NULL, approved_at DATETIME NOT NULL, UNIQUE KEY uq_mc_rule_alternative(rule_id,material_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_power_match_simulations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, rule_id BIGINT UNSIGNED NOT NULL, result_json JSON NOT NULL, actor_id BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, INDEX idx_mc_match_simulation(rule_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "INSERT IGNORE INTO mc_permissions(permission_key,name,level,created_at) VALUES ('material_center.view','访问物料中心','module',NOW()),('material_center.settings.view','查看设置','page',NOW()),('material_center.settings.manage_self','维护个人设置','action',NOW()),('material_center.settings.manage_global','维护全局设置','action',NOW()),('material_center.power.standardize','电源标准化','action',NOW()),('material_center.power.confirm','确认正式电源','action',NOW()),('material_center.power.rules.view','查看产品电源规则','page',NOW()),('material_center.power.rules.manage','维护产品电源规则','action',NOW()),('material_center.power.simulate','运行匹配模拟','action',NOW())",
        "INSERT IGNORE INTO mc_ui_settings(setting_key,group_key,default_json,validation_json,created_at,updated_at) VALUES ('theme.mode','theme','\"light\"','{\"type\":\"enum\",\"values\":[\"light\",\"dark\",\"system\"]}',NOW(),NOW()),('theme.primary','theme','\"#d60000\"','{\"type\":\"color\"}',NOW(),NOW()),('theme.sidebar','theme','\"#ffffff\"','{\"type\":\"color\"}',NOW(),NOW()),('font.family','font','\"system\"','{\"type\":\"enum\",\"values\":[\"system\",\"noto_sans_sc\",\"arial\"]}',NOW(),NOW()),('font.base_px','font','14','{\"type\":\"number\",\"min\":12,\"max\":18}',NOW(),NOW()),('font.table_px','font','13','{\"type\":\"number\",\"min\":11,\"max\":17}',NOW(),NOW()),('font.nav_px','font','14','{\"type\":\"number\",\"min\":12,\"max\":18}',NOW(),NOW()),('layout.density','layout','\"comfortable\"','{\"type\":\"enum\",\"values\":[\"compact\",\"comfortable\",\"spacious\"]}',NOW(),NOW()),('layout.sidebar','layout','\"expanded\"','{\"type\":\"enum\",\"values\":[\"expanded\",\"collapsed\"]}',NOW(),NOW()),('motion.enabled','feedback','true','{\"type\":\"boolean\"}',NOW(),NOW()),('feedback.toast','feedback','true','{\"type\":\"boolean\"}',NOW(),NOW()),('table.page_size','table','20','{\"type\":\"number\",\"min\":10,\"max\":100}',NOW(),NOW())",
        "INSERT IGNORE INTO mc_ui_themes(code,name,tokens_json,is_system,status,created_at,updated_at) VALUES ('professional_white','专业白','{\"primary\":\"#d60000\",\"sidebar\":\"#ffffff\",\"page\":\"#f4f6f8\"}',1,'active',NOW(),NOW()),('deep_navy','深蓝展示','{\"primary\":\"#d60000\",\"sidebar\":\"#102a43\",\"page\":\"#f4f6f8\"}',1,'active',NOW(),NOW())",
    ],
    'down' => [
        'DROP TABLE IF EXISTS mc_power_match_simulations','DROP TABLE IF EXISTS mc_product_power_approved_alternatives','DROP TABLE IF EXISTS mc_product_power_rule_brands','DROP TABLE IF EXISTS mc_product_power_rule_dimming_modes','DROP TABLE IF EXISTS mc_product_power_rules','DROP TABLE IF EXISTS mc_permission_audit_logs','DROP TABLE IF EXISTS mc_permission_grants','DROP TABLE IF EXISTS mc_permissions','DROP TABLE IF EXISTS mc_setting_audit_logs','DROP TABLE IF EXISTS mc_role_preferences','DROP TABLE IF EXISTS mc_user_preferences','DROP TABLE IF EXISTS mc_ui_theme_versions','DROP TABLE IF EXISTS mc_ui_themes','DROP TABLE IF EXISTS mc_ui_setting_scopes','DROP TABLE IF EXISTS mc_ui_settings',
    ],
];
