<?php
declare(strict_types=1);
$tables=['power_supply'=>'mc_power_supply_specs','chip'=>'mc_material_chip','optical'=>'mc_material_optical','profile'=>'mc_material_profile','connector'=>'mc_material_connector','accessory'=>'mc_material_accessory','packaging'=>'mc_material_packaging'];
$fields=[
 ['power_supply','power.installation_type','安装方式','text',null,'installation_type',100],['power_supply','power.output_type','输出类型','text',null,'output_type',110],
 ['power_supply','power.nominal_power_w','额定功率','decimal','W','nominal_power_w',120],['power_supply','power.max_output_power_w','最大输出功率','decimal','W','max_output_power_w',130],
 ['power_supply','power.input_voltage_min_v','输入电压最小','decimal','V','input_voltage_min_v',140],['power_supply','power.input_voltage_max_v','输入电压最大','decimal','V','input_voltage_max_v',150],
 ['power_supply','power.input_frequency_min_hz','输入频率最小','decimal','Hz','input_frequency_min_hz',160],['power_supply','power.input_frequency_max_hz','输入频率最大','decimal','Hz','input_frequency_max_hz',170],
 ['power_supply','power.output_current_ma','输出电流','decimal','mA','output_current_ma',180],['power_supply','power.output_current_min_ma','输出电流最小','decimal','mA','output_current_min_ma',190],['power_supply','power.output_current_max_ma','输出电流最大','decimal','mA','output_current_max_ma',200],
 ['power_supply','power.output_voltage_min_v','输出电压最小','decimal','V','output_voltage_min_v',210],['power_supply','power.output_voltage_max_v','输出电压最大','decimal','V','output_voltage_max_v',220],
 ['power_supply','power.length_mm','长度','decimal','mm','length_mm',230],['power_supply','power.width_mm','宽度','decimal','mm','width_mm',240],['power_supply','power.height_mm','高度','decimal','mm','height_mm',250],
 ['power_supply','power.ip_rating','防护等级','text',null,'ip_rating',260],['power_supply','power.power_factor','功率因数','decimal',null,'power_factor',270],['power_supply','power.efficiency','效率','decimal',null,'efficiency',280],
 ['power_supply','power.certification','认证','text',null,'certification',290],['power_supply','power.supplier_warranty_years','供应商质保','decimal','年','supplier_warranty_years',300],
 ['chip','chip.package_type','封装','text',null,'package_type',100],['chip','chip.light_source_type','光源类型','text',null,'light_source_type',110],['chip','chip.rated_power_w','额定功率','decimal','W','rated_power_w',120],['chip','chip.max_power_w','最大功率','decimal','W','max_power_w',130],
 ['chip','chip.voltage_v','电压','decimal','V','voltage_v',140],['chip','chip.current_ma','电流','decimal','mA','current_ma',150],['chip','chip.cct_min_k','色温最小','integer','K','cct_min_k',160],['chip','chip.cct_max_k','色温最大','integer','K','cct_max_k',170],['chip','chip.cri','显色指数','decimal','Ra','cri',180],['chip','chip.luminous_flux_lm','光通量','decimal','lm','luminous_flux_lm',190],['chip','chip.efficacy_lm_w','光效','decimal','lm/W','efficacy_lm_w',200],['chip','chip.sdcm','SDCM','decimal',null,'sdcm',210],['chip','chip.r9','R9','decimal',null,'r9',220],['chip','chip.size_text','尺寸','text',null,'size_text',230],['chip','chip.pad_text','焊盘','text',null,'pad_text',240],['chip','chip.lifetime_hours','寿命','integer','h','lifetime_hours',250],['chip','chip.certification','认证','text',null,'certification',260],
 ['optical','optical.optical_type','光学类型','text',null,'optical_type',100],['optical','optical.compatible_chip','适配芯片','text',null,'compatible_chip',110],['optical','optical.diameter_mm','直径','decimal','mm','diameter_mm',120],['optical','optical.height_mm','高度','decimal','mm','height_mm',130],['optical','optical.beam_angle_min','光束角最小','decimal','°','beam_angle_min',140],['optical','optical.beam_angle_max','光束角最大','decimal','°','beam_angle_max',150],['optical','optical.material_text','材质','text',null,'material_text',160],['optical','optical.transmittance','透光率','decimal',null,'transmittance',170],['optical','optical.beam_shape','光型','text',null,'beam_shape',180],['optical','optical.color','颜色','text',null,'color',190],['optical','optical.mounting_structure','安装结构','text',null,'mounting_structure',200],
 ['profile','profile.profile_type','型材类型','text',null,'profile_type',100],['profile','profile.material_grade','材料牌号','text',null,'material_grade',110],['profile','profile.length_mm','长度','decimal','mm','length_mm',120],['profile','profile.width_mm','宽度','decimal','mm','width_mm',130],['profile','profile.height_mm','高度','decimal','mm','height_mm',140],['profile','profile.diameter_mm','直径','decimal','mm','diameter_mm',150],['profile','profile.weight_g','重量','decimal','g','weight_g',160],['profile','profile.thermal_capacity','散热能力','text',null,'thermal_capacity',170],['profile','profile.surface_treatment','表面处理','text',null,'surface_treatment',180],['profile','profile.color','颜色','text',null,'color',190],['profile','profile.processing_status','加工状态','text',null,'processing_status',200],['profile','profile.drawing_version','图纸版本','text',null,'drawing_version',210],
 ['connector','connector.connector_type','接头类型','text',null,'connector_type',100],['connector','connector.system_type','系统类型','text',null,'system_type',110],['connector','connector.electrical_spec','电气规格','text',null,'electrical_spec',120],['connector','connector.installation_type','安装方式','text',null,'installation_type',130],['connector','connector.interface_type','接口类型','text',null,'interface_type',140],['connector','connector.color','颜色','text',null,'color',150],['connector','connector.size_text','尺寸','text',null,'size_text',160],['connector','connector.load_kg','承重','decimal','kg','load_kg',170],['connector','connector.material_text','材质','text',null,'material_text',180],['connector','connector.ip_rating','防护等级','text',null,'ip_rating',190],['connector','connector.compatible_product_text','适配产品','textarea',null,'compatible_product_text',200],
 ['accessory','accessory.accessory_type','配件类别','text',null,'accessory_type',100],['accessory','accessory.size_text','尺寸','text',null,'size_text',110],['accessory','accessory.color','颜色','text',null,'color',120],['accessory','accessory.material_text','材质','text',null,'material_text',130],['accessory','accessory.installation_position','安装位置','text',null,'installation_position',140],['accessory','accessory.compatible_product_text','适配产品','textarea',null,'compatible_product_text',150],['accessory','accessory.compatible_optical_text','适配光学','textarea',null,'compatible_optical_text',160],['accessory','accessory.price_impact','价格影响','decimal','currency','price_impact',170],['accessory','accessory.customer_selectable','客户可选','boolean',null,'customer_selectable',180],
 ['packaging','packaging.packaging_type','包装类别','text',null,'packaging_type',100],['packaging','packaging.inner_size','内尺寸','text',null,'inner_size',110],['packaging','packaging.outer_size','外尺寸','text',null,'outer_size',120],['packaging','packaging.material_text','材质','text',null,'material_text',130],['packaging','packaging.grammage','克重','decimal','g','grammage',140],['packaging','packaging.printing_method','印刷方式','text',null,'printing_method',150],['packaging','packaging.color','颜色','text',null,'color',160],['packaging','packaging.packing_quantity','装箱数量','decimal',null,'packing_quantity',170],['packaging','packaging.net_weight_kg','净重','decimal','kg','net_weight_kg',180],['packaging','packaging.gross_weight_kg','毛重','decimal','kg','gross_weight_kg',190],['packaging','packaging.customer_specific','客户专属','boolean',null,'customer_specific',200],
];
$quote=static fn(?string$value):string=>$value===null?'NULL':"'".str_replace("'","''",$value)."'";
$up=["ALTER TABLE mc_field_registry ADD COLUMN storage_target VARCHAR(140) NULL AFTER field_code"];
$codes=[];
foreach($fields as[$category,$code,$label,$type,$unit,$column,$sort]){
 $codes[]=$code;$target=$tables[$category].'.'.$column;$validation=in_array($type,['decimal','integer'],true)?'{"min":0}':(in_array($type,['text','textarea'],true)?'{"maxLength":2000}':null);
 $up[]="INSERT INTO mc_field_registry(field_code,storage_target,field_name,data_type,unit,is_required,validation_json,default_json,allow_batch,is_sensitive,customer_visible,allow_import,use_for_duplicate,use_for_adaptation,status,sort_order) VALUES(".$quote($code).','.$quote($target).','.$quote($label).','.$quote($type).','.$quote($unit).",0,".$quote($validation).",NULL,1,0,1,1,1,1,'active',".(int)$sort.") ON DUPLICATE KEY UPDATE storage_target=VALUES(storage_target),field_name=VALUES(field_name),data_type=VALUES(data_type),unit=VALUES(unit),validation_json=VALUES(validation_json),sort_order=VALUES(sort_order)";
 $up[]="INSERT IGNORE INTO mc_category_field_map(category_code,field_id,is_required,sort_order) SELECT ".$quote($category).",id,0,".(int)$sort." FROM mc_field_registry WHERE field_code=".$quote($code);
}
$codeList=implode(',',array_map($quote,$codes));
return['version'=>'20260726_010_complete_category_fields','description'=>'Complete registered field coverage for all seven category extension tables','up'=>$up,'down'=>[
 "DELETE m FROM mc_category_field_map m JOIN mc_field_registry f ON f.id=m.field_id WHERE f.field_code IN($codeList)",
 "DELETE FROM mc_field_registry WHERE field_code IN($codeList) AND field_code NOT IN('power.nominal_power_w','power.output_current_ma','chip.cri','profile.material_grade','connector.interface_type','accessory.accessory_type','packaging.packaging_type')",
 "UPDATE mc_field_registry SET storage_target=NULL WHERE field_code IN('power.nominal_power_w','power.output_current_ma','chip.cri','profile.material_grade','connector.interface_type','accessory.accessory_type','packaging.packaging_type')",
 "ALTER TABLE mc_field_registry DROP COLUMN storage_target",
 "INSERT IGNORE INTO mc_category_field_map(category_code,field_id,is_required,sort_order) SELECT CASE WHEN field_code LIKE 'power.%' THEN 'power_supply' WHEN field_code LIKE 'chip.%' THEN 'chip' WHEN field_code LIKE 'profile.%' THEN 'profile' WHEN field_code LIKE 'connector.%' THEN 'connector' WHEN field_code LIKE 'accessory.%' THEN 'accessory' WHEN field_code LIKE 'packaging.%' THEN 'packaging' END,id,is_required,sort_order FROM mc_field_registry WHERE field_code IN('power.nominal_power_w','power.output_current_ma','chip.cri','profile.material_grade','connector.interface_type','accessory.accessory_type','packaging.packaging_type')",
]];
