<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/bootstrap.php';
header('Content-Type: text/html; charset=utf-8');
header('X-Content-Type-Options: nosniff');
?>
<!doctype html>
<html lang="zh-CN" data-theme="system">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Artdon UI 组件展厅</title>
  <link rel="stylesheet" href="../index.css">
  <style>
    .gallery{max-width:1100px;margin:auto;padding:24px}.gallery-head{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:20px}
    .gallery-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.gallery .ui-card-body{display:grid;gap:14px}.gallery-wide{grid-column:1/-1}
    .demo-row{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.demo-form{display:grid;grid-template-columns:1fr 1fr;gap:12px}
    @media(max-width:720px){.gallery-grid,.demo-form{grid-template-columns:1fr}}
  </style>
</head>
<body>
<main class="gallery">
  <header class="gallery-head"><div><span class="ui-eyebrow">ARTDON DESIGN SYSTEM</span><h1>物料中心 UI 组件展厅</h1><p class="ui-muted">统一组件的真实交互与状态基准。</p></div><a class="ui-btn ui-btn-secondary" href="../../">返回物料中心</a></header>
  <div class="gallery-grid">
    <section class="ui-card"><div class="ui-card-header"><strong>按钮与徽章</strong><span class="ui-badge">基础</span></div><div class="ui-card-body"><div class="demo-row"><button class="ui-btn" data-ui-demo-feedback>主要按钮</button><button class="ui-btn ui-btn-secondary" data-ui-demo-feedback>次要按钮</button><button class="ui-btn ui-btn-ghost" data-ui-demo-feedback>文字按钮</button><button class="ui-btn ui-btn-danger" data-ui-demo-feedback>危险按钮</button><button class="ui-btn" disabled>禁用</button></div><div class="demo-row"><span class="ui-badge">信息</span><span class="ui-badge ui-badge-success">已启用</span><button class="ui-btn ui-btn-icon ui-tooltip" data-tooltip="这是工具提示" data-ui-demo-feedback aria-label="提示">?</button></div></div></section>
    <section class="ui-card"><div class="ui-card-header"><strong>表单控件与状态</strong></div><div class="ui-card-body demo-form"><label class="ui-field"><span class="ui-label">物料名称</span><input class="ui-input" value="铝型材"><small class="ui-help">默认输入状态</small></label><label class="ui-field"><span class="ui-label">分类 / Select</span><select class="ui-select"><option>型材</option><option>灯珠</option></select><small class="ui-help">统一美化选择器</small></label><label class="ui-field"><span class="ui-label">只读</span><input class="ui-input" value="可复制，不可修改" readonly><small class="ui-help">只读状态</small></label><label class="ui-field"><span class="ui-label">错误</span><input class="ui-input" value="非法值" aria-invalid="true"><small class="ui-help ui-error">字段格式不正确</small></label><label class="ui-check"><input type="checkbox" checked><span class="ui-check-box"></span><span>复选框文字可点击</span></label><label class="ui-check"><input type="radio" name="demo" checked><span class="ui-radio-mark"></span><span>统一单选框</span></label><label class="ui-switch"><input type="checkbox"><span class="ui-switch-track"></span><span>统一开关</span></label><label class="ui-field"><span class="ui-label">Textarea</span><textarea class="ui-textarea">多行输入</textarea></label></div></section>
    <section class="ui-card"><div class="ui-card-header"><strong>浮层与反馈</strong></div><div class="ui-card-body"><div class="demo-row"><button class="ui-btn" data-ui-modal-open="#gallery-modal">Modal M</button><button class="ui-btn ui-btn-secondary" id="confirm-demo">ConfirmModal</button><button class="ui-btn ui-btn-secondary" data-ui-drawer-open="#gallery-drawer">Drawer</button><button class="ui-btn ui-btn-secondary" onclick="ArtdonUI.toast('操作已完成','success')">成功 Toast</button><button class="ui-btn ui-btn-secondary" onclick="ArtdonUI.toast('网络请求失败','danger',0)">错误 Toast</button><div class="ui-dropdown"><button class="ui-btn ui-btn-secondary" aria-expanded="false" aria-controls="gallery-menu" data-ui-dropdown-trigger>下拉菜单</button><div class="ui-menu" id="gallery-menu" role="menu" aria-hidden="true"><button role="menuitem" data-ui-not-connected>查看详情</button><button role="menuitem" data-ui-not-connected>复制编号</button><button role="menuitem" data-ui-not-connected>未接入功能</button></div></div></div></div></section>
    <section class="ui-card"><div class="ui-card-header"><strong>字体层级与 Tabs</strong></div><div class="ui-card-body"><h1>页面主标题 24px</h1><h2>模块标题 16px</h2><p>正文使用统一 14px 系统字体，适合长时间办公。</p><small class="ui-muted">辅助文字 12px</small><div class="ui-tabs" role="tablist"><button class="ui-tab" aria-selected="true">基础信息</button><button class="ui-tab" aria-selected="false">属性</button><button class="ui-tab" aria-selected="false">历史</button></div></div></section>
    <section class="ui-card gallery-wide ui-table-panel"><div class="ui-card-header"><strong>统一 DataTable</strong><button class="ui-btn ui-btn-secondary ui-btn-sm" data-ui-table-settings="#gallery-table">列与密度</button></div><div class="ui-table-wrap"><table class="ui-table" id="gallery-table" data-ui-table data-page-size="10"><thead><tr><th class="ui-select-col"><label class="ui-check ui-check-only"><input type="checkbox" data-ui-select-all><span class="ui-check-box"></span></label></th><th data-sort="number">ID</th><th data-sort>名称</th><th data-sort>状态</th><th class="ui-action-col">操作</th></tr></thead><tbody><?php for($i=1;$i<=12;$i++): ?><tr><td><label class="ui-check ui-check-only"><input type="checkbox" data-ui-row-select><span class="ui-check-box"></span></label></td><td><?= $i ?></td><td>组件示例 <?= $i ?></td><td><span class="ui-badge ui-badge-success">可用</span></td><td class="ui-action-col"><button class="ui-link-button" onclick="ArtdonUI.toast('已查看第 <?= $i ?> 行')">查看</button></td></tr><?php endfor; ?></tbody></table></div></section>
    <section class="ui-card gallery-wide"><div class="ui-card-header"><strong>页面状态</strong></div><div class="ui-card-body"><div class="demo-row"><button class="ui-btn ui-btn-secondary" data-state-demo="loading">加载</button><button class="ui-btn ui-btn-secondary" data-state-demo="empty">空数据</button><button class="ui-btn ui-btn-secondary" data-state-demo="error">错误</button><button class="ui-btn ui-btn-secondary" data-state-demo="permission">无权限</button><button class="ui-btn ui-btn-secondary" data-state-demo="config">未配置</button></div><div class="ui-state" id="state-demo"><div class="ui-state-inner"><div class="ui-state-icon">…</div><h2>正在加载</h2><p>正在获取最新数据，请稍候。</p><div class="ui-skeleton"></div></div></div></div></section>
  </div>
</main>
<div class="ui-modal ui-modal-m" id="gallery-modal" role="dialog" aria-modal="true" aria-hidden="true" tabindex="-1"><div class="ui-modal-header"><strong>标准 M 弹窗（640px）</strong><button class="ui-btn ui-btn-secondary ui-btn-icon" data-ui-close aria-label="关闭">×</button></div><div class="ui-modal-body"><label class="ui-field"><span class="ui-label">演示字段</span><input class="ui-input" value="统一弹窗"><small class="ui-help">支持 Esc、遮罩、取消和焦点回归。</small></label></div><div class="ui-modal-footer"><button class="ui-btn ui-btn-secondary" data-ui-close>取消</button><button class="ui-btn" id="save-demo">保存</button></div></div>
<aside class="ui-drawer ui-drawer-m" id="gallery-drawer" role="dialog" aria-modal="true" aria-hidden="true" tabindex="-1"><div class="ui-drawer-header"><h2>统一详情抽屉（520px）</h2><button class="ui-btn ui-btn-secondary ui-btn-icon" data-ui-close aria-label="关闭">×</button></div><div class="ui-drawer-body"><p>复杂详情使用抽屉，不生成超宽弹窗。</p></div><div class="ui-drawer-footer">Artdon UI</div></aside>
<div class="ui-mask" data-ui-mask></div><div class="ui-toast-region" data-ui-toast-region role="status" aria-live="polite"></div>
<script src="../js/interaction-manager.js"></script><script src="../js/confirm-modal.js"></script><script src="../js/dropdown.js"></script><script src="../js/modal.js"></script><script src="../js/drawer.js"></script><script src="../js/toast.js"></script><script src="../js/table.js"></script><script src="../js/app-shell.js"></script>
<script>
document.querySelector('#confirm-demo').addEventListener('click',e=>ArtdonUI.confirm({title:'确认只读演示？',message:'这是统一确认弹窗，不会写入任何数据。',confirmLabel:'确认演示',trigger:e.currentTarget,onConfirm:()=>ArtdonUI.toast('确认事件已执行','success')}));
document.querySelectorAll('[data-ui-demo-feedback]').forEach(button=>button.addEventListener('click',()=>ArtdonUI.toast(`${button.textContent.trim()}事件已触发`)));
document.querySelector('#save-demo').addEventListener('click',e=>{const b=e.currentTarget;b.disabled=true;b.classList.add('is-loading');b.textContent='保存中…';setTimeout(()=>{b.disabled=false;b.classList.remove('is-loading');b.textContent='保存';ArtdonUI.toast('演示状态已更新','success');ArtdonUI.interactions.close({force:true});},500)});
const states={loading:['…','正在加载','正在获取最新数据，请稍候。'],empty:['0','暂无数据','当前筛选没有结果，请调整条件。'],error:['!','加载失败','网络或服务暂时不可用，请稍后重试。'],permission:['锁','无访问权限','需要相应权限，请联系管理员。'],config:['⚙','功能尚未配置','该功能尚未接入，不会显示虚假成功。']};
document.addEventListener('click',e=>{const type=e.target.dataset.stateDemo;if(!type)return;const [icon,title,text]=states[type];const el=document.querySelector('#state-demo');el.className='ui-state ui-state-'+type;el.querySelector('.ui-state-icon').textContent=icon;el.querySelector('h2').textContent=title;el.querySelector('p').textContent=text;});
</script>
</body></html>
