<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/bootstrap.php';
use Artdon\MaterialCenter\Security\MaterialCenterUserContext;
use Artdon\MaterialCenter\Security\PermissionService;
use Artdon\MaterialCenter\Services\AdaptationService;
use Artdon\MaterialCenter\Services\MaterialBatchService;
use Artdon\MaterialCenter\Services\MaterialMasterService;
use Artdon\MaterialCenter\Services\SupplierService;
$db=db();$tag='FINAL-'.date('YmdHis').'-'.bin2hex(random_bytes(2));$userId=1;
$materialIds=[];$supplierId=0;$productId=0;$groupIds=[];$optionIds=[];$priceId=0;$grantId=0;
$legacyBefore=(int)$db->query('SELECT COUNT(*) FROM bom_materials')->fetchColumn();
$legacySignature=(string)$db->query("SELECT SHA2(GROUP_CONCAT(CONCAT(COLUMN_NAME,':',COLUMN_TYPE,':',IS_NULLABLE,':',COLUMN_KEY) ORDER BY ORDINAL_POSITION SEPARATOR '|'),256) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='bom_materials'")->fetchColumn();
try{
 $categories=$db->query("SELECT code,id FROM mc_material_categories WHERE status='active'")->fetchAll(PDO::FETCH_KEY_PAIR);
 foreach(['power_supply','chip','optical','profile','connector','accessory','packaging']as$category)if(!isset($categories[$category]))throw new RuntimeException("missing category $category");
 $master=new MaterialMasterService($db);
 $power=$master->save(['category_id'=>$categories['power_supply'],'name'=>$tag.' power','brand'=>'TEST','model'=>'P1','unit'=>'PCS'],$userId);$materialIds[]=$power;
 $chip=$master->save(['category_id'=>$categories['chip'],'name'=>$tag.' chip','brand'=>'TEST','model'=>'C1','unit'=>'PCS'],$userId);$materialIds[]=$chip;
 $copy=$master->copy($chip,$userId);$materialIds[]=$copy;
 $master->transition($power,'submit',$userId);$master->transition($power,'approve',$userId);
 $context=new MaterialCenterUserContext($userId,'final-test','Final Test','admin',true);
 $batch=new MaterialBatchService($db);$preview=$batch->preview([$power,$chip],['brand'=>'FINAL-BATCH'],'overwrite',$context);if($preview['affected']!==2)throw new RuntimeException('cross-category batch preview failed');
 $batchResult=$batch->execute([$power,$chip],['brand'=>'FINAL-BATCH'],'overwrite',$context);if($batchResult['success']!==2)throw new RuntimeException('cross-category batch execute failed');
 $supplier=new SupplierService($db);$supplierId=$supplier->saveSupplier(['supplier_code'=>$tag,'name'=>$tag.' supplier','default_currency'=>'CNY','contact_name'=>'Test Contact'],$userId);
 $priceId=$supplier->savePrice(['supplier_id'=>$supplierId,'material_id'=>$power,'supplier_model'=>'T1','purchase_price'=>'12.3400','currency'=>'CNY','moq'=>'10','package_qty'=>'5','lead_time_days'=>'7','tiers'=>[['min_qty'=>10,'unit_price'=>12.34],['min_qty'=>100,'unit_price'=>11.50]]],$userId);
 $status=$db->query('SELECT approval_status FROM mc_supplier_prices WHERE id='.(int)$priceId)->fetchColumn();if($status!=='pending')throw new RuntimeException('supplier price did not enter approval');
 $supplier->approvePrice($priceId,$userId,'approve','final acceptance');if($db->query('SELECT approval_status FROM mc_supplier_prices WHERE id='.(int)$priceId)->fetchColumn()!=='approved')throw new RuntimeException('supplier price approval failed');
 $db->prepare("INSERT INTO mc_products(legacy_table,legacy_id,product_code,product_name,snapshot_json,snapshot_hash,synced_at,status)VALUES('final_test',?,?,?,?,?,NOW(),'active')")->execute([time(),$tag,$tag.' product','{}',hash('sha256',$tag)]);$productId=(int)$db->lastInsertId();
 $adapt=new AdaptationService($db);$groupIds[]=$adapt->saveGroup(['product_id'=>$productId,'group_code'=>'power','group_name'=>'Power','group_type'=>'power'],$userId);
 $optionIds[]=$adapt->saveOption(['group_id'=>$groupIds[0],'material_id'=>$power,'option_type'=>'optional','price_impact'=>'5','lead_time_impact_days'=>'2','is_default'=>1,'conditions'=>[['field_code'=>'voltage','operator'=>'gte','expected'=>220,'failure_message'=>'电压不足','severity'=>'block']]],$userId);
 $optionIds[]=$adapt->saveOption(['group_id'=>$groupIds[0],'material_id'=>$chip,'option_type'=>'alternative','price_impact'=>'2','lead_time_impact_days'=>'1'],$userId);
 $adapt->saveConflict(['product_id'=>$productId,'left_option_id'=>$optionIds[0],'right_option_id'=>$optionIds[1],'reason'=>'测试组合冲突','severity'=>'block'],$userId);
 $evaluation=$adapt->evaluate($productId,$optionIds,['voltage'=>230]);if($evaluation['compatible']||!array_filter($evaluation['reasons'],fn($r)=>$r['reason']==='测试组合冲突'))throw new RuntimeException('adaptation conflict evaluation failed');
 $adapt->approveProduct($productId,$userId);if(count($adapt->approved(time()))!==0){/* legacy table differs intentionally */}
 $role='final_readonly_'.$tag;$db->prepare("INSERT INTO mc_permission_grants(subject_type,subject_id,permission_key,effect,created_at,updated_at)VALUES('role',?,'material_center.view','allow',NOW(),NOW())")->execute([$role]);$grantId=(int)$db->lastInsertId();
 $readonly=new MaterialCenterUserContext(987654,'readonly','Read Only',$role,false);if(!(new PermissionService($db))->allows($readonly,'material_center.view')||(new PermissionService($db))->allows($readonly,'material_center.material.edit'))throw new RuntimeException('role permission isolation failed');
 if((int)$db->query('SELECT COUNT(*) FROM bom_materials')->fetchColumn()!==$legacyBefore)throw new RuntimeException('legacy BOM row count changed');
 $signatureAfter=(string)$db->query("SELECT SHA2(GROUP_CONCAT(CONCAT(COLUMN_NAME,':',COLUMN_TYPE,':',IS_NULLABLE,':',COLUMN_KEY) ORDER BY ORDINAL_POSITION SEPARATOR '|'),256) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='bom_materials'")->fetchColumn();if(!hash_equals($legacySignature,$signatureAfter))throw new RuntimeException('legacy BOM schema changed');
 echo "functional/data/permission integration: OK\n";
}finally{
 if($grantId)$db->exec('DELETE FROM mc_permission_grants WHERE id='.(int)$grantId);
 if($productId){$approvalIds=$db->query('SELECT approval_id FROM mc_adaptation_approvals WHERE product_id='.(int)$productId)->fetchAll(PDO::FETCH_COLUMN);if($approvalIds){$list=implode(',',array_map('intval',$approvalIds));$db->exec("DELETE FROM mc_approval_logs WHERE approval_id IN($list)");$db->exec("DELETE FROM mc_approvals WHERE id IN($list)");}$db->exec('DELETE FROM mc_adaptation_approvals WHERE product_id='.(int)$productId);$db->exec('DELETE FROM mc_adaptation_logs WHERE product_id='.(int)$productId);$db->exec('DELETE FROM mc_adaptation_conflicts WHERE product_id='.(int)$productId);if($optionIds){$list=implode(',',array_map('intval',$optionIds));$db->exec("DELETE FROM mc_adaptation_conditions WHERE option_id IN($list)");}$db->exec('DELETE FROM mc_adaptation_options WHERE group_id IN (SELECT id FROM mc_adaptation_groups WHERE product_id='.(int)$productId.')');$db->exec('DELETE FROM mc_adaptation_groups WHERE product_id='.(int)$productId);$db->exec('DELETE FROM mc_products WHERE id='.(int)$productId);}
 if($supplierId){$smIds=$db->query('SELECT id FROM mc_supplier_materials WHERE supplier_id='.(int)$supplierId)->fetchAll(PDO::FETCH_COLUMN);if($smIds){$list=implode(',',array_map('intval',$smIds));$pids=$db->query("SELECT id FROM mc_supplier_prices WHERE supplier_material_id IN($list)")->fetchAll(PDO::FETCH_COLUMN);if($pids){$pl=implode(',',array_map('intval',$pids));$aids=$db->query("SELECT approval_id FROM mc_supplier_prices WHERE id IN($pl) AND approval_id IS NOT NULL")->fetchAll(PDO::FETCH_COLUMN);$db->exec("DELETE FROM mc_supplier_price_tiers WHERE supplier_price_id IN($pl)");$db->exec("DELETE FROM mc_supplier_price_history WHERE supplier_price_id IN($pl)");$db->exec("DELETE FROM mc_supplier_prices WHERE id IN($pl)");if($aids){$al=implode(',',array_map('intval',$aids));$db->exec("DELETE FROM mc_approval_logs WHERE approval_id IN($al)");$db->exec("DELETE FROM mc_approvals WHERE id IN($al)");}}$db->exec("DELETE FROM mc_supplier_moq WHERE supplier_material_id IN($list)");$db->exec("DELETE FROM mc_supplier_lead_times WHERE supplier_material_id IN($list)");$db->exec("DELETE FROM mc_supplier_materials WHERE id IN($list)");}$db->exec('DELETE FROM mc_supplier_contacts WHERE supplier_id='.(int)$supplierId);$db->exec('DELETE FROM mc_supplier_profiles WHERE supplier_id='.(int)$supplierId);$db->exec('DELETE FROM mc_suppliers WHERE id='.(int)$supplierId);}
 if($materialIds){$list=implode(',',array_map('intval',$materialIds));$jobIds=$db->query("SELECT DISTINCT batch_job_id FROM mc_batch_job_items WHERE entity_id IN($list)")->fetchAll(PDO::FETCH_COLUMN);$db->exec("DELETE FROM mc_batch_job_items WHERE entity_id IN($list)");if($jobIds)$db->exec('DELETE FROM mc_batch_jobs WHERE id IN('.implode(',',array_map('intval',$jobIds)).')');foreach(['mc_material_lifecycle_events','mc_material_versions','mc_activity_logs']as$table){$column=$table==='mc_activity_logs'?'entity_id':'material_id';$db->exec("DELETE FROM $table WHERE $column IN($list)");}$db->exec("DELETE FROM mc_power_supply_specs WHERE material_id IN($list)");$db->exec("DELETE FROM mc_material_metadata WHERE material_id IN($list)");$db->exec("DELETE FROM mc_materials WHERE id IN($list)");$db->exec("DELETE FROM mc_operation_logs WHERE object_type='material' AND object_id IN($list)");}
 if($supplierId)$db->exec("DELETE FROM mc_operation_logs WHERE (object_type='supplier' AND object_id=".(int)$supplierId.") OR (object_type='supplier_price' AND object_id=".(int)$priceId.")");
}
$category=(int)$db->query("SELECT id FROM mc_material_categories WHERE code='chip'")->fetchColumn();$db->beginTransaction();try{$stmt=$db->prepare("INSERT INTO mc_materials(material_uuid,material_code,category_id,name,unit,status,source,is_official,allow_bom,allow_quote,allow_customer_display,is_pilot,created_at,updated_at)VALUES(?,?,?,?,?,'draft','performance_test',0,0,0,0,0,NOW(),NOW())");for($i=0;$i<10000;$i++)$stmt->execute([sprintf('00000000-0000-4000-8000-%012d',$i),sprintf('PERF-%05d',$i),$category,'PERF '.$i,'PCS']);$start=microtime(true);$page=(new MaterialMasterService($db))->page('PERF-099','chip','draft',1,100);$elapsed=microtime(true)-$start;if($page['total']<100||$elapsed>3.0)throw new RuntimeException("10k pagination performance failed total={$page['total']} elapsed={$elapsed}");echo sprintf("10k pagination: OK %.3fs\n",$elapsed);}finally{$db->rollBack();}
