<?php require_once dirname(__DIR__).'/bootstrap.php';$pageTitle='系统与设置';$pageDescription='外观、字体、表格、动画、客户展示和权限设置。';$activeMenu='settings';include MC_ROOT.'/components/layout_top.php'; ?>
<section class="mc-page mc-settings" data-settings><div class="mc-page-header mc-page-header--compact"><div><h1>系统与设置</h1><p>调整物料中心的外观、交互、表格和权限偏好。</p></div><button class="mc-button mc-button--primary" data-save-settings>保存设置</button></div><div class="mc-settings-layout"><aside class="mc-settings-nav"><button class="is-active" data-settings-tab="appearance">外观与主题</button><button data-settings-tab="font">字体与字号</button><button data-settings-tab="color">颜色配置</button><button data-settings-tab="layout">布局与密度</button><button data-settings-tab="motion">动画与反馈</button><button data-settings-tab="table">表格偏好</button><button data-settings-tab="display">客户展示模式</button><button data-settings-tab="permission">权限与角色</button><button data-settings-tab="data">数据接入</button><button data-settings-tab="audit">日志与审计</button><button data-settings-tab="restore">恢复默认</button></aside><section class="mc-settings-content">
<div class="mc-settings-panel is-active" data-settings-panel="appearance"><h2>外观与主题</h2><p>选择系统主题并即时预览。</p><div class="mc-theme-grid"><button class="is-active" data-theme-choice="light"><span class="mc-theme-preview is-light"></span><strong>白色专业</strong><small>推荐办公主题</small></button><button data-theme-choice="soft"><span class="mc-theme-preview is-soft"></span><strong>浅灰办公</strong><small>降低长时间使用疲劳</small></button><button data-theme-choice="dark"><span class="mc-theme-preview is-dark"></span><strong>深色办公</strong><small>夜间使用</small></button><button data-theme-choice="customer"><span class="mc-theme-preview is-customer"></span><strong>客户展示</strong><small>隐藏内部字段</small></button></div></div>
<div class="mc-settings-panel" data-settings-panel="font"><h2>字体与字号</h2><p>不同区域可独立调整。</p><div class="mc-setting-list"><?php foreach([['导航字体','--nav-font-size',13,11,18],['页面标题','--title-font-size',24,20,36],['正文','--body-font-size',14,12,18],['表格表头','--table-head-font-size',12,11,17],['表格正文','--table-font-size',13,12,17],['按钮文字','--button-font-size',13,12,16],['分页文字','--pagination-font-size',12,11,16]] as $s): ?><label><span><strong><?=mc_h($s[0])?></strong><small>当前 <b data-range-output><?=$s[2]?></b>px</small></span><input type="range" min="<?=$s[3]?>" max="<?=$s[4]?>" value="<?=$s[2]?>" data-css-var="<?=mc_h($s[1])?>"></label><?php endforeach; ?></div></div>
<div class="mc-settings-panel" data-settings-panel="color"><h2>颜色配置</h2><p>通过设计令牌统一控制全站颜色。</p><div class="mc-color-grid"><?php foreach([['主操作色','--primary','#0f8f9d'],['页面背景','--page-bg','#f6f8fb'],['卡片背景','--surface','#ffffff'],['主文字','--text','#0f172a'],['边框','--border','#e2e8f0'],['选中背景','--selection','#e8f7f8'],['成功','--success','#168a5b'],['警告','--warning','#d97706'],['错误','--danger','#dc2626']] as $c): ?><label><span><?=mc_h($c[0])?></span><input type="color" value="<?=mc_h($c[2])?>" data-css-var="<?=mc_h($c[1])?>"></label><?php endforeach; ?></div></div>
<div class="mc-settings-panel" data-settings-panel="layout"><h2>布局与密度</h2><p>控制导航、页面边距和组件密度。</p><div class="mc-form-grid"><label class="mc-field"><span>页面密度</span><select data-density><option value="comfortable">舒适</option><option value="standard" selected>标准</option><option value="compact">紧凑</option></select></label><label class="mc-field"><span>页面宽度</span><select><option>全宽</option><option>最大 1600px</option><option>最大 1440px</option></select></label><label class="mc-field"><span>导航宽度</span><input type="number" value="220"></label><label class="mc-field"><span>默认抽屉宽度</span><input type="number" value="520"></label></div></div>
<div class="mc-settings-panel" data-settings-panel="motion"><h2>动画与反馈</h2><p>控制菜单、抽屉、Toast和表格反馈。</p><div class="mc-switch-list"><label><span><strong>启用动画</strong><small>淡入、滑入和状态过渡</small></span><input type="checkbox" checked data-motion-toggle></label><label><span><strong>骨架屏</strong><small>加载详情时显示占位内容</small></span><input type="checkbox" checked></label><label><span><strong>保存成功提示</strong><small>右上角显示 Toast</small></span><input type="checkbox" checked></label><label><span><strong>轻微操作提示音</strong><small>默认关闭</small></span><input type="checkbox"></label></div></div>
<div class="mc-settings-panel" data-settings-panel="table"><h2>表格偏好</h2><p>设置行高、分页、列宽和默认视图。</p><div class="mc-form-grid"><label class="mc-field"><span>默认行高</span><select><option>36px 紧凑</option><option selected>44px 标准</option><option>52px 舒适</option></select></label><label class="mc-field"><span>每页数量</span><select><option selected>自动</option><option>10</option><option>20</option><option>50</option></select></label><label class="mc-field"><span>自动适配列宽</span><select><option>当前页内容</option><option>表头</option><option>抽样内容</option></select></label><label class="mc-field"><span>网格线</span><select><option>轻量</option><option>完整</option><option>隐藏</option></select></label></div></div>
<div class="mc-settings-panel" data-settings-panel="display"><h2>客户展示模式</h2><p>开启后隐藏内部敏感字段并放大展示内容。</p><div class="mc-switch-list"><label><span><strong>隐藏采购价</strong></span><input type="checkbox" checked></label><label><span><strong>隐藏供应商</strong></span><input type="checkbox" checked></label><label><span><strong>隐藏内部备注和日志</strong></span><input type="checkbox" checked></label><label><span><strong>放大产品图片和文字</strong></span><input type="checkbox" checked></label></div></div>
<div class="mc-settings-panel" data-settings-panel="permission"><h2>权限与角色</h2><p>页面为统一账号权限接入预留。</p><table class="mc-simple-table"><thead><tr><th>角色</th><th>查看</th><th>编辑</th><th>采购价</th><th>导入导出</th><th>设置</th></tr></thead><tbody><tr><td>物料管理员</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>工程</td><td>✓</td><td>✓</td><td>—</td><td>—</td><td>—</td></tr><tr><td>采购</td><td>✓</td><td>价格</td><td>✓</td><td>✓</td><td>—</td></tr><tr><td>业务查看</td><td>✓</td><td>—</td><td>—</td><td>—</td><td>—</td></tr></tbody></table></div>
<?php foreach(['data'=>'数据接入设置','audit'=>'日志与审计','restore'=>'恢复默认'] as $key=>$label): ?><div class="mc-settings-panel" data-settings-panel="<?=mc_h($key)?>"><h2><?=mc_h($label)?></h2><p>页面已建立，等待 Codex 接入对应业务逻辑。</p><div class="mc-empty-state"><?=mc_icon('settings',28)?><strong><?=mc_h($label)?></strong><span>设置界面已准备。</span></div></div><?php endforeach; ?>
</section></div></section><?php include MC_ROOT.'/components/layout_bottom.php'; ?>
