<?php
require_once dirname(__DIR__).'/bootstrap.php';$pageTitle='产品适配';$pageDescription='维护产品允许使用的电源、芯片、光学和配件规则。';$activeMenu='adaptation';include MC_ROOT.'/components/layout_top.php';
$products=[['56.03711','NOVAL RECESSED DOWNLIGHT','嵌入式灯具'],['81.30013','DELTA PENDANT LIGHT','吊灯'],['52.03526','ULTRA-SLIM CABINET LIGHT','柜体灯'],['93.06211','MUSEUM TRACK SPOT','轨道射灯'],['66.01008','MAGNETIC LINEAR LIGHT','磁吸线性灯']];
$groups=[['芯片 / 光源','必选','Bridgelux BXRV-1816','3个选项','cpu'],['电源 / 驱动','必选','LIFUD LF-GIR020YS','5个选项','zap'],['调光方式','可选','ON-OFF','4个选项','settings'],['光学 / 透镜','可选','24° Lens','6个选项','aperture'],['附件配件','可选','无','蜂巢网、玻璃','puzzle'],['外观颜色','必选','黑色','3个选项','box'],['安装方式','必选','嵌入式','固定','plug']];
?>
<section class="mc-page mc-page--adaptation" data-adaptation><div class="mc-page-header mc-page-header--compact"><div><h1>产品适配</h1><p>按产品建立物料兼容规则、默认物料和替代关系。</p></div><button class="mc-button mc-button--primary" data-shell-action="新建适配规则"><?=mc_icon('plus',16)?> 新建</button></div><div class="mc-adaptation-tabs"><button class="is-active">适配总览</button><button>电源</button><button>芯片</button><button>光学</button><button>配件</button><button>包装</button><button>冲突与待审批</button></div>
<div class="mc-adaptation-grid"><aside class="mc-product-list"><label class="mc-search mc-search--small"><?=mc_icon('search',16)?><input type="search" placeholder="搜索型号 / 系列" data-product-search></label><div class="mc-product-list__items"><?php foreach($products as $i=>$p): ?><button class="<?=$i===0?'is-active':''?>" data-product-item data-product-code="<?=mc_h($p[0])?>" data-product-name="<?=mc_h($p[1])?>"><span class="mc-product-thumb"><?=mc_icon('box',20)?></span><span><strong><?=mc_h($p[0])?></strong><small><?=mc_h($p[1])?></small><em><?=mc_h($p[2])?></em></span></button><?php endforeach; ?></div></aside>
<section class="mc-rule-canvas"><div class="mc-rule-canvas__header"><div><strong data-active-product-code>56.03711</strong><span data-active-product-name>NOVAL RECESSED DOWNLIGHT</span></div><span class="mc-badge mc-badge--success">启用</span></div><div class="mc-rule-summary"><div><span>配置组</span><strong>7</strong></div><div><span>必选</span><strong>4</strong></div><div><span>可选</span><strong>3</strong></div><div><span>冲突</span><strong>0</strong></div></div><div class="mc-rule-groups"><?php foreach($groups as $i=>$g): ?><button class="mc-rule-group <?=$i===1?'is-active':''?>" data-rule-group data-group-name="<?=mc_h($g[0])?>"><span class="mc-rule-group__icon"><?=mc_icon($g[4],18)?></span><span><strong><?=mc_h($g[0])?></strong><small>默认：<?=mc_h($g[2])?></small></span><em class="<?=$g[1]==='必选'?'is-required':''?>"><?=mc_h($g[1])?></em><b><?=mc_h($g[3])?></b></button><?php endforeach; ?></div><button class="mc-add-rule-group" data-shell-action="添加配置组">＋ 添加配置组</button></section>
<aside class="mc-option-panel"><div class="mc-option-panel__header"><div><strong data-option-panel-title>电源 / 驱动</strong><span>配置组选项详情</span></div><button class="mc-icon-button">×</button></div><div class="mc-option-tabs"><button class="is-active">选项列表</button><button>默认设置</button><button>替代关系</button><button>适用条件</button><button>价格影响</button></div><div class="mc-option-toolbar"><input type="search" placeholder="搜索品牌 / 型号"><button class="mc-button mc-button--primary" data-shell-action="添加选项">添加选项</button></div><div class="mc-option-list"><div><span class="mc-drag">⋮⋮</span><strong>LIFUD LF-GIR020YS</strong><small>20W · 500mA · 非调光</small><em class="mc-badge mc-badge--success">默认</em><button>•••</button></div><div><span class="mc-drag">⋮⋮</span><strong>Tridonic LC-25 DALI</strong><small>25W · 500-700mA · DALI</small><em class="mc-badge mc-badge--info">可选</em><button>•••</button></div><div><span class="mc-drag">⋮⋮</span><strong>Eaglerise EIP020</strong><small>20W · 500mA · 0-10V</small><em class="mc-badge mc-badge--neutral">替代</em><button>•••</button></div></div><div class="mc-option-footer"><button class="mc-button">取消</button><button class="mc-button mc-button--primary" data-shell-action="保存配置">保存配置</button></div></aside></div></section>
<?php include MC_ROOT.'/components/layout_bottom.php'; ?>
