<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/bootstrap.php';
use Artdon\MaterialCenter\Services\AdaptationService;
use Artdon\MaterialCenter\Services\MaterialMasterService;
$pageTitle='产品适配';$pageDescription='维护产品允许使用的电源、芯片、光学和配件规则。';$activeMenu='adaptation';
$service=new AdaptationService();$products=$service->products(trim((string)($_GET['q']??'')));$selected=(int)($_GET['product_id']??($products[0]['id']??0));
$groups=$selected?$service->groups($selected):[];$activeGroup=(int)($_GET['group_id']??($groups[0]['id']??0));$options=$activeGroup?$service->options($activeGroup):[];
$conflicts=$selected?$service->conflicts($selected):[];$allMaterials=(new MaterialMasterService())->rows();$allOptions=[];foreach($groups as$group)$allOptions=array_merge($allOptions,$service->options((int)$group['id']));
$activeProduct=null;foreach($products as$product)if((int)$product['id']===$selected)$activeProduct=$product;
include MC_ROOT.'/components/layout_top.php';
?>
<section class="mc-page mc-page--adaptation" data-adaptation>
 <div class="mc-page-header mc-page-header--compact"><div><h1>产品适配</h1><p>产品只读来自命名系统；规则、审批和日志只写 mc_ 表。</p></div><div><?php if($selected):?><button class="mc-button" data-open-modal="group-modal">新建配置组</button><?php if($groups&&$allMaterials):?><button class="mc-button" data-open-modal="option-modal">添加物料选项</button><?php endif;?><?php if(count($allOptions)>1):?><button class="mc-button" data-open-modal="conflict-modal">设置冲突</button><?php endif;?><?php endif;?> <form data-adaptation-action style="display:inline"><input type="hidden" name="csrf_token" value="<?=mc_h(csrf_token())?>"><input type="hidden" name="action" value="sync"><button class="mc-button mc-button--primary">同步产品</button></form></div></div>
 <div class="mc-adaptation-tabs"><button class="is-active">适配总览</button><button>电源</button><button>芯片</button><button>光学</button><button>配件</button><button>包装</button><button>冲突与待审批</button></div>
 <div class="mc-adaptation-grid">
  <aside class="mc-product-list"><form><label class="mc-search mc-search--small"><?=mc_icon('search',16)?><input name="q" value="<?=mc_h($_GET['q']??'')?>" placeholder="搜索型号 / 名称"></label></form><div class="mc-product-list__items"><?php if(!$products):?><div class="mc-empty-state"><strong>尚未同步产品</strong></div><?php endif;?><?php foreach($products as$product):?><a class="<?=$selected===$product['id']?'is-active':''?>" href="?product_id=<?=intval($product['id'])?>"><span class="mc-product-thumb"><?=mc_icon('box',20)?></span><span><strong><?=mc_h($product['product_code']??'—')?></strong><small><?=mc_h($product['product_name']??'—')?></small><em><?=intval($product['group_count'])?> 组 · <?=intval($product['conflict_count'])?> 冲突</em></span></a><?php endforeach;?></div></aside>
  <section class="mc-rule-canvas"><div class="mc-rule-canvas__header"><div><strong><?=mc_h($activeProduct['product_code']??'请选择产品')?></strong><span>配置规则</span></div></div><div class="mc-rule-groups"><?php if(!$groups):?><div class="mc-empty-state"><strong>暂无配置组</strong><span>点击“新建配置组”建立真实规则。</span></div><?php endif;?><?php foreach($groups as$group):?><a class="mc-rule-group <?=$activeGroup===$group['id']?'is-active':''?>" href="?product_id=<?=$selected?>&group_id=<?=intval($group['id'])?>"><span class="mc-rule-group__icon"><?=mc_icon('settings',18)?></span><span><strong><?=mc_h($group['group_name'])?></strong><small>默认：<?=mc_h($group['default_material']??'未设置')?></small></span><em><?=mc_h($group['status'])?></em><b><?=intval($group['option_count'])?> 个选项</b></a><?php endforeach;?></div></section>
  <aside class="mc-option-panel"><div class="mc-option-panel__header"><div><strong>选项列表</strong><span>真实批准状态、价格和交期影响</span></div></div><div class="mc-option-list"><?php if(!$options):?><div class="mc-empty-state"><strong>暂无选项</strong></div><?php endif;?><?php foreach($options as$option):?><div><strong><?=mc_h($option['material_code'].' '.$option['name'])?></strong><small><?=mc_h(($option['brand']??'').' '.($option['model']??''))?> · 价格 <?=mc_h($option['price_impact']??'0')?> · 交期 <?=mc_h($option['lead_time_impact_days']??'0')?> 天</small><em class="mc-badge"><?=$option['is_default']?'默认':mc_h($option['option_type'])?></em></div><?php endforeach;?></div></aside>
 </div>
 <?php if($conflicts):?><section class="mc-panel"><div class="mc-panel__header"><div><strong>冲突原因</strong><span>计算适配结果时作为阻断或警告返回</span></div></div><table class="mc-simple-table"><thead><tr><th>选项 A</th><th>选项 B</th><th>级别</th><th>原因</th></tr></thead><tbody><?php foreach($conflicts as$conflict):?><tr><td><?=mc_h($conflict['left_material'])?></td><td><?=mc_h($conflict['right_material'])?></td><td><?=mc_h($conflict['severity'])?></td><td><?=mc_h($conflict['reason'])?></td></tr><?php endforeach;?></tbody></table></section><?php endif;?>
 <?php if($selected&&$groups):?><form class="mc-panel" data-adaptation-evaluate><div class="mc-panel__header"><div><strong>适配计算</strong><span>选择选项，返回兼容结论、冲突原因、价格和交期影响</span></div></div><input type="hidden" name="csrf_token" value="<?=mc_h(csrf_token())?>"><input type="hidden" name="action" value="evaluate"><input type="hidden" name="product_id" value="<?=$selected?>"><div class="mc-switch-list"><?php foreach($allOptions as$option):?><label><span><strong><?=mc_h($option['material_code'].' '.$option['name'])?></strong></span><input type="checkbox" name="option_choice" value="<?=intval($option['id'])?>"></label><?php endforeach;?></div><button class="mc-button mc-button--primary">计算适配</button><output data-adaptation-result></output></form><?php endif;?>
 <?php if($selected&&$groups):?><form data-adaptation-action><input type="hidden" name="csrf_token" value="<?=mc_h(csrf_token())?>"><input type="hidden" name="action" value="approve"><input type="hidden" name="product_id" value="<?=$selected?>"><button class="mc-button mc-button--primary">批准当前产品适配版本</button></form><?php endif;?>
</section>
<div class="mc-modal" id="group-modal" data-modal><form class="mc-modal__panel" data-adaptation-action><div class="mc-modal__header"><div><strong>新建配置组</strong></div><button type="button" class="mc-icon-button" data-close-layer>×</button></div><div class="mc-modal__body"><input type="hidden" name="csrf_token" value="<?=mc_h(csrf_token())?>"><input type="hidden" name="action" value="save_group"><input type="hidden" name="product_id" value="<?=$selected?>"><div class="mc-form-grid"><label class="mc-field"><span>组代码 *</span><input name="group_code" required pattern="[a-z0-9_]+"></label><label class="mc-field"><span>组名称 *</span><input name="group_name" required></label><label class="mc-field"><span>类型 *</span><select name="group_type"><option value="power">电源</option><option value="chip">芯片</option><option value="optical">光学</option><option value="accessory">配件</option><option value="packaging">包装</option></select></label></div></div><div class="mc-modal__footer"><button class="mc-button mc-button--primary">保存</button></div></form></div>
<div class="mc-modal" id="option-modal" data-modal><form class="mc-modal__panel" data-adaptation-action><div class="mc-modal__header"><div><strong>添加物料选项</strong></div><button type="button" class="mc-icon-button" data-close-layer>×</button></div><div class="mc-modal__body"><input type="hidden" name="csrf_token" value="<?=mc_h(csrf_token())?>"><input type="hidden" name="action" value="save_option"><div class="mc-form-grid"><label class="mc-field"><span>配置组 *</span><select name="group_id"><?php foreach($groups as$group):?><option value="<?=intval($group['id'])?>" <?=$activeGroup===$group['id']?'selected':''?>><?=mc_h($group['group_name'])?></option><?php endforeach;?></select></label><label class="mc-field"><span>物料 *</span><select name="material_id"><?php foreach($allMaterials as$material):?><option value="<?=intval($material['id'])?>"><?=mc_h($material['material_code'].' '.$material['name'])?></option><?php endforeach;?></select></label><label class="mc-field"><span>选项类型</span><select name="option_type"><option value="optional">可选</option><option value="required">必选</option><option value="alternative">替代</option><option value="conditional">条件</option></select></label><label class="mc-field"><span>价格影响</span><input type="number" step="0.0001" name="price_impact"></label><label class="mc-field"><span>交期影响（天）</span><input type="number" name="lead_time_impact_days"></label><label class="mc-field"><span>默认</span><input type="checkbox" name="is_default" value="1"></label></div></div><div class="mc-modal__footer"><button class="mc-button mc-button--primary">保存</button></div></form></div>
<div class="mc-modal" id="conflict-modal" data-modal><form class="mc-modal__panel" data-adaptation-action><div class="mc-modal__header"><div><strong>设置选项冲突</strong></div><button type="button" class="mc-icon-button" data-close-layer>×</button></div><div class="mc-modal__body"><input type="hidden" name="csrf_token" value="<?=mc_h(csrf_token())?>"><input type="hidden" name="action" value="save_conflict"><input type="hidden" name="product_id" value="<?=$selected?>"><div class="mc-form-grid"><label class="mc-field"><span>选项 A</span><select name="left_option_id"><?php foreach($allOptions as$option):?><option value="<?=intval($option['id'])?>"><?=mc_h($option['material_code'].' '.$option['name'])?></option><?php endforeach;?></select></label><label class="mc-field"><span>选项 B</span><select name="right_option_id"><?php foreach(array_reverse($allOptions) as$option):?><option value="<?=intval($option['id'])?>"><?=mc_h($option['material_code'].' '.$option['name'])?></option><?php endforeach;?></select></label><label class="mc-field"><span>级别</span><select name="severity"><option value="block">阻断</option><option value="warn">警告</option></select></label><label class="mc-field"><span>冲突原因 *</span><input name="reason" required maxlength="500"></label></div></div><div class="mc-modal__footer"><button class="mc-button mc-button--primary">保存冲突</button></div></form></div>
<script src="<?=mc_h(mc_url('assets/js/adaptation-shell.js'))?>" defer></script>
<?php include MC_ROOT.'/components/layout_bottom.php';?>
