<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/bootstrap.php';
use Artdon\MaterialCenter\Services\SupplierService;
$pageTitle='供应商与价格';$pageDescription='管理供应商、供应商物料、采购价、MOQ和交期。';$activeMenu='supplier';
$service=new SupplierService();$suppliers=$service->suppliers();$selected=(int)($_GET['supplier_id']??($suppliers[0]['id']??0));$materials=$selected?$service->materials($selected):[];
include MC_ROOT.'/components/layout_top.php';?>
<section class="mc-page"><div class="mc-page-header mc-page-header--compact"><div><h1>供应商与价格</h1><p>真实供应商资料、供应商物料、最新价、历史价、MOQ 和交期。</p></div><button class="mc-button mc-button--primary" data-open-modal="supplier-modal"><?=mc_icon('plus',16)?> 新建供应商</button></div><div class="mc-tabs"><button class="is-active">供应商资料</button><button>供应商物料</button><button>采购价管理</button><button>价格历史</button><button>MOQ / 交期</button></div><div class="mc-supplier-layout"><aside class="mc-panel mc-supplier-list"><div class="mc-panel__header"><div><strong>供应商</strong><span>共 <?=count($suppliers)?> 家</span></div></div><?php if(!$suppliers):?><div class="mc-empty-state"><strong>暂无供应商</strong><span>新建后会显示真实资料。</span></div><?php endif;foreach($suppliers as$supplier):?><a class="<?=$selected===$supplier['id']?'is-active':''?>" href="?supplier_id=<?=intval($supplier['id'])?>"><span class="mc-supplier-logo"><?=mc_h(mb_substr($supplier['name'],0,1,'UTF-8'))?></span><span><strong><?=mc_h($supplier['name'])?></strong><small><?=intval($supplier['material_count'])?> 条物料</small></span></a><?php endforeach;?></aside><section class="mc-panel mc-supplier-detail"><?php $current=null;foreach($suppliers as$s)if((int)$s['id']===$selected)$current=$s;if(!$current):?><div class="mc-empty-state"><strong>请选择供应商</strong></div><?php else:?><div class="mc-panel__header"><div><strong><?=mc_h($current['name'])?></strong><span><?=mc_h($current['supplier_code'])?> · <?=mc_h($current['status'])?></span></div></div><div class="mc-detail-grid"><div><span>联系人</span><strong><?=mc_h($current['contact_name']??'—')?></strong></div><div><span>电话</span><strong><?=mc_h($current['contact_phone']??'—')?></strong></div><div><span>付款条件</span><strong><?=mc_h($current['payment_terms']??'—')?></strong></div><div><span>默认币种</span><strong><?=mc_h($current['default_currency']??'CNY')?></strong></div><div><span>质量等级</span><strong><?=mc_h($current['quality_grade']??'—')?></strong></div></div><div class="mc-subtable-header"><strong>供应商物料与最新价格</strong></div><table class="mc-simple-table"><thead><tr><th>物料</th><th>供应商型号</th><th>采购价</th><th>MOQ</th><th>交期</th><th>有效期</th></tr></thead><tbody><?php if(!$materials):?><tr><td colspan="6">暂无供应商物料或价格</td></tr><?php endif;foreach($materials as$item):?><tr><td><?=mc_h($item['material_code'].' '.$item['material_name'])?></td><td><?=mc_h($item['supplier_model']??'—')?></td><td><?=isset($item['purchase_price'])?mc_h($item['currency'].' '.$item['purchase_price']):'—'?></td><td><?=mc_h($item['current_moq']??$item['moq']??'—')?></td><td><?=mc_h(isset($item['current_lead_time'])?$item['current_lead_time'].'天':'—')?></td><td><?=mc_h(($item['valid_from']??'—').' / '.($item['valid_to']??'—'))?></td></tr><?php endforeach;?></tbody></table><?php endif;?></section></div></section>
<div class="mc-modal" id="supplier-modal" data-modal><form class="mc-modal__panel" data-supplier-form><div class="mc-modal__header"><div><strong>新建供应商</strong><span>保存到物料中心供应商主数据</span></div><button type="button" class="mc-icon-button" data-close-layer>×</button></div><div class="mc-modal__body"><input type="hidden" name="csrf_token" value="<?=mc_h(csrf_token())?>"><input type="hidden" name="action" value="save_supplier"><div class="mc-form-grid"><label class="mc-field"><span>供应商名称 *</span><input name="name" required></label><label class="mc-field"><span>供应商代码</span><input name="supplier_code"></label><label class="mc-field"><span>默认币种</span><input name="default_currency" value="CNY" required maxlength="3"></label><label class="mc-field"><span>付款条件</span><input name="payment_terms"></label><label class="mc-field"><span>质量等级</span><input name="quality_grade"></label><label class="mc-field"><span>联系人</span><input name="contact_name"></label><label class="mc-field"><span>电话</span><input name="contact_phone"></label><label class="mc-field"><span>邮箱</span><input type="email" name="contact_email"></label></div></div><div class="mc-modal__footer"><button type="button" class="mc-button" data-close-layer>取消</button><button class="mc-button mc-button--primary">保存</button></div></form></div>
<script src="<?=mc_h(mc_url('assets/js/suppliers.js'))?>" defer></script><?php include MC_ROOT.'/components/layout_bottom.php';?>
