<?php
$psPage=max(1,(int)($_GET['p']??1)); $psSize=20;
$psCatalog=(new Artdon\CommercialCenter\Services\CatalogCenterService())->products($view['auth'],trim((string)($_GET['q']??'')),trim((string)($_GET['category']??'')),$psPage,$psSize);
$psRows=$psCatalog['rows']; $psTotal=(int)$psCatalog['total']; $psPages=(int)$psCatalog['pages']; $psPage=(int)$psCatalog['page'];
$psPriced=count(array_filter($psRows,fn($r)=>(float)($r['bom_cost']??0)>0));
?>
<section class="price-strategy-page" data-price-strategy>
  <header class="ps-heading"><div><span class="eyebrow">PRODUCT PRICING STRATEGY</span><h1>价格策略中心</h1><p>配置产品销售价格、阶梯价格与客户等级价格。</p></div></header>
  <section class="ps-kpis">
    <article><i>▧</i><span>产品总数</span><strong><?= $psTotal ?></strong></article>
    <article><i>▣</i><span>已有价格</span><strong><?= $psPriced ?></strong><small>当前页</small></article>
    <article><i>◇</i><span>缺价格</span><strong><?= max(0,count($psRows)-$psPriced) ?></strong><small>当前页</small></article>
    <article><i>♙</i><span>启用策略</span><strong><?= $psPriced ?></strong><small>当前页</small></article>
    <article><i>⌁</i><span>待审批</span><strong>0</strong><small>草稿</small></article>
  </section>
  <form class="ps-toolbar" method="get"><input type="hidden" name="page" value="price_strategy"><label><input name="q" value="<?= cc_h((string)($_GET['q']??'')) ?>" placeholder="搜索型号 / 系列 / 类别"><b>⌕</b></label><select name="category"><option value="">全部分类</option><?php foreach($psCatalog['categories'] as $c):?><option value="<?=cc_h($c['category'])?>" <?=(string)($_GET['category']??'')===(string)$c['category']?'selected':''?>><?=cc_h($c['category'])?></option><?php endforeach;?></select><select><option>全部状态</option><option>启用</option><option>停用</option></select><select><option>全部币种</option><option>USD</option><option>RMB</option></select><select><option>全部模式</option><option>固定价格</option><option>阶梯价格</option></select><span></span><button type="button" data-ps-batch>批量保存</button><button type="button" class="ghost">导入/导出⌄</button></form>
  <div class="ps-table-wrap"><table class="ps-table"><thead><tr><th><input type="checkbox"></th><th>图片</th><th>型号</th><th>系列</th><th>类别</th><th>状态</th><th>币种</th><th>价格模式</th><th>MOQ</th><th>标准价</th><th>阶梯价格</th><th>客户等级价</th><th>启用</th><th>更新时间</th><th>操作</th></tr></thead><tbody>
  <?php foreach($psRows as $r): $cost=(float)($r['bom_cost']??0); $price=$cost>0?round($cost*1.35,2):0; $image=cc_legacy_asset_url($r['image_path']); $payload=['model'=>$r['model_no'],'name'=>$r['product_name'],'series'=>$r['series_name'],'category'=>$r['category'],'image'=>$image,'price'=>$price,'status'=>$r['status'],'updated'=>$r['updated_at']]; ?>
    <tr data-ps-row data-product="<?=cc_h(json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?>"><td><input type="checkbox"></td><td><div class="ps-thumb"><?php if($image):?><img src="<?=cc_h($image)?>" alt=""><?php endif;?></div></td><td><b><?=cc_h($r['model_no'])?></b><small><?=cc_h($r['id'])?></small></td><td><?=cc_h($r['series_name'])?></td><td><?=cc_h($r['category'])?><small><?=cc_h($r['lamp_type'])?></small></td><td><em>启用</em></td><td>USD</td><td><mark><?=$price>0?'阶梯价格':'固定价格'?></mark></td><td>1</td><td><b>USD <?=number_format($price,2)?></b></td><td><?=$price>0?'1–49：'.number_format($price,2).'<br>50–199：'.number_format($price*.92,2).'<br>200+：'.number_format($price*.85,2):'—'?></td><td><?=$price>0?'A级：'.number_format($price*.94,2).'<br>VIP：'.number_format($price*.88,2):'—'?></td><td><button class="ps-switch on" type="button" aria-label="启用"></button></td><td><?=cc_h(substr((string)$r['updated_at'],0,16))?></td><td><button class="ps-edit" type="button">编辑<br>更多 ⋮</button></td></tr>
  <?php endforeach;?></tbody></table></div>
  <footer class="ps-footer"><b>共 <?= $psTotal ?> 条</b><nav><a href="?page=price_strategy&p=<?=max(1,$psPage-1)?>">‹ 上一页</a><strong><?=$psPage?></strong><span>/ <?=$psPages?></span><a href="?page=price_strategy&p=<?=min($psPages,$psPage+1)?>">下一页 ›</a></nav><span>20 条/页⌄</span></footer>
</section>
<aside class="ps-drawer" data-ps-drawer><header><h2>价格策略编辑</h2><button type="button" data-ps-close>×</button></header><div class="ps-product"><div class="ps-drawer-img"></div><div><h3 data-ps-model>—</h3><b data-ps-name>—</b><em>启用</em><p>系列：<span data-ps-series>—</span></p><p>类别：<span data-ps-category>—</span></p><p>币种：USD</p></div></div><section><h3>基础设置</h3><div class="ps-fields"><label>币种*<select><option>USD</option><option>RMB</option></select></label><label>价格模式*<select><option>阶梯价格</option><option>固定价格</option></select></label><label>MOQ*<input type="number" value="1"></label></div></section><section><h3>标准价格</h3><label>标准价*<div class="ps-money"><input data-ps-price type="number" step=".01"><span>USD</span></div></label></section><section><h3>阶梯价格</h3><div data-ps-tiers></div><button class="ps-add" type="button" data-add-tier>＋ 添加阶梯</button></section><section><h3>客户等级价格</h3><div class="ps-level"><input value="A级客户"><input data-level-a type="number" step=".01"><button>♙</button></div><div class="ps-level"><input value="VIP客户"><input data-level-vip type="number" step=".01"><button>♙</button></div><button class="ps-add" type="button">＋ 添加客户等级</button></section><section><h3>备注说明</h3><textarea maxlength="200" placeholder="请输入备注说明（选填）"></textarea></section><footer><button type="button" data-ps-close>取消</button><button type="button" class="outline" data-ps-save>保存策略</button><button type="button" class="primary" data-ps-submit>提交审批</button></footer></aside><div class="ps-mask" data-ps-close></div><div class="ps-toast" data-ps-toast>价格策略已保存</div>
