<?php
$pageNo=max(1,(int)($_GET['p']??1)); $pageSize=in_array((int)($_GET['size']??12),[6,12,24],true)?(int)$_GET['size']:12;
$catalog=(new Artdon\CommercialCenter\Services\CatalogCenterService())->products($view['auth'],(string)($_GET['q']??''),(string)($_GET['category']??''));
$rows=$catalog['rows']; $total=count($rows); $pages=max(1,(int)ceil($total/$pageSize)); $pageNo=min($pageNo,$pages); $shown=array_slice($rows,($pageNo-1)*$pageSize,$pageSize);
?>
<section class="product-library-container">
  <header class="page-header"><div><span class="eyebrow">COMMERCIAL PRODUCT LIBRARY</span><h1>报价产品库</h1><p>命名中心产品只读引用，作为后续报价的统一产品入口。</p></div><div class="page-meta"><span>来源</span><b>命名中心只读</b></div></header>
  <div class="product-summary-bar"><span>产品总数 <b><?= $total ?></b></span><span>可报价 <b><?= count(array_filter($rows,fn($r)=>(string)($r['status']??'')==='可报价')) ?></b></span><span>开发中 <b><?= count(array_filter($rows,fn($r)=>(string)($r['status']??'')==='开发中')) ?></b></span><span>停售 <b><?= count(array_filter($rows,fn($r)=>(string)($r['status']??'')==='停售')) ?></b></span></div>
  <form class="product-toolbar" method="get"><input type="hidden" name="page" value="commercial_product_library"><input type="search" name="q" value="<?= cc_h((string)($_GET['q']??'')) ?>" placeholder="型号 / 系列 / 类别 / 功率 / 参数"><select name="category"><option value="">分类</option><?php foreach($catalog['categories'] as $c): ?><option value="<?= cc_h($c['category']) ?>"><?= cc_h($c['category']) ?></option><?php endforeach; ?></select><select name="status"><option value="">状态</option><option>可报价</option><option>开发中</option><option>停售</option></select><select name="power"><option value="">功率</option></select><a href="?page=commercial_product_library&mode=list">列表</a></form>
  <?php if($catalog['status']!=='available'): ?><section class="login-notice"><strong>当前账号无法读取产品库</strong></section><?php else: ?><section class="product-grid product-library-grid"><?php foreach($shown as $row): ?><article class="library-card" data-product-detail data-model="<?= cc_h($row['model_no']) ?>"><div class="library-thumb"><?php $image=cc_legacy_asset_url($row['image_path']); if($image): ?><img src="<?= cc_h($image) ?>" alt="" loading="lazy"><?php else: ?><span>NO IMAGE</span><?php endif; ?></div><div><h3><?= cc_h($row['model_no']) ?></h3><small><?= cc_h($row['series_name']) ?> · <?= cc_h($row['category']) ?></small><footer><span>状态：<?= cc_h($row['status']) ?></span><button type="button" class="text-button">查看详情</button></footer></div></article><?php endforeach; ?></section><?php endif; ?>
  <footer class="pagination-footer"><a href="?page=commercial_product_library&p=<?= max(1,$pageNo-1) ?>">上一页</a><span>第 <?= $pageNo ?> / <?= $pages ?> 页</span><a href="?page=commercial_product_library&p=<?= min($pages,$pageNo+1) ?>">下一页</a></footer>
</section>
