<?php
$pageNo=max(1,(int)($_GET['p']??1)); $requestedSize=(int)($_GET['size']??26); $pageSize=in_array($requestedSize,[13,26,52],true)?$requestedSize:26; $pageSize=max(1,$pageSize); $viewMode=(($_GET['mode']??'cards')==='list')?'list':'cards';
$catalog=(new Artdon\CommercialCenter\Services\CatalogCenterService())->products($view['auth'],(string)($_GET['q']??''),(string)($_GET['category']??''),$pageNo,$pageSize);
$shown=$catalog['rows']; $total=(int)$catalog['total']; $pages=(int)$catalog['pages']; $pageNo=(int)$catalog['page']; $statusCounts=$catalog['status_counts'];
?>
<section class="product-library-container">
  <header class="page-header"><div><span class="eyebrow">COMMERCIAL PRODUCT LIBRARY</span><h1>报价产品库</h1><p>命名中心产品只读引用，作为后续报价的统一产品入口。</p></div><div class="page-meta"><span>来源</span><b>命名中心只读</b></div></header>
  <?php $pageQuery='page=commercial_product_library&mode='.$viewMode.'&q='.rawurlencode((string)($_GET['q']??'')).'&category='.rawurlencode((string)($_GET['category']??'')).'&size='.$pageSize; ?><div class="product-control-bar">
    <div class="product-summary-bar"><span>产品总数 <b><?= $total ?></b></span><span>可报价 <b><?= (int)$statusCounts['可报价'] ?></b></span><span>开发中 <b><?= (int)$statusCounts['开发中'] ?></b></span><span>停售 <b><?= (int)$statusCounts['停售'] ?></b></span></div>
    <form class="product-toolbar" method="get"><input type="hidden" name="page" value="commercial_product_library"><input type="hidden" name="mode" value="<?= $viewMode ?>"><input type="search" name="q" value="<?= cc_h((string)($_GET['q']??'')) ?>" placeholder="型号 / 系列 / 类别 / 功率 / 参数"><select name="category"><option value="">分类</option><?php foreach($catalog['categories'] as $c): ?><option value="<?= cc_h($c['category']) ?>"><?= cc_h($c['category']) ?></option><?php endforeach; ?></select><select name="status"><option value="">状态</option><option>可报价</option><option>开发中</option><option>停售</option></select><select name="power"><option value="">功率</option></select><select name="size"><option value="13" <?= $pageSize===13?'selected':'' ?>>13/页</option><option value="26" <?= $pageSize===26?'selected':'' ?>>26/页</option><option value="52" <?= $pageSize===52?'selected':'' ?>>52/页</option></select><a href="?page=commercial_product_library&mode=<?= $viewMode==='list'?'cards':'list' ?>&size=<?= $pageSize ?>"><?= $viewMode==='list'?'卡片':'列表' ?></a></form>
    <footer class="pagination-footer"><a href="?<?= $pageQuery ?>&p=<?= max(1,$pageNo-1) ?>">上一页</a><span><?= $pageNo ?> / <?= $pages ?></span><a href="?<?= $pageQuery ?>&p=<?= min($pages,$pageNo+1) ?>">下一页</a></footer>
  </div>
  <?php if($catalog['status']!=='available'): ?><section class="login-notice"><strong>当前账号无法读取产品库</strong></section><?php else: ?><section class="product-grid product-library-grid <?= $viewMode==='list'?'is-list':'' ?>"><?php foreach($shown as $row): $cost=$row['bom_cost']??null; ?><article class="library-card" data-product-detail data-model="<?= cc_h($row['model_no']) ?>"><div class="library-thumb"><?php $image=cc_legacy_asset_url($row['image_path']); if($image): ?><img src="<?= cc_h($image) ?>" alt="" loading="lazy"><?php else: ?><span>NO IMAGE</span><?php endif; ?></div><div><h3><?= cc_h($row['model_no']) ?></h3><small><?= cc_h($row['series_name']) ?> · <?= cc_h($row['category']) ?></small><p class="product-size">尺寸：<?= cc_h($row['dim_outer_d']?:'—') ?> × <?= cc_h($row['dim_height']?:'—') ?></p><strong class="product-price">参考报价：USD <?= $cost===null?'—':number_format((float)$cost,2) ?></strong><footer><span>状态：<?= cc_h($row['status']) ?></span><button type="button" class="text-button">查看详情</button></footer></div></article><?php endforeach; ?></section><?php endif; ?>
</section>
<aside class="detail-drawer" data-detail-drawer aria-hidden="true"><div><span class="eyebrow">PRODUCT DETAIL</span><h2>产品详情</h2></div><button type="button" data-detail-close aria-label="关闭">×</button><div data-detail-content></div></aside><div class="drawer-mask" data-detail-close></div>
