<?php declare(strict_types=1); $rows=array_slice($catalogRows,0,8); $stdQty=[10,20,15,30,12,40,8,6]; $stdPrice=[680,98,128,66,188,58,168,980]; ?>
<section class="ref-quote ref-standard" data-quote-editor data-quote-type="standard">
  <header class="ref-titlebar standard-title"><div><a href="?page=quote_center">＋ 新建报价单</a><h1>标准品报价单（半自由）</h1><span class="quote-state"><?= $quickMode?'快速创建':'草稿' ?></span></div><nav><button data-draft-save>保存草稿</button><button>预览</button><button>打印</button><button>导出PDF</button><button>导出Excel</button><button>提交审核</button><button class="primary">发送报价</button></nav></header>
  <?php if($quickMode):?><div class="quick-strip">快速创建模式：保存后可补充完整客户与条款信息</div><?php endif;?>
  <div class="ref-body standard-body">
    <main>
      <section class="ref-panel"><h2>报价单信息</h2><div class="standard-form"><?php foreach(['报价单号'=>'QT-20250516-001','客户 *'=>'示例照明公司','联系人'=>'李明','国家/地区 *'=>'中国','币种 *'=>'CNY 人民币','有效期 *'=>'30 天','负责人 *'=>'邱磊','付款方式 *'=>'30% 预付款，70% 发货前','贸易条款 *'=>'FOB 深圳','报价日期'=>'2025-05-16','交期基准'=>'确认订单后','价格模板'=>'标准出口价格'] as $label=>$value):?><label><span><?=$label?></span><input value="<?=$value?>"></label><?php endforeach;?></div></section>
      <section class="ref-panel standard-lines"><div class="panel-title"><h2>报价明细</h2><nav><button data-open-product>＋ 添加产品</button><button>＋ 添加配件</button><button>批量操作⌄</button></nav></div><div class="ref-table-scroll"><table><thead><tr><th>#</th><th>图片</th><th>型号</th><th>产品名称</th><th>配置摘要</th><th>数量</th><th>单价</th><th>折扣</th><th>小计</th><th>交期</th><th>备注</th><th>操作</th></tr></thead><tbody data-quote-lines><?php foreach($rows as $i=>$row):$img=cc_legacy_asset_url($row['image_path']??'');?><tr><td><?=$i+1?></td><td><div class="ref-thumb"><?php if($img):?><img src="<?=cc_h($img)?>" alt=""><?php else:?>图<?php endif;?></div></td><td><b><?=cc_h($row['model_no'])?></b></td><td><?=cc_h(preg_replace('/ · BOM成本.*$/u','',(string)$row['product_name']))?></td><td><span><?=['COB 15W 3000K','SMD 9W 4000K','COB 12W 3000K','SMD 3W 4000K','COB 18W 3000K','SMD 3W 3000K','COB 16W 4000K','COB 25W 3000K'][$i]?></span><small>DALI-2 · <?=$i%2?'36°':'24°'?> · <?=$i%3?'白色':'黑色'?></small></td><td><input type="number" value="<?=$stdQty[$i]?>" data-qty></td><td><input type="number" value="<?=$stdPrice[$i]?>" data-price></td><td><input type="number" value="<?=$i%2?5:0?>" data-discount></td><td data-line-total>0.00</td><td>15 天</td><td><?=$i===0?'餐厅项目':'—'?></td><td><button data-configure>编辑</button><button class="text-danger" data-remove-line>删除</button></td></tr><?php endforeach;?></tbody></table></div><footer><button data-add-line>＋ 添加产品</button><span>共 <?=count($rows)?> 项</span></footer></section>
    </main>
    <aside><section class="ref-panel total-box"><h2>报价汇总</h2><dl><dt>产品金额（未税）</dt><dd data-subtotal>0.00</dd><dt>折扣金额</dt><dd><input value="0" data-order-discount></dd><dt>运费</dt><dd><input value="800" data-shipping></dd><dt>税费（13%）</dt><dd><input value="0" data-tax></dd></dl><div><b>总金额（含税）</b><strong data-grand-total>0.00</strong></div><p>预计毛利　<b>按权限计算</b></p><p>毛利率　<b>按权限显示</b></p></section><section class="ref-panel risk-cards"><article>△<b>MOQ 提醒</b><span>部分产品存在最小起订量要求</span></article><article>▣<b>交期提醒</b><span>请与客户确认长交期产品</span></article><article>◇<b>佣金提醒</b><span>预计佣金金额待规则计算</span></article></section><section class="ref-panel note-box"><h2>备注信息</h2><textarea placeholder="请输入备注（对客户或内部备注）"></textarea></section></aside>
  </div>
  <div class="standard-workflow"><b>内部流程</b><?php foreach(['草稿'=>'当前状态','内部核价'=>'待核价','待审核'=>'待提交','已发送'=>'尚未发送','转项目/转订单'=>'未执行'] as $step=>$state):?><span><strong><?=$step?></strong><small><?=$state?></small></span><i>›</i><?php endforeach;?></div>
  <div class="quote-config-modal open ref-config" data-config-modal aria-hidden="false"><div><header><div><b>添加产品 / 选择标准产品与配置</b><span>按产品适配规则选择合法配置</span></div><button data-modal-close>×</button></header><div class="config-steps"><b>1 选择产品</b><span>2 选择配置</span><span>3 加入报价</span></div><div class="config-picked"><div class="ref-thumb">图</div><b><?=cc_h($rows[0]['model_no']??'52.04526')?></b><span><?=cc_h(preg_replace('/ · BOM成本.*$/u','',(string)($rows[0]['product_name']??'SHOWLITE 嵌入射灯')))?></span></div><div class="config-options"><?php foreach(['芯片/光源'=>['COB 18W 3000K','COB 18W 4000K','SMD 15W 3000K'],'电源/驱动'=>['不调光','可控硅调光','DALI-2','0/1-10V'],'调光方式'=>['不调光','可控硅调光','DALI-2','0/1-10V','调光+应急'],'光学/角度'=>['24°','36°','60°'],'附件/配件'=>['无','蜂窝防眩格栅','拉伸片','遮光罩'],'外观颜色'=>['白色','黑色','银色'],'安装方式'=>['嵌入式','表面式','吊装式']] as $label=>$opts):?><label><b><?=$label?></b><?php foreach($opts as $n=>$opt):?><span class="<?=$n===0?'selected':''?>"><?=$opt?></span><?php endforeach;?></label><?php endforeach;?></div><footer><span>预计单价（含税） <b>¥188.00</b></span><button data-modal-close>取消</button><button class="primary" data-apply-config>加入报价</button></footer></div></div>
</section>
