<?php declare(strict_types=1); $rows=array_slice($catalogRows,0,5); $customNames=['定制轨道射灯（深防眩）','定制线性洗墙灯','定制嵌入式筒灯（无边）','定制壁洗灯（非标长度）','定制智能电源（DALI）']; $customSpecs=['18W / 3000K / Ra≥90 / 15° / 黑色 / 深防眩杯','24W/m / 3000K / Ra≥90 / DC24V / IP65 / 铝材黑色','12W / 4000K / Ra≥90 / 38° / 白色 / 无边框','36W / 3000K / Ra≥90 / L=1200mm / IP65','100W / DALI-2 / 24V / PF≥0.95 / 防雷']; $customQty=[120,80,200,40,40]; $customTarget=[238,168,78,328,158]; $customPrice=[288,218,98,418,198]; ?>
<section class="ref-quote ref-custom" data-quote-editor data-quote-type="custom">
  <header class="custom-actionbar"><button data-draft-save>▱ 保存草稿</button><button>◉ 预览</button><button>▣ 打印</button><button>▤ 导出PDF</button><button>▤ 导出Excel</button><button>▱ 提交审核</button><button class="primary">➤ 发送报价</button><span>类型：定制品报价单</span></header>
  <div class="ref-body custom-body">
    <main>
      <section class="ref-panel"><h2>报价信息</h2><div class="custom-info"><?php foreach(['报价单号 *'=>'QT-20240523-001','国家/地区 *'=>'🇨🇳 中国','付款方式'=>'30% 预付款，70% 发货前','客户 *'=>'星辉照明（深圳）有限公司','币种 *'=>'CNY 人民币','贸易条款'=>'FOB 深圳','联系人'=>'张经理','有效期 *'=>'2024-06-22','备注'=>'请输入备注信息（可选）','项目名称'=>'星辉总部大楼照明定制方案','负责人 *'=>'邱磊' ] as $label=>$value):?><label><span><?=$label?></span><?= $label==='备注'?'<textarea>'.$value.'</textarea>':'<input value="'.$value.'">'?></label><?php endforeach;?></div></section>
      <section class="ref-panel custom-uploads"><h2>客户需求 / 参考资料</h2><div><?php foreach(['产品图片','参考图','尺寸图','客户文件'] as $u):?><label><input type="file" multiple hidden data-file-upload><b>↥ 上传<?=$u?></b><span>拖拽或点击上传</span><em data-file-count>尚未选择</em></label><?php endforeach;?></div></section>
      <section class="ref-panel custom-lines"><div class="panel-title"><h2>报价明细 <small>（支持高度自定义项）</small></h2><nav><button data-add-line>＋ 添加明细</button><button>批量导入</button><button>批量删除</button></nav></div><div class="ref-table-scroll"><table><thead><tr><th>#</th><th>图片</th><th>自定义产品名称 *</th><th>规格说明</th><th>数量 *</th><th>单位</th><th>目标单价</th><th>报价单价 *</th><th>小计</th><th>备注</th><th>操作</th></tr></thead><tbody data-quote-lines><?php foreach($rows as $i=>$row):$img=cc_legacy_asset_url($row['image_path']??'');?><tr><td><?=$i+1?></td><td><div class="ref-thumb"><?php if($img):?><img src="<?=cc_h($img)?>" alt=""><?php else:?>＋<?php endif;?></div></td><td><input value="<?=$customNames[$i]?>"></td><td><textarea><?=$customSpecs[$i]?></textarea></td><td><input type="number" value="<?=$customQty[$i]?>" data-qty></td><td><input value="<?=$i===1?'m':'pcs'?>"></td><td><input value="<?=$customTarget[$i]?>"></td><td><input type="number" value="<?=$customPrice[$i]?>" data-price></td><td data-line-total>0.00</td><td><input value="<?=['防眩角≤30°','配扩散罩','开孔Ø75mm','非标定制1200mm','需过载保护'][$i]?>"></td><td><button>复制</button><button class="text-danger" data-remove-line>删除</button></td></tr><?php endforeach;?></tbody></table></div><footer><button data-add-line>＋ 添加明细</button><span>共 <?=count($rows)?> 项</span></footer></section>
    </main>
    <aside><section class="ref-panel custom-fields-side"><h2>自由录入 / 自定义字段</h2><div data-custom-fields><?php foreach(['材质'=>'铝合金','颜色'=>'黑色（RAL 9005）','尺寸'=>'可定制','功率'=>'按方案配置','安装方式'=>'轨道 / 嵌入 / 吊装','特殊工艺'=>'阳极氧化 + 喷涂'] as $k=>$v):?><label><?=$k?><input value="<?=$v?>"></label><?php endforeach;?></div><button data-add-field>＋ 增加自定义字段</button></section><section class="ref-panel reference-product"><h2>关联参考产品（可选）</h2><input placeholder="选择标准产品（可选）"><p><span class="ref-thumb">图</span><b><?=cc_h($rows[0]['model_no']??'52.03526')?></b><small>仅作为参考，不限制自由报价</small></p></section><section class="ref-panel total-box"><h2>报价汇总 <small>CNY</small></h2><dl><dt>产品金额（小计）</dt><dd data-subtotal>0.00</dd><dt>折扣</dt><dd><input value="0" data-order-discount></dd><dt>运费</dt><dd><input value="1800" data-shipping></dd><dt>税费（13%）</dt><dd><input value="0" data-tax></dd></dl><div><b>总金额</b><strong data-grand-total>0.00</strong></div></section><section class="ref-panel engineer-note"><h2>工程说明 / 特殊要求 / 审核提醒</h2><ul><li>该项目为非标定制产品，需完成光效与防眩评估。</li><li>非标产品需开模，交期预计 30–35 天。</li><li>请内部核价确认成本与毛利。</li></ul></section></aside>
  </div>
  <div class="standard-workflow custom-flow"><b>内部流程</b><?php foreach(['草稿'=>'当前状态','内部核价'=>'待核价','待审核'=>'待提交','已发送'=>'尚未发送','转项目/转订单'=>'未执行'] as $step=>$state):?><span><strong><?=$step?></strong><small><?=$state?></small></span><i>›</i><?php endforeach;?></div>
</section>
