<?php
$h=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$titles=['quotation'=>'QUOTATION','order_usd'=>'PROFORMA INVOICE','order_cny'=>'订购合同','packing_list'=>'PACKING LIST','commercial_invoice'=>'COMMERCIAL INVOICE'];
$title=$titles[$documentType]??'DOCUMENT';$isPack=$documentType==='packing_list';$isInvoice=in_array($documentType,['quotation','order_usd','order_cny','commercial_invoice'],true);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title><?=$h($title)?></title><link rel="stylesheet" href="<?=cc_public_path('/modules/documents/Templates/shared/legacy_v1.css')?>"></head><body>
<div class="fixture"><?=$document['is_fixture']?'演示数据 · 不可用于正式业务':''?></div><div class="toolbar no-print"><button onclick="window.print()">打印 / 另存为 PDF</button><span>Excel：本阶段待独立导出服务</span></div>
<main class="paper"><header><div><h1><?=$h($document['company']['name'])?></h1><p><?=$h($document['company']['address'])?></p></div><div><h2><?=$h($title)?></h2><table><tr><th><?=$isPack?'PI No.':($documentType==='commercial_invoice'?'CI No.':($documentType==='order_usd'?'PI No.':'Document No.'))?></th><td><?=$h($isPack?$document['pi_no']:($documentType==='commercial_invoice'?$document['ci_no']:$document['number']))?></td></tr><tr><th>Date</th><td><?=$h($document['date'])?></td></tr><tr><th>Customer PO</th><td><?=$h($document['customer_po'])?></td></tr></table></div></header>
<section class="party"><b>Buyer / Consignee</b><p><?=$h($document['customer']['name'])?><br><?=$h($document['customer']['contact'])?><br><?=$h($document['customer']['address'])?></p></section>
<table class="items"><thead><tr><th>#</th><th>Picture</th><th>Customer Model</th><th>Manufacturer Code</th><th>Description / Configuration</th><th>QTY</th><?php if($isPack):?><th>Cartons</th><th>N.W.</th><th>G.W.</th><th>Carton Size</th><?php else:?><th>Unit Price</th><th>Amount</th><?php endif;?></tr></thead><tbody><?php $total=0;foreach($document['items'] as $i=>$item):$amount=(float)$item['quantity']*(float)$item['unit_price'];$total+=$amount;?><tr><td><?=$i+1?></td><td></td><td><?=$h($item['customer_model'])?></td><td><?=$h($item['manufacturer_code'])?></td><td class="left"><?=$h($item['description'])?></td><td><?=$h($item['quantity'])?></td><?php if($isPack):?><td><?=$h($item['cartons'])?></td><td><?=$h($item['net_weight'])?></td><td><?=$h($item['gross_weight'])?></td><td><?=$h($item['carton_size'])?></td><?php else:?><td><?=number_format((float)$item['unit_price'],2)?></td><td><?=number_format($amount,2)?></td><?php endif;?></tr><?php endforeach;?></tbody></table>
<?php if($isInvoice):?><section class="totals"><div><b>Terms</b><p><?=$h($document['terms'])?></p><b>Bank Information</b><p><?=$h($document['bank'])?></p></div><strong>Total <?=$h($document['currency'])?> <?=number_format($total,2)?></strong></section><?php endif;?>
<footer><span>Template <?=$h($templateVersion)?></span><div>For and on behalf of<br><br><b><?=$h($document['signature'])?></b></div></footer></main></body></html>
