<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use Artdon\CommercialCenter\Services\ApprovalCenterService;use Artdon\CommercialCenter\Services\CustomQuoteService;use Artdon\CommercialCenter\Services\LegacyOrderConversionService;use Artdon\CommercialCenter\Services\QuotePermissionService;
if(($argv[1]??'')!=='--write-test'){echo "PASS: approval/conversion test loaded; use --write-test.\n";exit;}
$db=db();$actor=['id'=>0,'username'=>'step910-test','display_name'=>'STEP 9/10 TEST','is_test_actor'=>true,'test_permissions'=>QuotePermissionService::ACTIONS];$quoteIds=[];$orderId=0;
try{$custom=new CustomQuoteService();$customer=$custom->bootstrap(0)['customers'][0]??null;if(!is_array($customer))throw new RuntimeException('Customer missing');
$base=['customer_id'=>(int)$customer['id'],'currency'=>'USD','valid_until'=>date('Y-m-d',strtotime('+30 days')),'payment_terms'=>'30% deposit','trade_terms'=>'FOB','is_test'=>1,'discount_amount'=>12,
'items'=>[['description'=>'Custom approval item','product_name'=>'Custom approval item','quantity'=>2,'unit'=>'PCS','unit_price'=>100,'configuration_snapshot'=>['power'=>'12W'],'custom_fields'=>['estimated_cost'=>90,'customer_model'=>'CM-100','manufacturer_code'=>'MF-200','color'=>'Black']]]];
$q=$custom->save($base,$actor);$quoteIds[]=(int)$q['id'];$custom->submit((int)$q['id'],$actor);$approval=new ApprovalCenterService();$detail=$approval->detail((int)$q['id'],$actor);
if(!in_array('特殊折扣',$detail['risk']['reasons'],true)||$detail['risk']['level']==='low')throw new RuntimeException('Risk trigger failed');
$approval->act((int)$q['id'],'escalate','高风险转上级','director',$actor);$approved=$approval->act((int)$q['id'],'approve','审核通过','',$actor);if($approved['status']!=='approved')throw new RuntimeException('Approval failed');
$converted=(new LegacyOrderConversionService())->convert((int)$q['id'],$actor);$orderId=(int)$converted['order_id'];if($orderId<=0||$converted['order_no']===''||!str_contains($converted['documents']['ci'],'quote_order_doc.php'))throw new RuntimeException('Conversion/document links failed');
$order=$db->query("SELECT * FROM quote_sales_orders WHERE id={$orderId}")->fetch(PDO::FETCH_ASSOC);$items=json_decode((string)$order['items_json'],true)?:[];
if(($items[0]['customer_code']??'')!=='CM-100'||($items[0]['product_code']??'')!=='MF-200'||(float)$order['amount']!==188.0)throw new RuntimeException('Order snapshot mapping failed');
$docs=(int)$db->query("SELECT COUNT(*) FROM cc_legacy_document_snapshots WHERE legacy_order_id={$orderId}")->fetchColumn();if($docs!==3)throw new RuntimeException('PI/CI/PL snapshots missing');
$q2=$custom->save($base+['project_name'=>'CHANGE REQUEST'],$actor);$quoteIds[]=(int)$q2['id'];$custom->submit((int)$q2['id'],$actor);$changed=$approval->act((int)$q2['id'],'request_changes','补充结构图','',$actor);if($changed['status']!=='rejected')throw new RuntimeException('Request changes failed');
echo "PASS: queue risk, escalation, approval, request changes, immutable conversion and PI/CI/PL legacy links verified.\n";
}finally{if($orderId){$shipIds=$db->query("SELECT id FROM quote_shipments WHERE order_id={$orderId}")->fetchAll(PDO::FETCH_COLUMN);if($shipIds){$s=implode(',',array_map('intval',$shipIds));$db->exec("DELETE FROM quote_shipment_cartons WHERE shipment_id IN ({$s})");$db->exec("DELETE FROM quote_shipment_items WHERE shipment_id IN ({$s})");$db->exec("DELETE FROM quote_shipments WHERE id IN ({$s})");}$db->exec("DELETE FROM cc_legacy_document_snapshots WHERE legacy_order_id={$orderId}");$db->exec("DELETE FROM cc_quote_order_links WHERE legacy_order_id={$orderId}");$db->exec("DELETE FROM quote_sales_order_items WHERE order_id={$orderId}");$db->exec("DELETE FROM quote_sales_orders WHERE id={$orderId}");}
foreach($quoteIds as $qid){$versions=$db->query("SELECT id FROM cc_quote_versions WHERE quote_id={$qid}")->fetchAll(PDO::FETCH_COLUMN);if($versions){$v=implode(',',array_map('intval',$versions));$items=$db->query("SELECT id FROM cc_quote_items WHERE quote_version_id IN ({$v})")->fetchAll(PDO::FETCH_COLUMN);if($items){$i=implode(',',array_map('intval',$items));$db->exec("DELETE FROM cc_quote_item_snapshots WHERE quote_item_id IN ({$i})");$db->exec("DELETE FROM cc_quote_item_adaptation_refs WHERE quote_item_id IN ({$i})");$db->exec("DELETE FROM cc_quote_item_details WHERE quote_item_id IN ({$i})");$db->exec("DELETE FROM cc_quote_items WHERE id IN ({$i})");}}$db->exec("DELETE FROM cc_quote_review_actions WHERE quote_id={$qid}");$db->exec("DELETE FROM cc_quote_approvals WHERE quote_id={$qid}");$db->exec("DELETE FROM cc_quote_state_history WHERE quote_id={$qid}");$db->exec("DELETE FROM cc_quote_audit_logs WHERE quote_id={$qid}");$db->exec("DELETE FROM cc_quote_snapshots WHERE quote_id={$qid}");$db->exec("DELETE FROM cc_quotation_logs WHERE quote_id={$qid}");if($versions)$db->exec("DELETE FROM cc_quote_versions WHERE id IN (".implode(',',array_map('intval',$versions)).")");$db->exec("DELETE FROM cc_quote_channel_context WHERE quote_id={$qid}");$db->exec("DELETE FROM cc_quote_details WHERE quote_id={$qid}");$db->exec("DELETE FROM cc_quotes WHERE id={$qid} AND is_test=1");}}
