<?php
declare(strict_types=1);
namespace Artdon\MaterialCenter\Services;

use Artdon\MaterialCenter\Adapters\LegacyProductAdapter;
use PDO;
use RuntimeException;

final class AdaptationService
{
 public function __construct(private ?PDO$db=null){$this->db??=\db();}
 public function syncProducts(int$userId):array{$adapter=new LegacyProductAdapter($this->db);$after=0;$seen=0;$created=0;$changed=0;do{$rows=$adapter->allAfter($after,500);if(!$rows)break;$this->db->beginTransaction();try{foreach($rows as$row){$after=max($after,(int)$row['id']);$seen++;$json=json_encode($row,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$hash=hash('sha256',$json);$old=$this->db->prepare("SELECT id,snapshot_hash FROM mc_products WHERE legacy_table='naming_models' AND legacy_id=?");$old->execute([$row['id']]);$existing=$old->fetch(PDO::FETCH_ASSOC);if(!$existing){$this->db->prepare("INSERT INTO mc_products(legacy_table,legacy_id,product_code,product_name,snapshot_json,snapshot_hash,synced_at,status)VALUES('naming_models',?,?,?,?,?,NOW(),'active')")->execute([$row['id'],$row['model_no'],$row['product_name']?:$row['item_name'],$json,$hash]);$created++;}elseif(!hash_equals($existing['snapshot_hash'],$hash)){$this->db->prepare("UPDATE mc_products SET product_code=?,product_name=?,snapshot_json=?,snapshot_hash=?,synced_at=NOW() WHERE id=?")->execute([$row['model_no'],$row['product_name']?:$row['item_name'],$json,$hash,$existing['id']]);$changed++;}}$this->db->commit();}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}while(count($rows)===500);$this->log(0,'sync_products',['seen'=>$seen,'created'=>$created,'changed'=>$changed],$userId);return['seen'=>$seen,'created'=>$created,'changed'=>$changed];}
 public function products(string$q=''):array{$sql="SELECT p.*,(SELECT COUNT(*) FROM mc_adaptation_groups g WHERE g.product_id=p.id) group_count,(SELECT COUNT(*) FROM mc_adaptation_conflicts c WHERE c.product_id=p.id AND c.status='active') conflict_count FROM mc_products p WHERE p.status='active'";$params=[];if($q!==''){$sql.=' AND (p.product_code LIKE ? OR p.product_name LIKE ?)';$like='%'.$q.'%';$params=[$like,$like];}$sql.=' ORDER BY p.product_code LIMIT 500';$stmt=$this->db->prepare($sql);$stmt->execute($params);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
 public function groups(int$productId):array{$stmt=$this->db->prepare("SELECT g.*,(SELECT COUNT(*) FROM mc_adaptation_options o WHERE o.group_id=g.id) option_count,(SELECT CONCAT(m.material_code,' ',m.name) FROM mc_adaptation_options o JOIN mc_materials m ON m.id=o.material_id WHERE o.group_id=g.id AND o.is_default=1 LIMIT 1) default_material FROM mc_adaptation_groups g WHERE g.product_id=? ORDER BY g.sort_order,g.id");$stmt->execute([$productId]);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
 public function options(int$groupId):array{$stmt=$this->db->prepare("SELECT o.*,m.material_code,m.name,m.brand,m.model FROM mc_adaptation_options o JOIN mc_materials m ON m.id=o.material_id WHERE o.group_id=? AND m.deleted_at IS NULL ORDER BY o.sort_order,o.id");$stmt->execute([$groupId]);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
 public function saveGroup(array$d,int$userId):int{$product=(int)($d['product_id']??0);$code=preg_replace('/[^a-z0-9_]/','',strtolower((string)($d['group_code']??'')));$name=trim((string)($d['group_name']??''));$type=(string)($d['group_type']??'custom');if(!$product||$code===''||$name==='')throw new RuntimeException('产品、配置组代码和名称不能为空。');$this->db->beginTransaction();try{$stmt=$this->db->prepare("INSERT INTO mc_adaptation_groups(product_id,group_code,group_name,group_type,status,sort_order,created_by,created_at,updated_at)VALUES(?,?,?,?,'draft',?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE group_name=VALUES(group_name),group_type=VALUES(group_type),sort_order=VALUES(sort_order),updated_at=NOW()");$stmt->execute([$product,$code,$name,$type,(int)($d['sort_order']??0),$userId]);$find=$this->db->prepare('SELECT id FROM mc_adaptation_groups WHERE product_id=? AND group_code=?');$find->execute([$product,$code]);$id=(int)$find->fetchColumn();$this->log($product,'save_group',['group_id'=>$id,'code'=>$code],$userId);$this->db->commit();return$id;}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 public function saveOption(array$d,int$userId):int{$group=(int)($d['group_id']??0);$material=(int)($d['material_id']??0);$type=(string)($d['option_type']??'optional');if(!$group||!$material||!in_array($type,['required','optional','alternative','conditional','disabled'],true))throw new RuntimeException('配置组、物料或选项类型无效。');$price=$d['price_impact']??'';$lead=$d['lead_time_impact_days']??'';$this->db->beginTransaction();try{if(!empty($d['is_default']))$this->db->prepare('UPDATE mc_adaptation_options SET is_default=0 WHERE group_id=?')->execute([$group]);$this->db->prepare("INSERT INTO mc_adaptation_options(group_id,material_id,option_type,is_default,price_impact,lead_time_impact_days,status,sort_order)VALUES(?,?,?,?,?,?,'draft',?) ON DUPLICATE KEY UPDATE option_type=VALUES(option_type),is_default=VALUES(is_default),price_impact=VALUES(price_impact),lead_time_impact_days=VALUES(lead_time_impact_days),sort_order=VALUES(sort_order)")->execute([$group,$material,$type,!empty($d['is_default'])?1:0,$price!==''?(float)$price:null,$lead!==''?(int)$lead:null,(int)($d['sort_order']??0)]);$find=$this->db->prepare('SELECT id FROM mc_adaptation_options WHERE group_id=? AND material_id=?');$find->execute([$group,$material]);$id=(int)$find->fetchColumn();foreach((array)($d['conditions']??[])as$c){if(empty($c['field_code'])||empty($c['operator']))continue;$this->db->prepare('INSERT INTO mc_adaptation_conditions(option_id,field_code,operator,expected_json,failure_message,severity,sort_order)VALUES(?,?,?,?,?,?,?)')->execute([$id,$c['field_code'],$c['operator'],json_encode($c['expected']??null,JSON_UNESCAPED_UNICODE),$c['failure_message']??'条件不满足',$c['severity']??'block',(int)($c['sort_order']??0)]);}$this->log(0,'save_option',['option_id'=>$id,'group_id'=>$group],$userId);$this->db->commit();return$id;}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 public function approveProduct(int$productId,int$userId):void{$this->db->beginTransaction();try{$groups=$this->groups($productId);if(!$groups)throw new RuntimeException('产品没有可审批配置组。');foreach($groups as$group)if((int)$group['option_count']<1)throw new RuntimeException($group['group_name'].'没有物料选项。');if($this->hasCycle($productId))throw new RuntimeException('适配替代关系存在循环。');$this->db->prepare("UPDATE mc_adaptation_groups SET status='approved',updated_at=NOW() WHERE product_id=?")->execute([$productId]);$this->db->prepare("UPDATE mc_adaptation_options o JOIN mc_adaptation_groups g ON g.id=o.group_id SET o.status='approved' WHERE g.product_id=?")->execute([$productId]);$this->log($productId,'approve',['groups'=>count($groups)],$userId);$this->db->commit();}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 public function approved(int$legacyProductId):array{$stmt=$this->db->prepare("SELECT p.product_code,p.product_name,g.group_code,g.group_name,o.option_type,o.is_default,o.price_impact,o.lead_time_impact_days,m.id material_id,m.material_code,m.name material_name,m.brand,m.model FROM mc_products p JOIN mc_adaptation_groups g ON g.product_id=p.id AND g.status='approved' JOIN mc_adaptation_options o ON o.group_id=g.id AND o.status='approved' JOIN mc_materials m ON m.id=o.material_id AND m.deleted_at IS NULL WHERE p.legacy_table='naming_models' AND p.legacy_id=? ORDER BY g.sort_order,o.sort_order");$stmt->execute([$legacyProductId]);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
 private function hasCycle(int$productId):bool{$stmt=$this->db->prepare("SELECT o.id,o2.id target FROM mc_adaptation_options o JOIN mc_adaptation_groups g ON g.id=o.group_id LEFT JOIN mc_adaptation_defaults d ON d.option_id=o.id LEFT JOIN mc_adaptation_options o2 ON o2.id=d.option_id WHERE g.product_id=?");$stmt->execute([$productId]);return false;}
 private function log(int$productId,string$action,array$data,int$user):void{$this->db->prepare("INSERT INTO mc_adaptation_logs(product_id,action,detail_json,actor_id,created_at)VALUES(?,?,?,?,NOW())")->execute([$productId,$action,json_encode($data,JSON_UNESCAPED_UNICODE),$user]);}
}
