<?php
declare(strict_types=1);
namespace Artdon\MaterialCenter\Services;

use PDO;
use RuntimeException;

final class DocumentService
{
 private const EXTENSIONS=['pdf','png','jpg','jpeg','webp','doc','docx','xls','xlsx','csv','ies','ldt','zip'];
 public function __construct(private ?PDO$db=null){$this->db??=\db();}
 public function rows(string$q=''):array{$sql="SELECT d.*,m.material_code,m.name material_name,v.version_no,v.mime_type,v.file_size,v.sha256 FROM mc_material_documents d JOIN mc_materials m ON m.id=d.material_id LEFT JOIN mc_document_versions v ON v.id=(SELECT id FROM mc_document_versions x WHERE x.document_id=d.id ORDER BY version_no DESC LIMIT 1) WHERE d.deleted_at IS NULL";$params=[];if($q!==''){$sql.=' AND (d.file_name LIKE ? OR m.material_code LIKE ? OR m.name LIKE ?)';$like='%'.$q.'%';$params=[$like,$like,$like];}$sql.=' ORDER BY d.created_at DESC LIMIT 500';$stmt=$this->db->prepare($sql);$stmt->execute($params);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
 public function upload(array$file,array$d,int$userId):int{$material=(int)($d['material_id']??0);$this->assertMaterial($material);if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('文件上传失败。');$size=(int)($file['size']??0);if($size<1||$size>25*1024*1024)throw new RuntimeException('文件必须小于 25MB。');$original=basename((string)($file['name']??''));$ext=strtolower(pathinfo($original,PATHINFO_EXTENSION));if(!in_array($ext,self::EXTENSIONS,true))throw new RuntimeException('不允许的文件类型。');$tmp=(string)$file['tmp_name'];$mime=$this->mime($tmp,$ext);if(str_starts_with($mime,'text/x-php')||str_contains($mime,'executable'))throw new RuntimeException('文件内容类型不安全。');$sha=hash_file('sha256',$tmp);$dir=MC_ROOT.'/storage/documents/'.date('Y/m');if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('文档目录不可写。');$stored=bin2hex(random_bytes(16)).'.'.$ext;$path=$dir.'/'.$stored;if(!move_uploaded_file($tmp,$path)&&!rename($tmp,$path))throw new RuntimeException('文件保存失败。');chmod($path,0640);$type=trim((string)($d['document_type']??'datasheet'))?:'datasheet';$access=(string)($d['access_level']??'internal');if(!in_array($access,['internal','engineering','purchasing','public'],true))$access='internal';$documentId=(int)($d['document_id']??0);$this->db->beginTransaction();try{if(!$documentId){$this->db->prepare('INSERT INTO mc_material_documents(material_id,document_type,file_name,file_path,version,created_by,created_at)VALUES(?,?,?,?,?, ?,NOW())')->execute([$material,$type,$original,$path,'1',$userId]);$documentId=(int)$this->db->lastInsertId();$version=1;}else{$stmt=$this->db->prepare('SELECT COALESCE(MAX(version_no),0)+1 FROM mc_document_versions WHERE document_id=?');$stmt->execute([$documentId]);$version=(int)$stmt->fetchColumn();$this->db->prepare('UPDATE mc_material_documents SET file_name=?,file_path=?,version=? WHERE id=? AND material_id=? AND deleted_at IS NULL')->execute([$original,$path,(string)$version,$documentId,$material]);}
   $this->db->prepare('INSERT INTO mc_document_versions(document_id,version_no,file_name,file_path,mime_type,file_size,sha256,access_level,created_by,created_at)VALUES(?,?,?,?,?,?,?,?,?,NOW())')->execute([$documentId,$version,$original,$path,$mime,$size,$sha,$access,$userId]);$this->db->prepare("INSERT INTO mc_operation_logs(module,object_type,object_id,action,new_value_json,actor_id,actor_ip,result,created_at)VALUES('material_center','document',?,'upload',?,?,?,'success',NOW())")->execute([$documentId,json_encode(['version'=>$version,'sha256'=>$sha,'material_id'=>$material]),$userId,(string)($_SERVER['REMOTE_ADDR']??'cli')]);$this->db->commit();return$documentId;}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();@unlink($path);throw$e;}}
 public function version(int$documentId):array{$stmt=$this->db->prepare('SELECT v.*,d.material_id FROM mc_document_versions v JOIN mc_material_documents d ON d.id=v.document_id WHERE v.document_id=? AND d.deleted_at IS NULL ORDER BY v.version_no DESC LIMIT 1');$stmt->execute([$documentId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row||!is_file($row['file_path']))throw new RuntimeException('文件不存在。',404);return$row;}
 public function delete(int$documentId,int$userId):void{$stmt=$this->db->prepare('UPDATE mc_material_documents SET deleted_at=NOW() WHERE id=? AND deleted_at IS NULL');$stmt->execute([$documentId]);if(!$stmt->rowCount())throw new RuntimeException('文档不存在。');$this->db->prepare("INSERT INTO mc_operation_logs(module,object_type,object_id,action,actor_id,actor_ip,result,created_at)VALUES('material_center','document',?,'delete',?,?,'success',NOW())")->execute([$documentId,$userId,(string)($_SERVER['REMOTE_ADDR']??'cli')]);}
 public function logs(int$limit=200):array{return$this->db->query('SELECT * FROM mc_operation_logs ORDER BY created_at DESC,id DESC LIMIT '.max(1,min(500,$limit)))->fetchAll(PDO::FETCH_ASSOC);}
 private function mime(string$path,string$ext):string{if(function_exists('finfo_open')){$f=finfo_open(FILEINFO_MIME_TYPE);if($f){$m=finfo_file($f,$path);finfo_close($f);if(is_string($m)&&$m!=='')return$m;}}if(function_exists('mime_content_type')){$m=mime_content_type($path);if(is_string($m)&&$m!=='')return$m;}return match($ext){'png'=>'image/png','jpg','jpeg'=>'image/jpeg','webp'=>'image/webp','pdf'=>'application/pdf','csv'=>'text/csv','zip','xlsx','docx'=>'application/zip',default=>'application/octet-stream'};}
 private function assertMaterial(int$id):void{$stmt=$this->db->prepare('SELECT 1 FROM mc_materials WHERE id=? AND deleted_at IS NULL');$stmt->execute([$id]);if(!$stmt->fetchColumn())throw new RuntimeException('关联物料不存在。');}
}
