<?php
declare(strict_types=1);
namespace Artdon\MaterialCenter\Services;

use PDO;
use RuntimeException;
use ZipArchive;

final class ImportService
{
 public function __construct(private ?PDO$db=null){$this->db??=\db();}
 public function upload(array$file,int$userId):array{
  if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('上传失败，请重新选择文件。');
  $size=(int)($file['size']??0);if($size<1||$size>10*1024*1024)throw new RuntimeException('文件大小必须在 10MB 内。');
  $name=basename((string)($file['name']??''));$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));if(!in_array($ext,['csv','xlsx'],true))throw new RuntimeException('仅支持 CSV 或 XLSX。');
  $rows=$ext==='csv'?$this->csv((string)$file['tmp_name']):$this->xlsx((string)$file['tmp_name']);if(!$rows)throw new RuntimeException('文件没有可导入数据。');
  $uuid=$this->uuid();$dir=MC_ROOT.'/storage/imports';if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('导入目录不可写。');$path=$dir.'/'.$uuid.'.'.$ext;if(!move_uploaded_file((string)$file['tmp_name'],$path)&&!rename((string)$file['tmp_name'],$path))throw new RuntimeException('无法保存导入文件。');
  $this->db->beginTransaction();try{$this->db->prepare("INSERT INTO mc_import_tasks(task_uuid,import_type,file_name,file_path,status,total_rows,created_by,created_at)VALUES(?,'material',?,?,'prechecked',?,?,NOW())")->execute([$uuid,$name,$path,count($rows),$userId]);$task=(int)$this->db->lastInsertId();$success=0;$errors=0;
   foreach($rows as$i=>$raw){$normalized=$this->normalize($raw);$messages=$this->validate($normalized);$result=$messages?'error':'valid';$this->db->prepare('INSERT INTO mc_import_rows(task_id,row_no,raw_json,normalized_json,result)VALUES(?,?,?,?,?)')->execute([$task,$i+2,json_encode($raw,JSON_UNESCAPED_UNICODE),json_encode($normalized,JSON_UNESCAPED_UNICODE),$result]);if($messages){$errors++;foreach($messages as[$field,$code,$message])$this->db->prepare('INSERT INTO mc_import_errors(task_id,row_no,field_code,error_code,error_message,raw_value,created_at)VALUES(?,?,?,?,?,?,NOW())')->execute([$task,$i+2,$field,$code,$message,(string)($normalized[$field]??'')]);}else$success++;}
   $this->db->prepare('UPDATE mc_import_tasks SET success_rows=?,error_rows=? WHERE id=?')->execute([$success,$errors,$task]);$this->db->commit();return['task_uuid'=>$uuid,'total'=>count($rows),'valid'=>$success,'errors'=>$errors];
  }catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();@unlink($path);throw$e;}
 }
 public function execute(string$uuid,int$userId):array{
  $stmt=$this->db->prepare("SELECT * FROM mc_import_tasks WHERE task_uuid=? AND status='prechecked' FOR UPDATE");$this->db->beginTransaction();try{$stmt->execute([$uuid]);$task=$stmt->fetch(PDO::FETCH_ASSOC);if(!$task)throw new RuntimeException('导入任务不存在或已执行。');if((int)$task['error_rows']>0)throw new RuntimeException('请先修复全部预检错误。');$rows=$this->db->prepare("SELECT * FROM mc_import_rows WHERE task_id=? AND result='valid' ORDER BY row_no");$rows->execute([$task['id']]);$service=new MaterialMasterService($this->db);$count=0;foreach($rows->fetchAll(PDO::FETCH_ASSOC)as$row){$d=json_decode((string)$row['normalized_json'],true);$cat=$this->db->prepare("SELECT id FROM mc_material_categories WHERE code=? AND status='active'");$cat->execute([$d['category_code']]);$d['category_id']=(int)$cat->fetchColumn();$id=$service->save($d,$userId);$this->db->prepare("UPDATE mc_import_rows SET result='success',entity_id=? WHERE id=?")->execute([$id,$row['id']]);$count++;}$this->db->prepare("UPDATE mc_import_tasks SET status='completed',completed_at=NOW() WHERE id=?")->execute([$task['id']]);$this->db->commit();return['success'=>$count];
  }catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}
 }
 public function errors(string$uuid):array{$stmt=$this->db->prepare('SELECT e.row_no,e.field_code,e.error_code,e.error_message,e.raw_value FROM mc_import_errors e JOIN mc_import_tasks t ON t.id=e.task_id WHERE t.task_uuid=? ORDER BY e.row_no,e.id');$stmt->execute([$uuid]);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
 private function normalize(array$row):array{$aliases=['物料类别'=>'category_code','类别'=>'category_code','category'=>'category_code','物料名称'=>'name','名称'=>'name','品牌'=>'brand','型号'=>'model','单位'=>'unit','规格'=>'spec_summary','关键规格'=>'spec_summary'];$out=[];foreach($row as$k=>$v){$key=$aliases[trim((string)$k)]??trim((string)$k);$out[$key]=trim((string)$v);}if(($out['unit']??'')==='')$out['unit']='PCS';return$out;}
 private function validate(array$d):array{$e=[];if(($d['category_code']??'')==='')$e[]=['category_code','required','类别不能为空'];elseif(!in_array($d['category_code'],['power_supply','chip','optical','profile','connector','accessory','packaging'],true))$e[]=['category_code','invalid','类别代码无效'];if(($d['name']??'')==='')$e[]=['name','required','名称不能为空'];if(mb_strlen((string)($d['name']??''))>200)$e[]=['name','too_long','名称超过200字符'];return$e;}
 private function csv(string$path):array{$fh=fopen($path,'rb');if(!$fh)throw new RuntimeException('CSV 无法读取。');$header=fgetcsv($fh);if(!$header){fclose($fh);return[];}$header=array_map(static fn($v)=>preg_replace('/^\xEF\xBB\xBF/','',trim((string)$v)),$header);$rows=[];while(($values=fgetcsv($fh))!==false){if(!array_filter($values,static fn($v)=>trim((string)$v)!==''))continue;$values=array_pad($values,count($header),'');$rows[]=array_combine($header,array_slice($values,0,count($header)));}fclose($fh);return$rows;}
 private function xlsx(string$path):array{if(!class_exists(ZipArchive::class))throw new RuntimeException('服务器未启用 ZIP，暂不能读取 XLSX；可另存为 CSV。');$zip=new ZipArchive();if($zip->open($path)!==true)throw new RuntimeException('XLSX 文件损坏。');$shared=[];$sharedXml=$zip->getFromName('xl/sharedStrings.xml');if($sharedXml!==false){$xml=simplexml_load_string($sharedXml);foreach($xml->si as$si)$shared[]=trim(implode('',array_map('strval',$si->xpath('.//t'))));}$sheet=$zip->getFromName('xl/worksheets/sheet1.xml');$zip->close();if($sheet===false)throw new RuntimeException('XLSX 缺少第一个工作表。');$xml=simplexml_load_string($sheet);$matrix=[];foreach($xml->sheetData->row as$row){$line=[];foreach($row->c as$cell){$ref=(string)$cell['r'];preg_match('/^[A-Z]+/',$ref,$m);$column=$this->columnIndex($m[0]??'A');$value=(string)$cell->v;if((string)$cell['t']==='s')$value=$shared[(int)$value]??'';elseif((string)$cell['t']==='inlineStr')$value=(string)$cell->is->t;$line[$column]=$value;}if($line){ksort($line);$matrix[]=array_replace(array_fill(0,max(array_keys($line))+1,''),$line);}}if(!$matrix)return[];$header=array_map('trim',array_map('strval',array_shift($matrix)));$rows=[];foreach($matrix as$line){$line=array_pad($line,count($header),'');if(array_filter($line,static fn($v)=>trim((string)$v)!==''))$rows[]=array_combine($header,array_slice($line,0,count($header)));}return$rows;}
 private function columnIndex(string$letters):int{$n=0;foreach(str_split($letters)as$letter)$n=$n*26+(ord($letter)-64);return$n-1;}
 private function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
}
