<?php
declare(strict_types=1);
namespace Artdon\MaterialCenter\Services;
use PDO;use RuntimeException;
final class MaterialMasterService{
 public function __construct(private ?PDO$db=null){$this->db??=\db();}
 public function rows(string$q=''):array{$sql="SELECT m.*,c.code category_code,c.name category_name,(SELECT COUNT(*) FROM mc_legacy_links l WHERE l.material_id=m.id) legacy_links FROM mc_materials m JOIN mc_material_categories c ON c.id=m.category_id WHERE m.deleted_at IS NULL";$p=[];if($q!==''){$sql.=" AND (m.material_code LIKE ? OR m.name LIKE ? OR m.brand LIKE ? OR m.model LIKE ?)";$v='%'.$q.'%';$p=[$v,$v,$v,$v];}$sql.=" ORDER BY m.updated_at DESC,m.id DESC";$s=$this->db->prepare($sql);$s->execute($p);return$s->fetchAll(PDO::FETCH_ASSOC);}
 public function categories():array{return$this->db->query("SELECT id,code,name FROM mc_material_categories WHERE status='active' ORDER BY sort_order,id")->fetchAll(PDO::FETCH_ASSOC);}
 public function save(array$d,int$userId):int{
  foreach(['category_id','name','unit']as$k)if(trim((string)($d[$k]??''))==='')throw new RuntimeException('请完整填写分类、名称和单位。');
  $id=(int)($d['id']??0);$category=(int)$d['category_id'];$s=$this->db->prepare("SELECT code FROM mc_material_categories WHERE id=? AND status='active'");$s->execute([$category]);$categoryCode=$s->fetchColumn();if(!$categoryCode)throw new RuntimeException('物料分类无效。');
  if($id){$s=$this->db->prepare("UPDATE mc_materials SET category_id=?,brand=?,model=?,name=?,unit=?,updated_by=?,updated_at=NOW() WHERE id=? AND status='draft' AND deleted_at IS NULL");$s->execute([$category,$this->null($d['brand']??''),$this->null($d['model']??''),trim((string)$d['name']),trim((string)$d['unit']),$userId,$id]);if(!$s->rowCount())throw new RuntimeException('只有草稿物料可以直接编辑。');return$id;}
  $code=$this->nextCode((string)$categoryCode);$uuid=$this->uuid();$s=$this->db->prepare("INSERT INTO mc_materials(material_uuid,material_code,category_id,brand,model,name,unit,status,source,is_official,allow_bom,allow_quote,allow_customer_display,is_pilot,created_by,updated_by,created_at,updated_at)VALUES(?,?,?,?,?,?,?,'draft','material_center_manual',0,0,0,0,0,?,?,NOW(),NOW())");$s->execute([$uuid,$code,$category,$this->null($d['brand']??''),$this->null($d['model']??''),trim((string)$d['name']),trim((string)$d['unit']),$userId,$userId]);$id=(int)$this->db->lastInsertId();
  if($categoryCode==='power_supply')$this->db->prepare("INSERT INTO mc_power_supply_specs(material_id,installation_type,output_type,status,created_at,updated_at)VALUES(?,'unknown','unknown','draft',NOW(),NOW())")->execute([$id]);
  $this->log($id,'create',['source'=>'material_center_manual'],$userId);return$id;
 }
 public function copy(int$id,int$userId):int{$s=$this->db->prepare('SELECT * FROM mc_materials WHERE id=? AND deleted_at IS NULL');$s->execute([$id]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)throw new RuntimeException('原物料不存在。');$new=$this->save(['category_id'=>$r['category_id'],'brand'=>$r['brand'],'model'=>$r['model'],'name'=>$r['name'].'（复制）','unit'=>$r['unit']],$userId);$this->log($new,'copy',['source_material_id'=>$id],$userId);return$new;}
 public function transition(int$id,string$action,int$userId,string$reason=''):void{(new MaterialLifecycleService($this->db))->transition($id,$action,$userId,$reason);$this->log($id,$action,['reason'=>$reason],$userId);}
 public function deleteDraft(int$id,int$userId):void{$s=$this->db->prepare("SELECT status FROM mc_materials WHERE id=? AND deleted_at IS NULL");$s->execute([$id]);if($s->fetchColumn()!=='draft')throw new RuntimeException('只有草稿物料可以删除。');$refs=$this->references($id);if(array_sum($refs)>0)throw new RuntimeException('物料已有引用，不能删除草稿。');$this->db->beginTransaction();try{$this->db->prepare('DELETE FROM mc_power_supply_current_options WHERE material_id=?')->execute([$id]);$this->db->prepare('DELETE FROM mc_power_supply_dimming_modes WHERE material_id=?')->execute([$id]);$this->db->prepare('DELETE FROM mc_power_supply_specs WHERE material_id=?')->execute([$id]);$this->db->prepare('DELETE FROM mc_materials WHERE id=?')->execute([$id]);$this->log($id,'delete_draft',['references'=>$refs],$userId);$this->db->commit();}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 public function references(int$id):array{$checks=['legacy_links'=>'SELECT COUNT(*) FROM mc_legacy_links WHERE material_id=?','supplier_materials'=>'SELECT COUNT(*) FROM mc_supplier_materials WHERE material_id=?','alternatives'=>'SELECT COUNT(*) FROM mc_material_alternatives WHERE material_id=? OR alternative_material_id=?','product_rules'=>'SELECT COUNT(*) FROM mc_product_power_approved_alternatives WHERE material_id=?'];$out=[];foreach($checks as$k=>$sql){$s=$this->db->prepare($sql);$params=substr_count($sql,'?')===2?[$id,$id]:[$id];$s->execute($params);$out[$k]=(int)$s->fetchColumn();}return$out;}
 private function nextCode(string$category):string{$prefix=$category==='power_supply'?'PS':'MC';do{$code=$prefix.'-'.date('ymd').'-'.strtoupper(substr(bin2hex(random_bytes(4)),0,6));$s=$this->db->prepare('SELECT 1 FROM mc_materials WHERE material_code=?');$s->execute([$code]);}while($s->fetchColumn());return$code;}
 private function log(int$id,string$action,array$data,int$user):void{$this->db->prepare("INSERT INTO mc_activity_logs(entity_type,entity_id,action,after_json,actor_id,created_at)VALUES('material',?,?,?,?,NOW())")->execute([$id,$action,json_encode($data,JSON_UNESCAPED_UNICODE),$user]);}
 private function null(mixed$v):?string{$v=trim((string)$v);return$v===''?null:mb_substr($v,0,200);}
 private function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
}
