<?php
declare(strict_types=1);
namespace Artdon\MaterialCenter\Services;

use PDO;
use RuntimeException;

final class SubstitutionService
{
 public function __construct(private ?PDO$db=null){$this->db??=\db();}
 public function rows(string$q=''):array{$sql="SELECT s.*,m.material_code,m.name material_name,m.brand,m.model,a.material_code substitute_code,a.name substitute_name,a.brand substitute_brand,a.model substitute_model FROM mc_material_substitutions s JOIN mc_materials m ON m.id=s.material_id JOIN mc_materials a ON a.id=s.substitute_material_id WHERE m.deleted_at IS NULL AND a.deleted_at IS NULL";$params=[];if($q!==''){$sql.=" AND (m.material_code LIKE ? OR m.name LIKE ? OR a.material_code LIKE ? OR a.name LIKE ?)";$like='%'.$q.'%';$params=[$like,$like,$like,$like];}$sql.=' ORDER BY s.priority DESC,s.updated_at DESC';$stmt=$this->db->prepare($sql);$stmt->execute($params);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
 public function save(array$d,int$userId):int{$from=(int)($d['material_id']??0);$to=(int)($d['substitute_material_id']??0);$type=(string)($d['substitution_type']??'direct');if(!$from||!$to||$from===$to)throw new RuntimeException('主物料与替代物料必须不同。');if(!in_array($type,['direct','conditional','temporary','discontinued'],true))throw new RuntimeException('替代类型无效。');$this->assertMaterial($from);$this->assertMaterial($to);if($this->wouldCycle($from,$to))throw new RuntimeException('替代关系会形成死循环。');$this->db->beginTransaction();try{$stmt=$this->db->prepare("INSERT INTO mc_material_substitutions(material_id,substitute_material_id,substitution_type,condition_json,priority,effective_from,effective_to,status,created_by,created_at,updated_at)VALUES(?,?,?,?,?,?,?,'draft',?,NOW(),NOW()) ON DUPLICATE KEY UPDATE condition_json=VALUES(condition_json),priority=VALUES(priority),effective_from=VALUES(effective_from),effective_to=VALUES(effective_to),updated_at=NOW()");$stmt->execute([$from,$to,$type,$this->json($d['conditions']??[]),(int)($d['priority']??0),$this->nullable($d['effective_from']??''),$this->nullable($d['effective_to']??''),$userId]);$find=$this->db->prepare('SELECT id FROM mc_material_substitutions WHERE material_id=? AND substitute_material_id=? AND substitution_type=?');$find->execute([$from,$to,$type]);$id=(int)$find->fetchColumn();$this->version($from,'substitution_created',['substitution_id'=>$id],$userId);$this->log($id,'save',$d,$userId);$this->db->commit();return$id;}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 public function approve(int$id,int$userId):void{$this->db->beginTransaction();try{$stmt=$this->db->prepare('SELECT material_id,substitute_material_id FROM mc_material_substitutions WHERE id=? FOR UPDATE');$stmt->execute([$id]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row)throw new RuntimeException('替代关系不存在。');if($this->wouldCycle((int)$row['material_id'],(int)$row['substitute_material_id'],$id))throw new RuntimeException('替代关系存在死循环。');$this->db->prepare("UPDATE mc_material_substitutions SET status='approved',updated_at=NOW() WHERE id=?")->execute([$id]);$this->version((int)$row['material_id'],'substitution_approved',['substitution_id'=>$id],$userId);$this->log($id,'approve',[],$userId);$this->db->commit();}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 public function impact(int$materialId):array{return(new MaterialMasterService($this->db))->references($materialId);}
 public function migrateReferences(int$from,int$to,int$userId):array{$this->assertMaterial($from);$this->assertMaterial($to);$uuid=$this->uuid();$tables=['mc_adaptation_options','mc_supplier_materials','mc_product_power_approved_alternatives'];$scope=[];$preview=[];foreach($tables as$table){$stmt=$this->db->prepare("SELECT id FROM `$table` WHERE material_id=?");$stmt->execute([$from]);$scope[$table]=array_map('intval',$stmt->fetchAll(PDO::FETCH_COLUMN));$preview[$table]=count($scope[$table]);}$this->db->beginTransaction();try{$this->db->prepare("INSERT INTO mc_reference_migrations(migration_uuid,from_material_id,to_material_id,scope_json,preview_json,status,created_by,created_at)VALUES(?,?,?,?,?,'running',?,NOW())")->execute([$uuid,$from,$to,json_encode($scope),json_encode($preview),$userId]);$result=[];foreach($scope as$table=>$ids){if(!$ids){$result[$table]=0;continue;}$marks=implode(',',array_fill(0,count($ids),'?'));$stmt=$this->db->prepare("UPDATE `$table` SET material_id=? WHERE material_id=? AND id IN($marks)");$stmt->execute(array_merge([$to,$from],$ids));$result[$table]=$stmt->rowCount();}$this->db->prepare("UPDATE mc_reference_migrations SET result_json=?,status='completed',executed_at=NOW() WHERE migration_uuid=?")->execute([json_encode($result),$uuid]);$this->version($from,'references_migrated',['to'=>$to,'uuid'=>$uuid,'result'=>$result],$userId);$this->db->commit();return['migration_uuid'=>$uuid,'preview'=>$preview,'result'=>$result];}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 public function rollbackMigration(string$uuid,int$userId):array{$this->db->beginTransaction();try{$stmt=$this->db->prepare("SELECT * FROM mc_reference_migrations WHERE migration_uuid=? AND status='completed' FOR UPDATE");$stmt->execute([$uuid]);$m=$stmt->fetch(PDO::FETCH_ASSOC);if(!$m)throw new RuntimeException('可回滚迁移不存在。');$scope=json_decode((string)$m['scope_json'],true)?:[];$result=[];foreach($scope as$table=>$ids){if(!in_array($table,['mc_adaptation_options','mc_supplier_materials','mc_product_power_approved_alternatives'],true)||!is_array($ids)||!$ids){$result[$table]=0;continue;}$ids=array_map('intval',$ids);$marks=implode(',',array_fill(0,count($ids),'?'));$stmt=$this->db->prepare("UPDATE `$table` SET material_id=? WHERE material_id=? AND id IN($marks)");$stmt->execute(array_merge([(int)$m['from_material_id'],(int)$m['to_material_id']],$ids));$result[$table]=$stmt->rowCount();}$this->db->prepare("UPDATE mc_reference_migrations SET status='rolled_back',rolled_back_at=NOW() WHERE id=?")->execute([$m['id']]);$this->version((int)$m['from_material_id'],'references_rollback',['uuid'=>$uuid,'result'=>$result],$userId);$this->db->commit();return$result;}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 public function versions(int$materialId):array{$stmt=$this->db->prepare('SELECT * FROM mc_material_versions WHERE material_id=? ORDER BY version_no DESC');$stmt->execute([$materialId]);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
 private function version(int$materialId,string$note,array$extra,int$userId):void{$stmt=$this->db->prepare('SELECT m.*,md.spec_summary,md.lock_version FROM mc_materials m LEFT JOIN mc_material_metadata md ON md.material_id=m.id WHERE m.id=?');$stmt->execute([$materialId]);$snapshot=$stmt->fetch(PDO::FETCH_ASSOC);if(!$snapshot)return;$snapshot['_change']=$extra;$next=$this->db->prepare('SELECT COALESCE(MAX(version_no),0)+1 FROM mc_material_versions WHERE material_id=?');$next->execute([$materialId]);$this->db->prepare('INSERT INTO mc_material_versions(material_id,version_no,snapshot_json,change_note,created_by,created_at)VALUES(?,?,?,?,?,NOW())')->execute([$materialId,(int)$next->fetchColumn(),json_encode($snapshot,JSON_UNESCAPED_UNICODE),$note,$userId]);}
 private function wouldCycle(int$from,int$to,int$ignore=0):bool{$seen=[];$stack=[$to];while($stack){$node=array_pop($stack);if($node===$from)return true;if(isset($seen[$node]))continue;$seen[$node]=true;$sql="SELECT substitute_material_id FROM mc_material_substitutions WHERE material_id=? AND status IN('draft','approved')";$params=[$node];if($ignore){$sql.=' AND id<>?';$params[]=$ignore;}$stmt=$this->db->prepare($sql);$stmt->execute($params);foreach($stmt->fetchAll(PDO::FETCH_COLUMN)as$next)$stack[]=(int)$next;}return false;}
 private function assertMaterial(int$id):void{$stmt=$this->db->prepare('SELECT 1 FROM mc_materials WHERE id=? AND deleted_at IS NULL');$stmt->execute([$id]);if(!$stmt->fetchColumn())throw new RuntimeException('物料不存在。');}
 private function log(int$id,string$action,array$data,int$user):void{$this->db->prepare("INSERT INTO mc_operation_logs(module,object_type,object_id,action,new_value_json,actor_id,actor_ip,result,created_at)VALUES('material_center','substitution',?,?,?,?,?,'success',NOW())")->execute([$id,$action,json_encode($data,JSON_UNESCAPED_UNICODE),$user,(string)($_SERVER['REMOTE_ADDR']??'cli')]);}
 private function json(mixed$v):string{return is_string($v)?$v:json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);}
 private function nullable(mixed$v):?string{$v=trim((string)$v);return$v===''?null:$v;}
 private function uuid():string{$d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4));}
}
