<?php
declare(strict_types=1);
namespace Artdon\MaterialCenter\Services;

use PDO;
use RuntimeException;

final class SupplierService
{
 private const DOCUMENT_EXTENSIONS=['pdf','png','jpg','jpeg','webp','doc','docx','xls','xlsx','csv','zip'];
 public function __construct(private ?PDO$db=null){$this->db??=\db();}
 public function suppliers():array{return$this->db->query("SELECT s.*,p.default_currency,p.payment_terms,p.quality_grade,p.tax_rate,(SELECT COUNT(*) FROM mc_supplier_materials sm WHERE sm.supplier_id=s.id AND sm.status='active') material_count,(SELECT name FROM mc_supplier_contacts c WHERE c.supplier_id=s.id AND c.status='active' ORDER BY c.is_primary DESC,c.id LIMIT 1) contact_name,(SELECT phone FROM mc_supplier_contacts c WHERE c.supplier_id=s.id AND c.status='active' ORDER BY c.is_primary DESC,c.id LIMIT 1) contact_phone FROM mc_suppliers s LEFT JOIN mc_supplier_profiles p ON p.supplier_id=s.id WHERE s.deleted_at IS NULL ORDER BY s.updated_at DESC,s.id DESC")->fetchAll(PDO::FETCH_ASSOC);}
 public function materials(int$supplierId):array{$stmt=$this->db->prepare("SELECT sm.*,m.material_code,m.name material_name,m.brand,m.model,p.purchase_price,p.currency,p.valid_from,p.valid_to,(SELECT lead_time_days FROM mc_supplier_lead_times l WHERE l.supplier_material_id=sm.id AND l.status='active' ORDER BY id DESC LIMIT 1) current_lead_time,(SELECT moq FROM mc_supplier_moq q WHERE q.supplier_material_id=sm.id AND q.status='active' ORDER BY id DESC LIMIT 1) current_moq FROM mc_supplier_materials sm JOIN mc_materials m ON m.id=sm.material_id LEFT JOIN mc_supplier_prices p ON p.id=(SELECT id FROM mc_supplier_prices x WHERE x.supplier_material_id=sm.id AND x.approval_status='approved' ORDER BY COALESCE(valid_from,'1000-01-01') DESC,id DESC LIMIT 1) WHERE sm.supplier_id=? AND sm.status='active' ORDER BY sm.is_preferred DESC,m.name");$stmt->execute([$supplierId]);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
 public function pendingPrices():array{return$this->db->query("SELECT p.id,p.purchase_price,p.currency,p.created_at,s.name supplier_name,m.material_code,m.name material_name FROM mc_supplier_prices p JOIN mc_supplier_materials sm ON sm.id=p.supplier_material_id JOIN mc_suppliers s ON s.id=sm.supplier_id JOIN mc_materials m ON m.id=sm.material_id WHERE p.approval_status='pending' ORDER BY p.created_at,p.id")->fetchAll(PDO::FETCH_ASSOC);}
 public function documents(int$supplierId):array{$stmt=$this->db->prepare('SELECT * FROM mc_supplier_documents WHERE supplier_id=? AND deleted_at IS NULL ORDER BY created_at DESC,id DESC');$stmt->execute([$supplierId]);return$stmt->fetchAll(PDO::FETCH_ASSOC);}
 public function document(int$id):array{$stmt=$this->db->prepare('SELECT * FROM mc_supplier_documents WHERE id=? AND deleted_at IS NULL');$stmt->execute([$id]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row||!is_file($row['file_path']))throw new RuntimeException('供应商附件不存在。',404);return$row;}
 public function uploadDocument(array$file,array$d,int$userId):int{
  $supplierId=(int)($d['supplier_id']??0);$check=$this->db->prepare('SELECT 1 FROM mc_suppliers WHERE id=? AND deleted_at IS NULL');$check->execute([$supplierId]);if(!$check->fetchColumn())throw new RuntimeException('供应商不存在。');if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('附件上传失败。');$size=(int)($file['size']??0);if($size<1||$size>25*1024*1024)throw new RuntimeException('附件必须小于 25MB。');$name=basename((string)($file['name']??''));$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));if(!in_array($ext,self::DOCUMENT_EXTENSIONS,true))throw new RuntimeException('不允许的附件类型。');$tmp=(string)$file['tmp_name'];$mime=$this->documentMime($tmp,$ext);$this->assertDocumentMime($ext,$mime,$tmp);$dir=MC_ROOT.'/storage/suppliers/'.date('Y/m');if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('供应商附件目录不可写。');$path=$dir.'/'.bin2hex(random_bytes(16)).'.'.$ext;if(!move_uploaded_file($tmp,$path)&&!rename($tmp,$path))throw new RuntimeException('附件保存失败。');chmod($path,0640);$sha=hash_file('sha256',$path);
  $this->db->beginTransaction();try{$type=trim((string)($d['document_type']??'attachment'))?:'attachment';$this->db->prepare("INSERT INTO mc_supplier_documents(supplier_id,document_type,file_name,file_path,mime_type,file_size,sha256,version_no,access_level,created_by,created_at)VALUES(?,?,?,?,?,?,?,1,'purchasing',?,NOW())")->execute([$supplierId,$type,$name,$path,$mime,$size,$sha,$userId]);$id=(int)$this->db->lastInsertId();$this->log('supplier_document',$id,'upload',['supplier_id'=>$supplierId,'sha256'=>$sha],$userId);$this->db->commit();return$id;}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();@unlink($path);throw$e;}
 }
 public function saveSupplier(array$d,int$userId):int{
  $name=trim((string)($d['name']??''));if($name==='')throw new RuntimeException('供应商名称不能为空。');
  $currency=strtoupper(trim((string)($d['default_currency']??'CNY')));if(!preg_match('/^[A-Z]{3}$/',$currency))throw new RuntimeException('币种无效。');
  $id=(int)($d['id']??0);$this->db->beginTransaction();try{
   if($id){$stmt=$this->db->prepare('UPDATE mc_suppliers SET name=?,status=?,updated_at=NOW() WHERE id=? AND deleted_at IS NULL');$stmt->execute([$name,$d['status']??'active',$id]);if(!$stmt->rowCount())throw new RuntimeException('供应商不存在。');}
   else{$code=trim((string)($d['supplier_code']??''));if($code==='')$code='SUP-'.date('ymd').'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,6));$stmt=$this->db->prepare('INSERT INTO mc_suppliers(supplier_code,name,status,created_at,updated_at)VALUES(?,?,?,NOW(),NOW())');$stmt->execute([$code,$name,$d['status']??'active']);$id=(int)$this->db->lastInsertId();}
   $taxRate=$d['tax_rate']??'';$this->db->prepare("INSERT INTO mc_supplier_profiles(supplier_id,default_currency,payment_terms,quality_grade,tax_rate,notes,created_at,updated_at)VALUES(?,?,?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE default_currency=VALUES(default_currency),payment_terms=VALUES(payment_terms),quality_grade=VALUES(quality_grade),tax_rate=VALUES(tax_rate),notes=VALUES(notes),updated_at=NOW()")->execute([$id,$currency,$this->nullable($d['payment_terms']??''),$this->nullable($d['quality_grade']??''),$taxRate!==''?(float)$taxRate:null,$this->nullable($d['notes']??'')]);
   if(trim((string)($d['contact_name']??''))!=='')$this->db->prepare("INSERT INTO mc_supplier_contacts(supplier_id,name,position,phone,email,is_primary,status,created_at,updated_at)VALUES(?,?,?,?,?,1,'active',NOW(),NOW())")->execute([$id,trim((string)$d['contact_name']),$this->nullable($d['contact_position']??''),$this->nullable($d['contact_phone']??''),$this->nullable($d['contact_email']??'')]);
   $this->log('supplier',$id,$id?'save':'create',$d,$userId);$this->db->commit();return$id;
  }catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}
 }
 public function savePrice(array$d,int$userId):int{
  $supplierId=(int)($d['supplier_id']??0);$materialId=(int)($d['material_id']??0);$price=(float)($d['purchase_price']??-1);$currency=strtoupper(trim((string)($d['currency']??'CNY')));if(!$supplierId||!$materialId||$price<0||!preg_match('/^[A-Z]{3}$/',$currency))throw new RuntimeException('供应商、物料、价格或币种无效。');
  $this->db->beginTransaction();try{
   $supplierModel=trim((string)($d['supplier_model']??''));$moq=$d['moq']??'';$lead=$d['lead_time_days']??'';$stmt=$this->db->prepare("INSERT INTO mc_supplier_materials(supplier_id,material_id,supplier_model,supplier_material_code,moq,lead_time_days,status)VALUES(?,?,?,?,?,?,'active') ON DUPLICATE KEY UPDATE supplier_material_code=VALUES(supplier_material_code),moq=VALUES(moq),lead_time_days=VALUES(lead_time_days),status='active'");$stmt->execute([$supplierId,$materialId,$supplierModel,$this->nullable($d['supplier_material_code']??''),$moq!==''?(float)$moq:null,$lead!==''?(int)$lead:null]);
   $find=$this->db->prepare('SELECT id FROM mc_supplier_materials WHERE supplier_id=? AND material_id=? AND supplier_model=? LIMIT 1');$find->execute([$supplierId,$materialId,$supplierModel]);$sm=(int)$find->fetchColumn();
   $old=$this->db->prepare('SELECT id,purchase_price FROM mc_supplier_prices WHERE supplier_material_id=? ORDER BY id DESC LIMIT 1');$old->execute([$sm]);$oldRow=$old->fetch(PDO::FETCH_ASSOC);
   $this->db->prepare("INSERT INTO mc_approvals(approval_type,entity_type,entity_id,status,requested_by,requested_at,current_step,request_json)VALUES('supplier_price','supplier_price',0,'pending',?,NOW(),1,?)")->execute([$userId,json_encode(['supplier_material_id'=>$sm,'price'=>$price,'currency'=>$currency],JSON_UNESCAPED_UNICODE)]);$approvalId=(int)$this->db->lastInsertId();
   $stmt=$this->db->prepare("INSERT INTO mc_supplier_prices(supplier_material_id,purchase_price,currency,valid_from,valid_to,approval_status,approval_id,created_at)VALUES(?,?,?,?,?,'pending',?,NOW())");$stmt->execute([$sm,$price,$currency,$this->nullable($d['valid_from']??''),$this->nullable($d['valid_to']??''),$approvalId]);$priceId=(int)$this->db->lastInsertId();$this->db->prepare('UPDATE mc_approvals SET entity_id=? WHERE id=?')->execute([$priceId,$approvalId]);
   $taxRate=$d['tax_rate']??'';$this->db->prepare('INSERT INTO mc_supplier_price_history(supplier_price_id,old_price,new_price,currency,tax_included,tax_rate,effective_at,changed_by,approval_id,created_at)VALUES(?,?,?,?,?,?,NOW(),?,?,NOW())')->execute([$priceId,$oldRow['purchase_price']??null,$price,$currency,!empty($d['tax_included'])?1:0,$taxRate!==''?(float)$taxRate:null,$userId,$approvalId]);
   $packageQty=$d['package_qty']??'';if($moq!=='')$this->db->prepare("INSERT INTO mc_supplier_moq(supplier_material_id,moq,package_qty,effective_from,status)VALUES(?,?,?,?,'active')")->execute([$sm,(float)$moq,$packageQty!==''?(float)$packageQty:null,$this->nullable($d['valid_from']??'')]);
   if($lead!=='')$this->db->prepare("INSERT INTO mc_supplier_lead_times(supplier_material_id,lead_time_days,condition_text,effective_from,status)VALUES(?,?,?,?,'active')")->execute([$sm,(int)$lead,$this->nullable($d['lead_time_condition']??''),$this->nullable($d['valid_from']??'')]);
   foreach((array)($d['tiers']??[])as$tier){$min=(float)($tier['min_qty']??0);$tierPrice=(float)($tier['unit_price']??-1);if($min>0&&$tierPrice>=0)$this->db->prepare('INSERT INTO mc_supplier_price_tiers(supplier_price_id,min_qty,max_qty,unit_price)VALUES(?,?,?,?)')->execute([$priceId,$min,isset($tier['max_qty'])&&$tier['max_qty']!==''?(float)$tier['max_qty']:null,$tierPrice]);}
   if(!empty($d['is_preferred'])){$this->db->prepare('UPDATE mc_supplier_materials SET is_preferred=0 WHERE material_id=?')->execute([$materialId]);$this->db->prepare('UPDATE mc_supplier_materials SET is_preferred=1 WHERE id=?')->execute([$sm]);}
   $this->log('supplier_price',$priceId,'request_price_approval',['supplier_material_id'=>$sm,'price'=>$price,'currency'=>$currency,'approval_id'=>$approvalId],$userId);$this->db->commit();return$priceId;
  }catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}
 }
 public function approvePrice(int$priceId,int$userId,string$decision,string$comment=''):void{if(!in_array($decision,['approve','reject'],true))throw new RuntimeException('审批决定无效。');$this->db->beginTransaction();try{$stmt=$this->db->prepare("SELECT approval_id,approval_status FROM mc_supplier_prices WHERE id=? FOR UPDATE");$stmt->execute([$priceId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row||$row['approval_status']!=='pending')throw new RuntimeException('价格审批不存在或已处理。');$status=$decision==='approve'?'approved':'rejected';$this->db->prepare('UPDATE mc_supplier_prices SET approval_status=? WHERE id=?')->execute([$status,$priceId]);$this->db->prepare('UPDATE mc_approvals SET status=?,completed_at=NOW() WHERE id=?')->execute([$status,$row['approval_id']]);$this->db->prepare('INSERT INTO mc_approval_logs(approval_id,action,actor_id,detail_json,created_at)VALUES(?,?,?,?,NOW())')->execute([$row['approval_id'],$decision,$userId,json_encode(['comment'=>$comment],JSON_UNESCAPED_UNICODE)]);$this->log('supplier_price',$priceId,$decision.'_price',['comment'=>$comment],$userId);$this->db->commit();}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 private function log(string$type,int$id,string$action,array$data,int$user):void{$this->db->prepare("INSERT INTO mc_operation_logs(module,object_type,object_id,action,new_value_json,actor_id,actor_ip,result,created_at)VALUES('material_center',?,?,?,?,?,?, 'success',NOW())")->execute([$type,$id,$action,json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$user,(string)($_SERVER['REMOTE_ADDR']??'cli')]);}
 private function documentMime(string$path,string$ext):string{if(function_exists('finfo_open')){$f=finfo_open(FILEINFO_MIME_TYPE);if($f){$mime=finfo_file($f,$path);finfo_close($f);if(is_string($mime)&&$mime!=='')return$mime;}}if(function_exists('mime_content_type')){$mime=mime_content_type($path);if(is_string($mime)&&$mime!=='')return$mime;}return match($ext){'pdf'=>'application/pdf','png'=>'image/png','jpg','jpeg'=>'image/jpeg','webp'=>'image/webp','csv'=>'text/csv','zip','docx','xlsx'=>'application/zip','doc'=>'application/msword','xls'=>'application/vnd.ms-excel',default=>'application/octet-stream'};}
 private function assertDocumentMime(string$ext,string$mime,string$path):void{$allowed=match($ext){'pdf'=>['application/pdf'],'png'=>['image/png'],'jpg','jpeg'=>['image/jpeg'],'webp'=>['image/webp'],'csv'=>['text/plain','text/csv','application/csv','application/octet-stream'],'zip','docx','xlsx'=>['application/zip','application/x-zip','application/x-zip-compressed','application/octet-stream'],'doc'=>['application/msword','application/octet-stream'],'xls'=>['application/vnd.ms-excel','application/octet-stream'],default=>[]};if(!in_array($mime,$allowed,true))throw new RuntimeException('附件扩展名与内容类型不一致。');$head=(string)file_get_contents($path,false,null,0,8);if($ext==='pdf'&&!str_starts_with($head,'%PDF-'))throw new RuntimeException('PDF 文件签名无效。');if(in_array($ext,['zip','docx','xlsx'],true)&&!str_starts_with($head,'PK'))throw new RuntimeException('压缩附件签名无效。');}
 private function nullable(mixed$v):?string{$v=trim((string)$v);return$v===''?null:$v;}
}
