<?php

// Generated from Unicode CLDR 48 ISO territory mappings/names and Google libphonenumber E.164 metadata.
// The list intentionally contains the 249 currently assigned ISO 3166-1 alpha-2 entries.
return [
    ['IN','印度','India','IN','#dc2626','IN',['iso'=>'IN','iso3'=>'IND','numeric'=>'356','phone_code'=>'+91','region'=>'Asia','pinned'=>1],0],
    ['KR','韩国','South Korea','KR','#dc2626','KR',['iso'=>'KR','iso3'=>'KOR','numeric'=>'410','phone_code'=>'+82','region'=>'Asia','pinned'=>1],0],
    ['AE','阿拉伯联合酋长国','United Arab Emirates','AE','#dc2626','AE',['iso'=>'AE','iso3'=>'ARE','numeric'=>'784','phone_code'=>'+971','region'=>'Asia','pinned'=>1],0],
    ['SA','沙特阿拉伯','Saudi Arabia','SA','#dc2626','SA',['iso'=>'SA','iso3'=>'SAU','numeric'=>'682','phone_code'=>'+966','region'=>'Asia','pinned'=>1],0],
    ['DE','德国','Germany','DE','#2563eb','DE',['iso'=>'DE','iso3'=>'DEU','numeric'=>'276','phone_code'=>'+49','region'=>'Europe','pinned'=>1],0],
    ['US','美国','United States','US','#f59e0b','US',['iso'=>'US','iso3'=>'USA','numeric'=>'840','phone_code'=>'+1','region'=>'Americas','pinned'=>1],0],
    ['GB','英国','United Kingdom','GB','#2563eb','GB',['iso'=>'GB','iso3'=>'GBR','numeric'=>'826','phone_code'=>'+44','region'=>'Europe','pinned'=>1],0],
    ['CN','中国','China','CN','#dc2626','CN',['iso'=>'CN','iso3'=>'CHN','numeric'=>'156','phone_code'=>'+86','region'=>'Asia','pinned'=>1],0],
    ['HK','中国香港特别行政区','Hong Kong SAR China','HK','#dc2626','HK',['iso'=>'HK','iso3'=>'HKG','numeric'=>'344','phone_code'=>'+852','region'=>'Asia','pinned'=>1],0],
    ['SG','新加坡','Singapore','SG','#dc2626','SG',['iso'=>'SG','iso3'=>'SGP','numeric'=>'702','phone_code'=>'+65','region'=>'Asia','pinned'=>1],0],
    ['TR','土耳其','Türkiye','TR','#dc2626','TR',['iso'=>'TR','iso3'=>'TUR','numeric'=>'792','phone_code'=>'+90','region'=>'Asia','pinned'=>1],0],
    ['AD','安道尔','Andorra','AD','#2563eb','AD',['iso'=>'AD','iso3'=>'AND','numeric'=>'020','phone_code'=>'+376','region'=>'Europe','pinned'=>0],0],
    ['AF','阿富汗','Afghanistan','AF','#dc2626','AF',['iso'=>'AF','iso3'=>'AFG','numeric'=>'004','phone_code'=>'+93','region'=>'Asia','pinned'=>0],0],
    ['AG','安提瓜和巴布达','Antigua & Barbuda','AG','#f59e0b','AG',['iso'=>'AG','iso3'=>'ATG','numeric'=>'028','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['AI','安圭拉','Anguilla','AI','#f59e0b','AI',['iso'=>'AI','iso3'=>'AIA','numeric'=>'660','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['AL','阿尔巴尼亚','Albania','AL','#2563eb','AL',['iso'=>'AL','iso3'=>'ALB','numeric'=>'008','phone_code'=>'+355','region'=>'Europe','pinned'=>0],0],
    ['AM','亚美尼亚','Armenia','AM','#dc2626','AM',['iso'=>'AM','iso3'=>'ARM','numeric'=>'051','phone_code'=>'+374','region'=>'Asia','pinned'=>0],0],
    ['AO','安哥拉','Angola','AO','#16a34a','AO',['iso'=>'AO','iso3'=>'AGO','numeric'=>'024','phone_code'=>'+244','region'=>'Africa','pinned'=>0],0],
    ['AQ','南极洲','Antarctica','AQ','#0ea5e9','AQ',['iso'=>'AQ','iso3'=>'ATA','numeric'=>'010','phone_code'=>'+672','region'=>'Oceania','pinned'=>0],0],
    ['AR','阿根廷','Argentina','AR','#f59e0b','AR',['iso'=>'AR','iso3'=>'ARG','numeric'=>'032','phone_code'=>'+54','region'=>'Americas','pinned'=>0],0],
    ['AS','美属萨摩亚','American Samoa','AS','#0ea5e9','AS',['iso'=>'AS','iso3'=>'ASM','numeric'=>'016','phone_code'=>'+1','region'=>'Oceania','pinned'=>0],0],
    ['AT','奥地利','Austria','AT','#2563eb','AT',['iso'=>'AT','iso3'=>'AUT','numeric'=>'040','phone_code'=>'+43','region'=>'Europe','pinned'=>0],0],
    ['AU','澳大利亚','Australia','AU','#0ea5e9','AU',['iso'=>'AU','iso3'=>'AUS','numeric'=>'036','phone_code'=>'+61','region'=>'Oceania','pinned'=>0],0],
    ['AW','阿鲁巴','Aruba','AW','#f59e0b','AW',['iso'=>'AW','iso3'=>'ABW','numeric'=>'533','phone_code'=>'+297','region'=>'Americas','pinned'=>0],0],
    ['AX','奥兰群岛','Åland Islands','AX','#2563eb','AX',['iso'=>'AX','iso3'=>'ALA','numeric'=>'248','phone_code'=>'+358','region'=>'Europe','pinned'=>0],0],
    ['AZ','阿塞拜疆','Azerbaijan','AZ','#dc2626','AZ',['iso'=>'AZ','iso3'=>'AZE','numeric'=>'031','phone_code'=>'+994','region'=>'Asia','pinned'=>0],0],
    ['BA','波斯尼亚和黑塞哥维那','Bosnia & Herzegovina','BA','#2563eb','BA',['iso'=>'BA','iso3'=>'BIH','numeric'=>'070','phone_code'=>'+387','region'=>'Europe','pinned'=>0],0],
    ['BB','巴巴多斯','Barbados','BB','#f59e0b','BB',['iso'=>'BB','iso3'=>'BRB','numeric'=>'052','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['BD','孟加拉国','Bangladesh','BD','#dc2626','BD',['iso'=>'BD','iso3'=>'BGD','numeric'=>'050','phone_code'=>'+880','region'=>'Asia','pinned'=>0],0],
    ['BE','比利时','Belgium','BE','#2563eb','BE',['iso'=>'BE','iso3'=>'BEL','numeric'=>'056','phone_code'=>'+32','region'=>'Europe','pinned'=>0],0],
    ['BF','布基纳法索','Burkina Faso','BF','#16a34a','BF',['iso'=>'BF','iso3'=>'BFA','numeric'=>'854','phone_code'=>'+226','region'=>'Africa','pinned'=>0],0],
    ['BG','保加利亚','Bulgaria','BG','#2563eb','BG',['iso'=>'BG','iso3'=>'BGR','numeric'=>'100','phone_code'=>'+359','region'=>'Europe','pinned'=>0],0],
    ['BH','巴林','Bahrain','BH','#dc2626','BH',['iso'=>'BH','iso3'=>'BHR','numeric'=>'048','phone_code'=>'+973','region'=>'Asia','pinned'=>0],0],
    ['BI','布隆迪','Burundi','BI','#16a34a','BI',['iso'=>'BI','iso3'=>'BDI','numeric'=>'108','phone_code'=>'+257','region'=>'Africa','pinned'=>0],0],
    ['BJ','贝宁','Benin','BJ','#16a34a','BJ',['iso'=>'BJ','iso3'=>'BEN','numeric'=>'204','phone_code'=>'+229','region'=>'Africa','pinned'=>0],0],
    ['BL','圣巴泰勒米','St. Barthélemy','BL','#f59e0b','BL',['iso'=>'BL','iso3'=>'BLM','numeric'=>'652','phone_code'=>'+590','region'=>'Americas','pinned'=>0],0],
    ['BM','百慕大','Bermuda','BM','#f59e0b','BM',['iso'=>'BM','iso3'=>'BMU','numeric'=>'060','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['BN','文莱','Brunei','BN','#dc2626','BN',['iso'=>'BN','iso3'=>'BRN','numeric'=>'096','phone_code'=>'+673','region'=>'Asia','pinned'=>0],0],
    ['BO','玻利维亚','Bolivia','BO','#f59e0b','BO',['iso'=>'BO','iso3'=>'BOL','numeric'=>'068','phone_code'=>'+591','region'=>'Americas','pinned'=>0],0],
    ['BQ','荷属加勒比区','Caribbean Netherlands','BQ','#f59e0b','BQ',['iso'=>'BQ','iso3'=>'BES','numeric'=>'535','phone_code'=>'+599','region'=>'Americas','pinned'=>0],0],
    ['BR','巴西','Brazil','BR','#f59e0b','BR',['iso'=>'BR','iso3'=>'BRA','numeric'=>'076','phone_code'=>'+55','region'=>'Americas','pinned'=>0],0],
    ['BS','巴哈马','Bahamas','BS','#f59e0b','BS',['iso'=>'BS','iso3'=>'BHS','numeric'=>'044','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['BT','不丹','Bhutan','BT','#dc2626','BT',['iso'=>'BT','iso3'=>'BTN','numeric'=>'064','phone_code'=>'+975','region'=>'Asia','pinned'=>0],0],
    ['BV','布韦岛','Bouvet Island','BV','#f59e0b','BV',['iso'=>'BV','iso3'=>'BVT','numeric'=>'074','phone_code'=>'+47','region'=>'Americas','pinned'=>0],0],
    ['BW','博茨瓦纳','Botswana','BW','#16a34a','BW',['iso'=>'BW','iso3'=>'BWA','numeric'=>'072','phone_code'=>'+267','region'=>'Africa','pinned'=>0],0],
    ['BY','白俄罗斯','Belarus','BY','#2563eb','BY',['iso'=>'BY','iso3'=>'BLR','numeric'=>'112','phone_code'=>'+375','region'=>'Europe','pinned'=>0],0],
    ['BZ','伯利兹','Belize','BZ','#f59e0b','BZ',['iso'=>'BZ','iso3'=>'BLZ','numeric'=>'084','phone_code'=>'+501','region'=>'Americas','pinned'=>0],0],
    ['CA','加拿大','Canada','CA','#f59e0b','CA',['iso'=>'CA','iso3'=>'CAN','numeric'=>'124','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['CC','科科斯（基林）群岛','Cocos (Keeling) Islands','CC','#0ea5e9','CC',['iso'=>'CC','iso3'=>'CCK','numeric'=>'166','phone_code'=>'+61','region'=>'Oceania','pinned'=>0],0],
    ['CD','刚果（金）','Congo - Kinshasa','CD','#16a34a','CD',['iso'=>'CD','iso3'=>'COD','numeric'=>'180','phone_code'=>'+243','region'=>'Africa','pinned'=>0],0],
    ['CF','中非共和国','Central African Republic','CF','#16a34a','CF',['iso'=>'CF','iso3'=>'CAF','numeric'=>'140','phone_code'=>'+236','region'=>'Africa','pinned'=>0],0],
    ['CG','刚果（布）','Congo - Brazzaville','CG','#16a34a','CG',['iso'=>'CG','iso3'=>'COG','numeric'=>'178','phone_code'=>'+242','region'=>'Africa','pinned'=>0],0],
    ['CH','瑞士','Switzerland','CH','#2563eb','CH',['iso'=>'CH','iso3'=>'CHE','numeric'=>'756','phone_code'=>'+41','region'=>'Europe','pinned'=>0],0],
    ['CI','科特迪瓦','Côte d’Ivoire','CI','#16a34a','CI',['iso'=>'CI','iso3'=>'CIV','numeric'=>'384','phone_code'=>'+225','region'=>'Africa','pinned'=>0],0],
    ['CK','库克群岛','Cook Islands','CK','#0ea5e9','CK',['iso'=>'CK','iso3'=>'COK','numeric'=>'184','phone_code'=>'+682','region'=>'Oceania','pinned'=>0],0],
    ['CL','智利','Chile','CL','#f59e0b','CL',['iso'=>'CL','iso3'=>'CHL','numeric'=>'152','phone_code'=>'+56','region'=>'Americas','pinned'=>0],0],
    ['CM','喀麦隆','Cameroon','CM','#16a34a','CM',['iso'=>'CM','iso3'=>'CMR','numeric'=>'120','phone_code'=>'+237','region'=>'Africa','pinned'=>0],0],
    ['CO','哥伦比亚','Colombia','CO','#f59e0b','CO',['iso'=>'CO','iso3'=>'COL','numeric'=>'170','phone_code'=>'+57','region'=>'Americas','pinned'=>0],0],
    ['CR','哥斯达黎加','Costa Rica','CR','#f59e0b','CR',['iso'=>'CR','iso3'=>'CRI','numeric'=>'188','phone_code'=>'+506','region'=>'Americas','pinned'=>0],0],
    ['CU','古巴','Cuba','CU','#f59e0b','CU',['iso'=>'CU','iso3'=>'CUB','numeric'=>'192','phone_code'=>'+53','region'=>'Americas','pinned'=>0],0],
    ['CV','佛得角','Cape Verde','CV','#16a34a','CV',['iso'=>'CV','iso3'=>'CPV','numeric'=>'132','phone_code'=>'+238','region'=>'Africa','pinned'=>0],0],
    ['CW','库拉索','Curaçao','CW','#f59e0b','CW',['iso'=>'CW','iso3'=>'CUW','numeric'=>'531','phone_code'=>'+599','region'=>'Americas','pinned'=>0],0],
    ['CX','圣诞岛','Christmas Island','CX','#0ea5e9','CX',['iso'=>'CX','iso3'=>'CXR','numeric'=>'162','phone_code'=>'+61','region'=>'Oceania','pinned'=>0],0],
    ['CY','塞浦路斯','Cyprus','CY','#dc2626','CY',['iso'=>'CY','iso3'=>'CYP','numeric'=>'196','phone_code'=>'+357','region'=>'Asia','pinned'=>0],0],
    ['CZ','捷克','Czechia','CZ','#2563eb','CZ',['iso'=>'CZ','iso3'=>'CZE','numeric'=>'203','phone_code'=>'+420','region'=>'Europe','pinned'=>0],0],
    ['DJ','吉布提','Djibouti','DJ','#16a34a','DJ',['iso'=>'DJ','iso3'=>'DJI','numeric'=>'262','phone_code'=>'+253','region'=>'Africa','pinned'=>0],0],
    ['DK','丹麦','Denmark','DK','#2563eb','DK',['iso'=>'DK','iso3'=>'DNK','numeric'=>'208','phone_code'=>'+45','region'=>'Europe','pinned'=>0],0],
    ['DM','多米尼克','Dominica','DM','#f59e0b','DM',['iso'=>'DM','iso3'=>'DMA','numeric'=>'212','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['DO','多米尼加共和国','Dominican Republic','DO','#f59e0b','DO',['iso'=>'DO','iso3'=>'DOM','numeric'=>'214','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['DZ','阿尔及利亚','Algeria','DZ','#16a34a','DZ',['iso'=>'DZ','iso3'=>'DZA','numeric'=>'012','phone_code'=>'+213','region'=>'Africa','pinned'=>0],0],
    ['EC','厄瓜多尔','Ecuador','EC','#f59e0b','EC',['iso'=>'EC','iso3'=>'ECU','numeric'=>'218','phone_code'=>'+593','region'=>'Americas','pinned'=>0],0],
    ['EE','爱沙尼亚','Estonia','EE','#2563eb','EE',['iso'=>'EE','iso3'=>'EST','numeric'=>'233','phone_code'=>'+372','region'=>'Europe','pinned'=>0],0],
    ['EG','埃及','Egypt','EG','#16a34a','EG',['iso'=>'EG','iso3'=>'EGY','numeric'=>'818','phone_code'=>'+20','region'=>'Africa','pinned'=>0],0],
    ['EH','西撒哈拉','Western Sahara','EH','#16a34a','EH',['iso'=>'EH','iso3'=>'ESH','numeric'=>'732','phone_code'=>'+212','region'=>'Africa','pinned'=>0],0],
    ['ER','厄立特里亚','Eritrea','ER','#16a34a','ER',['iso'=>'ER','iso3'=>'ERI','numeric'=>'232','phone_code'=>'+291','region'=>'Africa','pinned'=>0],0],
    ['ES','西班牙','Spain','ES','#2563eb','ES',['iso'=>'ES','iso3'=>'ESP','numeric'=>'724','phone_code'=>'+34','region'=>'Europe','pinned'=>0],0],
    ['ET','埃塞俄比亚','Ethiopia','ET','#16a34a','ET',['iso'=>'ET','iso3'=>'ETH','numeric'=>'231','phone_code'=>'+251','region'=>'Africa','pinned'=>0],0],
    ['FI','芬兰','Finland','FI','#2563eb','FI',['iso'=>'FI','iso3'=>'FIN','numeric'=>'246','phone_code'=>'+358','region'=>'Europe','pinned'=>0],0],
    ['FJ','斐济','Fiji','FJ','#0ea5e9','FJ',['iso'=>'FJ','iso3'=>'FJI','numeric'=>'242','phone_code'=>'+679','region'=>'Oceania','pinned'=>0],0],
    ['FK','福克兰群岛','Falkland Islands','FK','#f59e0b','FK',['iso'=>'FK','iso3'=>'FLK','numeric'=>'238','phone_code'=>'+500','region'=>'Americas','pinned'=>0],0],
    ['FM','密克罗尼西亚','Micronesia','FM','#0ea5e9','FM',['iso'=>'FM','iso3'=>'FSM','numeric'=>'583','phone_code'=>'+691','region'=>'Oceania','pinned'=>0],0],
    ['FO','法罗群岛','Faroe Islands','FO','#2563eb','FO',['iso'=>'FO','iso3'=>'FRO','numeric'=>'234','phone_code'=>'+298','region'=>'Europe','pinned'=>0],0],
    ['FR','法国','France','FR','#2563eb','FR',['iso'=>'FR','iso3'=>'FRA','numeric'=>'250','phone_code'=>'+33','region'=>'Europe','pinned'=>0],0],
    ['GA','加蓬','Gabon','GA','#16a34a','GA',['iso'=>'GA','iso3'=>'GAB','numeric'=>'266','phone_code'=>'+241','region'=>'Africa','pinned'=>0],0],
    ['GD','格林纳达','Grenada','GD','#f59e0b','GD',['iso'=>'GD','iso3'=>'GRD','numeric'=>'308','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['GE','格鲁吉亚','Georgia','GE','#dc2626','GE',['iso'=>'GE','iso3'=>'GEO','numeric'=>'268','phone_code'=>'+995','region'=>'Asia','pinned'=>0],0],
    ['GF','法属圭亚那','French Guiana','GF','#f59e0b','GF',['iso'=>'GF','iso3'=>'GUF','numeric'=>'254','phone_code'=>'+594','region'=>'Americas','pinned'=>0],0],
    ['GG','根西岛','Guernsey','GG','#2563eb','GG',['iso'=>'GG','iso3'=>'GGY','numeric'=>'831','phone_code'=>'+44','region'=>'Europe','pinned'=>0],0],
    ['GH','加纳','Ghana','GH','#16a34a','GH',['iso'=>'GH','iso3'=>'GHA','numeric'=>'288','phone_code'=>'+233','region'=>'Africa','pinned'=>0],0],
    ['GI','直布罗陀','Gibraltar','GI','#2563eb','GI',['iso'=>'GI','iso3'=>'GIB','numeric'=>'292','phone_code'=>'+350','region'=>'Europe','pinned'=>0],0],
    ['GL','格陵兰','Greenland','GL','#f59e0b','GL',['iso'=>'GL','iso3'=>'GRL','numeric'=>'304','phone_code'=>'+299','region'=>'Americas','pinned'=>0],0],
    ['GM','冈比亚','Gambia','GM','#16a34a','GM',['iso'=>'GM','iso3'=>'GMB','numeric'=>'270','phone_code'=>'+220','region'=>'Africa','pinned'=>0],0],
    ['GN','几内亚','Guinea','GN','#16a34a','GN',['iso'=>'GN','iso3'=>'GIN','numeric'=>'324','phone_code'=>'+224','region'=>'Africa','pinned'=>0],0],
    ['GP','瓜德罗普','Guadeloupe','GP','#f59e0b','GP',['iso'=>'GP','iso3'=>'GLP','numeric'=>'312','phone_code'=>'+590','region'=>'Americas','pinned'=>0],0],
    ['GQ','赤道几内亚','Equatorial Guinea','GQ','#16a34a','GQ',['iso'=>'GQ','iso3'=>'GNQ','numeric'=>'226','phone_code'=>'+240','region'=>'Africa','pinned'=>0],0],
    ['GR','希腊','Greece','GR','#2563eb','GR',['iso'=>'GR','iso3'=>'GRC','numeric'=>'300','phone_code'=>'+30','region'=>'Europe','pinned'=>0],0],
    ['GS','南乔治亚和南桑威奇群岛','South Georgia & South Sandwich Islands','GS','#f59e0b','GS',['iso'=>'GS','iso3'=>'SGS','numeric'=>'239','phone_code'=>'+500','region'=>'Americas','pinned'=>0],0],
    ['GT','危地马拉','Guatemala','GT','#f59e0b','GT',['iso'=>'GT','iso3'=>'GTM','numeric'=>'320','phone_code'=>'+502','region'=>'Americas','pinned'=>0],0],
    ['GU','关岛','Guam','GU','#0ea5e9','GU',['iso'=>'GU','iso3'=>'GUM','numeric'=>'316','phone_code'=>'+1','region'=>'Oceania','pinned'=>0],0],
    ['GW','几内亚比绍','Guinea-Bissau','GW','#16a34a','GW',['iso'=>'GW','iso3'=>'GNB','numeric'=>'624','phone_code'=>'+245','region'=>'Africa','pinned'=>0],0],
    ['GY','圭亚那','Guyana','GY','#f59e0b','GY',['iso'=>'GY','iso3'=>'GUY','numeric'=>'328','phone_code'=>'+592','region'=>'Americas','pinned'=>0],0],
    ['HM','赫德岛和麦克唐纳群岛','Heard & McDonald Islands','HM','#0ea5e9','HM',['iso'=>'HM','iso3'=>'HMD','numeric'=>'334','phone_code'=>'+672','region'=>'Oceania','pinned'=>0],0],
    ['HN','洪都拉斯','Honduras','HN','#f59e0b','HN',['iso'=>'HN','iso3'=>'HND','numeric'=>'340','phone_code'=>'+504','region'=>'Americas','pinned'=>0],0],
    ['HR','克罗地亚','Croatia','HR','#2563eb','HR',['iso'=>'HR','iso3'=>'HRV','numeric'=>'191','phone_code'=>'+385','region'=>'Europe','pinned'=>0],0],
    ['HT','海地','Haiti','HT','#f59e0b','HT',['iso'=>'HT','iso3'=>'HTI','numeric'=>'332','phone_code'=>'+509','region'=>'Americas','pinned'=>0],0],
    ['HU','匈牙利','Hungary','HU','#2563eb','HU',['iso'=>'HU','iso3'=>'HUN','numeric'=>'348','phone_code'=>'+36','region'=>'Europe','pinned'=>0],0],
    ['ID','印度尼西亚','Indonesia','ID','#dc2626','ID',['iso'=>'ID','iso3'=>'IDN','numeric'=>'360','phone_code'=>'+62','region'=>'Asia','pinned'=>0],0],
    ['IE','爱尔兰','Ireland','IE','#2563eb','IE',['iso'=>'IE','iso3'=>'IRL','numeric'=>'372','phone_code'=>'+353','region'=>'Europe','pinned'=>0],0],
    ['IL','以色列','Israel','IL','#dc2626','IL',['iso'=>'IL','iso3'=>'ISR','numeric'=>'376','phone_code'=>'+972','region'=>'Asia','pinned'=>0],0],
    ['IM','马恩岛','Isle of Man','IM','#2563eb','IM',['iso'=>'IM','iso3'=>'IMN','numeric'=>'833','phone_code'=>'+44','region'=>'Europe','pinned'=>0],0],
    ['IO','英属印度洋领地','British Indian Ocean Territory','IO','#16a34a','IO',['iso'=>'IO','iso3'=>'IOT','numeric'=>'086','phone_code'=>'+246','region'=>'Africa','pinned'=>0],0],
    ['IQ','伊拉克','Iraq','IQ','#dc2626','IQ',['iso'=>'IQ','iso3'=>'IRQ','numeric'=>'368','phone_code'=>'+964','region'=>'Asia','pinned'=>0],0],
    ['IR','伊朗','Iran','IR','#dc2626','IR',['iso'=>'IR','iso3'=>'IRN','numeric'=>'364','phone_code'=>'+98','region'=>'Asia','pinned'=>0],0],
    ['IS','冰岛','Iceland','IS','#2563eb','IS',['iso'=>'IS','iso3'=>'ISL','numeric'=>'352','phone_code'=>'+354','region'=>'Europe','pinned'=>0],0],
    ['IT','意大利','Italy','IT','#2563eb','IT',['iso'=>'IT','iso3'=>'ITA','numeric'=>'380','phone_code'=>'+39','region'=>'Europe','pinned'=>0],0],
    ['JE','泽西岛','Jersey','JE','#2563eb','JE',['iso'=>'JE','iso3'=>'JEY','numeric'=>'832','phone_code'=>'+44','region'=>'Europe','pinned'=>0],0],
    ['JM','牙买加','Jamaica','JM','#f59e0b','JM',['iso'=>'JM','iso3'=>'JAM','numeric'=>'388','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['JO','约旦','Jordan','JO','#dc2626','JO',['iso'=>'JO','iso3'=>'JOR','numeric'=>'400','phone_code'=>'+962','region'=>'Asia','pinned'=>0],0],
    ['JP','日本','Japan','JP','#dc2626','JP',['iso'=>'JP','iso3'=>'JPN','numeric'=>'392','phone_code'=>'+81','region'=>'Asia','pinned'=>0],0],
    ['KE','肯尼亚','Kenya','KE','#16a34a','KE',['iso'=>'KE','iso3'=>'KEN','numeric'=>'404','phone_code'=>'+254','region'=>'Africa','pinned'=>0],0],
    ['KG','吉尔吉斯斯坦','Kyrgyzstan','KG','#dc2626','KG',['iso'=>'KG','iso3'=>'KGZ','numeric'=>'417','phone_code'=>'+996','region'=>'Asia','pinned'=>0],0],
    ['KH','柬埔寨','Cambodia','KH','#dc2626','KH',['iso'=>'KH','iso3'=>'KHM','numeric'=>'116','phone_code'=>'+855','region'=>'Asia','pinned'=>0],0],
    ['KI','基里巴斯','Kiribati','KI','#0ea5e9','KI',['iso'=>'KI','iso3'=>'KIR','numeric'=>'296','phone_code'=>'+686','region'=>'Oceania','pinned'=>0],0],
    ['KM','科摩罗','Comoros','KM','#16a34a','KM',['iso'=>'KM','iso3'=>'COM','numeric'=>'174','phone_code'=>'+269','region'=>'Africa','pinned'=>0],0],
    ['KN','圣基茨和尼维斯','St. Kitts & Nevis','KN','#f59e0b','KN',['iso'=>'KN','iso3'=>'KNA','numeric'=>'659','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['KP','朝鲜','North Korea','KP','#dc2626','KP',['iso'=>'KP','iso3'=>'PRK','numeric'=>'408','phone_code'=>'+850','region'=>'Asia','pinned'=>0],0],
    ['KW','科威特','Kuwait','KW','#dc2626','KW',['iso'=>'KW','iso3'=>'KWT','numeric'=>'414','phone_code'=>'+965','region'=>'Asia','pinned'=>0],0],
    ['KY','开曼群岛','Cayman Islands','KY','#f59e0b','KY',['iso'=>'KY','iso3'=>'CYM','numeric'=>'136','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['KZ','哈萨克斯坦','Kazakhstan','KZ','#dc2626','KZ',['iso'=>'KZ','iso3'=>'KAZ','numeric'=>'398','phone_code'=>'+7','region'=>'Asia','pinned'=>0],0],
    ['LA','老挝','Laos','LA','#dc2626','LA',['iso'=>'LA','iso3'=>'LAO','numeric'=>'418','phone_code'=>'+856','region'=>'Asia','pinned'=>0],0],
    ['LB','黎巴嫩','Lebanon','LB','#dc2626','LB',['iso'=>'LB','iso3'=>'LBN','numeric'=>'422','phone_code'=>'+961','region'=>'Asia','pinned'=>0],0],
    ['LC','圣卢西亚','St. Lucia','LC','#f59e0b','LC',['iso'=>'LC','iso3'=>'LCA','numeric'=>'662','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['LI','列支敦士登','Liechtenstein','LI','#2563eb','LI',['iso'=>'LI','iso3'=>'LIE','numeric'=>'438','phone_code'=>'+423','region'=>'Europe','pinned'=>0],0],
    ['LK','斯里兰卡','Sri Lanka','LK','#dc2626','LK',['iso'=>'LK','iso3'=>'LKA','numeric'=>'144','phone_code'=>'+94','region'=>'Asia','pinned'=>0],0],
    ['LR','利比里亚','Liberia','LR','#16a34a','LR',['iso'=>'LR','iso3'=>'LBR','numeric'=>'430','phone_code'=>'+231','region'=>'Africa','pinned'=>0],0],
    ['LS','莱索托','Lesotho','LS','#16a34a','LS',['iso'=>'LS','iso3'=>'LSO','numeric'=>'426','phone_code'=>'+266','region'=>'Africa','pinned'=>0],0],
    ['LT','立陶宛','Lithuania','LT','#2563eb','LT',['iso'=>'LT','iso3'=>'LTU','numeric'=>'440','phone_code'=>'+370','region'=>'Europe','pinned'=>0],0],
    ['LU','卢森堡','Luxembourg','LU','#2563eb','LU',['iso'=>'LU','iso3'=>'LUX','numeric'=>'442','phone_code'=>'+352','region'=>'Europe','pinned'=>0],0],
    ['LV','拉脱维亚','Latvia','LV','#2563eb','LV',['iso'=>'LV','iso3'=>'LVA','numeric'=>'428','phone_code'=>'+371','region'=>'Europe','pinned'=>0],0],
    ['LY','利比亚','Libya','LY','#16a34a','LY',['iso'=>'LY','iso3'=>'LBY','numeric'=>'434','phone_code'=>'+218','region'=>'Africa','pinned'=>0],0],
    ['MA','摩洛哥','Morocco','MA','#16a34a','MA',['iso'=>'MA','iso3'=>'MAR','numeric'=>'504','phone_code'=>'+212','region'=>'Africa','pinned'=>0],0],
    ['MC','摩纳哥','Monaco','MC','#2563eb','MC',['iso'=>'MC','iso3'=>'MCO','numeric'=>'492','phone_code'=>'+377','region'=>'Europe','pinned'=>0],0],
    ['MD','摩尔多瓦','Moldova','MD','#2563eb','MD',['iso'=>'MD','iso3'=>'MDA','numeric'=>'498','phone_code'=>'+373','region'=>'Europe','pinned'=>0],0],
    ['ME','黑山','Montenegro','ME','#2563eb','ME',['iso'=>'ME','iso3'=>'MNE','numeric'=>'499','phone_code'=>'+382','region'=>'Europe','pinned'=>0],0],
    ['MF','法属圣马丁','St. Martin','MF','#f59e0b','MF',['iso'=>'MF','iso3'=>'MAF','numeric'=>'663','phone_code'=>'+590','region'=>'Americas','pinned'=>0],0],
    ['MG','马达加斯加','Madagascar','MG','#16a34a','MG',['iso'=>'MG','iso3'=>'MDG','numeric'=>'450','phone_code'=>'+261','region'=>'Africa','pinned'=>0],0],
    ['MH','马绍尔群岛','Marshall Islands','MH','#0ea5e9','MH',['iso'=>'MH','iso3'=>'MHL','numeric'=>'584','phone_code'=>'+692','region'=>'Oceania','pinned'=>0],0],
    ['MK','北马其顿','North Macedonia','MK','#2563eb','MK',['iso'=>'MK','iso3'=>'MKD','numeric'=>'807','phone_code'=>'+389','region'=>'Europe','pinned'=>0],0],
    ['ML','马里','Mali','ML','#16a34a','ML',['iso'=>'ML','iso3'=>'MLI','numeric'=>'466','phone_code'=>'+223','region'=>'Africa','pinned'=>0],0],
    ['MM','缅甸','Myanmar (Burma)','MM','#dc2626','MM',['iso'=>'MM','iso3'=>'MMR','numeric'=>'104','phone_code'=>'+95','region'=>'Asia','pinned'=>0],0],
    ['MN','蒙古','Mongolia','MN','#dc2626','MN',['iso'=>'MN','iso3'=>'MNG','numeric'=>'496','phone_code'=>'+976','region'=>'Asia','pinned'=>0],0],
    ['MO','中国澳门特别行政区','Macao SAR China','MO','#dc2626','MO',['iso'=>'MO','iso3'=>'MAC','numeric'=>'446','phone_code'=>'+853','region'=>'Asia','pinned'=>0],0],
    ['MP','北马里亚纳群岛','Northern Mariana Islands','MP','#0ea5e9','MP',['iso'=>'MP','iso3'=>'MNP','numeric'=>'580','phone_code'=>'+1','region'=>'Oceania','pinned'=>0],0],
    ['MQ','马提尼克','Martinique','MQ','#f59e0b','MQ',['iso'=>'MQ','iso3'=>'MTQ','numeric'=>'474','phone_code'=>'+596','region'=>'Americas','pinned'=>0],0],
    ['MR','毛里塔尼亚','Mauritania','MR','#16a34a','MR',['iso'=>'MR','iso3'=>'MRT','numeric'=>'478','phone_code'=>'+222','region'=>'Africa','pinned'=>0],0],
    ['MS','蒙特塞拉特','Montserrat','MS','#f59e0b','MS',['iso'=>'MS','iso3'=>'MSR','numeric'=>'500','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['MT','马耳他','Malta','MT','#2563eb','MT',['iso'=>'MT','iso3'=>'MLT','numeric'=>'470','phone_code'=>'+356','region'=>'Europe','pinned'=>0],0],
    ['MU','毛里求斯','Mauritius','MU','#16a34a','MU',['iso'=>'MU','iso3'=>'MUS','numeric'=>'480','phone_code'=>'+230','region'=>'Africa','pinned'=>0],0],
    ['MV','马尔代夫','Maldives','MV','#dc2626','MV',['iso'=>'MV','iso3'=>'MDV','numeric'=>'462','phone_code'=>'+960','region'=>'Asia','pinned'=>0],0],
    ['MW','马拉维','Malawi','MW','#16a34a','MW',['iso'=>'MW','iso3'=>'MWI','numeric'=>'454','phone_code'=>'+265','region'=>'Africa','pinned'=>0],0],
    ['MX','墨西哥','Mexico','MX','#f59e0b','MX',['iso'=>'MX','iso3'=>'MEX','numeric'=>'484','phone_code'=>'+52','region'=>'Americas','pinned'=>0],0],
    ['MY','马来西亚','Malaysia','MY','#dc2626','MY',['iso'=>'MY','iso3'=>'MYS','numeric'=>'458','phone_code'=>'+60','region'=>'Asia','pinned'=>0],0],
    ['MZ','莫桑比克','Mozambique','MZ','#16a34a','MZ',['iso'=>'MZ','iso3'=>'MOZ','numeric'=>'508','phone_code'=>'+258','region'=>'Africa','pinned'=>0],0],
    ['NA','纳米比亚','Namibia','NA','#16a34a','NA',['iso'=>'NA','iso3'=>'NAM','numeric'=>'516','phone_code'=>'+264','region'=>'Africa','pinned'=>0],0],
    ['NC','新喀里多尼亚','New Caledonia','NC','#0ea5e9','NC',['iso'=>'NC','iso3'=>'NCL','numeric'=>'540','phone_code'=>'+687','region'=>'Oceania','pinned'=>0],0],
    ['NE','尼日尔','Niger','NE','#16a34a','NE',['iso'=>'NE','iso3'=>'NER','numeric'=>'562','phone_code'=>'+227','region'=>'Africa','pinned'=>0],0],
    ['NF','诺福克岛','Norfolk Island','NF','#0ea5e9','NF',['iso'=>'NF','iso3'=>'NFK','numeric'=>'574','phone_code'=>'+672','region'=>'Oceania','pinned'=>0],0],
    ['NG','尼日利亚','Nigeria','NG','#16a34a','NG',['iso'=>'NG','iso3'=>'NGA','numeric'=>'566','phone_code'=>'+234','region'=>'Africa','pinned'=>0],0],
    ['NI','尼加拉瓜','Nicaragua','NI','#f59e0b','NI',['iso'=>'NI','iso3'=>'NIC','numeric'=>'558','phone_code'=>'+505','region'=>'Americas','pinned'=>0],0],
    ['NL','荷兰','Netherlands','NL','#2563eb','NL',['iso'=>'NL','iso3'=>'NLD','numeric'=>'528','phone_code'=>'+31','region'=>'Europe','pinned'=>0],0],
    ['NO','挪威','Norway','NO','#2563eb','NO',['iso'=>'NO','iso3'=>'NOR','numeric'=>'578','phone_code'=>'+47','region'=>'Europe','pinned'=>0],0],
    ['NP','尼泊尔','Nepal','NP','#dc2626','NP',['iso'=>'NP','iso3'=>'NPL','numeric'=>'524','phone_code'=>'+977','region'=>'Asia','pinned'=>0],0],
    ['NR','瑙鲁','Nauru','NR','#0ea5e9','NR',['iso'=>'NR','iso3'=>'NRU','numeric'=>'520','phone_code'=>'+674','region'=>'Oceania','pinned'=>0],0],
    ['NU','纽埃','Niue','NU','#0ea5e9','NU',['iso'=>'NU','iso3'=>'NIU','numeric'=>'570','phone_code'=>'+683','region'=>'Oceania','pinned'=>0],0],
    ['NZ','新西兰','New Zealand','NZ','#0ea5e9','NZ',['iso'=>'NZ','iso3'=>'NZL','numeric'=>'554','phone_code'=>'+64','region'=>'Oceania','pinned'=>0],0],
    ['OM','阿曼','Oman','OM','#dc2626','OM',['iso'=>'OM','iso3'=>'OMN','numeric'=>'512','phone_code'=>'+968','region'=>'Asia','pinned'=>0],0],
    ['PA','巴拿马','Panama','PA','#f59e0b','PA',['iso'=>'PA','iso3'=>'PAN','numeric'=>'591','phone_code'=>'+507','region'=>'Americas','pinned'=>0],0],
    ['PE','秘鲁','Peru','PE','#f59e0b','PE',['iso'=>'PE','iso3'=>'PER','numeric'=>'604','phone_code'=>'+51','region'=>'Americas','pinned'=>0],0],
    ['PF','法属波利尼西亚','French Polynesia','PF','#0ea5e9','PF',['iso'=>'PF','iso3'=>'PYF','numeric'=>'258','phone_code'=>'+689','region'=>'Oceania','pinned'=>0],0],
    ['PG','巴布亚新几内亚','Papua New Guinea','PG','#0ea5e9','PG',['iso'=>'PG','iso3'=>'PNG','numeric'=>'598','phone_code'=>'+675','region'=>'Oceania','pinned'=>0],0],
    ['PH','菲律宾','Philippines','PH','#dc2626','PH',['iso'=>'PH','iso3'=>'PHL','numeric'=>'608','phone_code'=>'+63','region'=>'Asia','pinned'=>0],0],
    ['PK','巴基斯坦','Pakistan','PK','#dc2626','PK',['iso'=>'PK','iso3'=>'PAK','numeric'=>'586','phone_code'=>'+92','region'=>'Asia','pinned'=>0],0],
    ['PL','波兰','Poland','PL','#2563eb','PL',['iso'=>'PL','iso3'=>'POL','numeric'=>'616','phone_code'=>'+48','region'=>'Europe','pinned'=>0],0],
    ['PM','圣皮埃尔和密克隆群岛','St. Pierre & Miquelon','PM','#f59e0b','PM',['iso'=>'PM','iso3'=>'SPM','numeric'=>'666','phone_code'=>'+508','region'=>'Americas','pinned'=>0],0],
    ['PN','皮特凯恩群岛','Pitcairn Islands','PN','#0ea5e9','PN',['iso'=>'PN','iso3'=>'PCN','numeric'=>'612','phone_code'=>'+64','region'=>'Oceania','pinned'=>0],0],
    ['PR','波多黎各','Puerto Rico','PR','#f59e0b','PR',['iso'=>'PR','iso3'=>'PRI','numeric'=>'630','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['PS','巴勒斯坦领土','Palestinian Territories','PS','#dc2626','PS',['iso'=>'PS','iso3'=>'PSE','numeric'=>'275','phone_code'=>'+970','region'=>'Asia','pinned'=>0],0],
    ['PT','葡萄牙','Portugal','PT','#2563eb','PT',['iso'=>'PT','iso3'=>'PRT','numeric'=>'620','phone_code'=>'+351','region'=>'Europe','pinned'=>0],0],
    ['PW','帕劳','Palau','PW','#0ea5e9','PW',['iso'=>'PW','iso3'=>'PLW','numeric'=>'585','phone_code'=>'+680','region'=>'Oceania','pinned'=>0],0],
    ['PY','巴拉圭','Paraguay','PY','#f59e0b','PY',['iso'=>'PY','iso3'=>'PRY','numeric'=>'600','phone_code'=>'+595','region'=>'Americas','pinned'=>0],0],
    ['QA','卡塔尔','Qatar','QA','#dc2626','QA',['iso'=>'QA','iso3'=>'QAT','numeric'=>'634','phone_code'=>'+974','region'=>'Asia','pinned'=>0],0],
    ['RE','留尼汪','Réunion','RE','#16a34a','RE',['iso'=>'RE','iso3'=>'REU','numeric'=>'638','phone_code'=>'+262','region'=>'Africa','pinned'=>0],0],
    ['RO','罗马尼亚','Romania','RO','#2563eb','RO',['iso'=>'RO','iso3'=>'ROU','numeric'=>'642','phone_code'=>'+40','region'=>'Europe','pinned'=>0],0],
    ['RS','塞尔维亚','Serbia','RS','#2563eb','RS',['iso'=>'RS','iso3'=>'SRB','numeric'=>'688','phone_code'=>'+381','region'=>'Europe','pinned'=>0],0],
    ['RU','俄罗斯','Russia','RU','#2563eb','RU',['iso'=>'RU','iso3'=>'RUS','numeric'=>'643','phone_code'=>'+7','region'=>'Europe','pinned'=>0],0],
    ['RW','卢旺达','Rwanda','RW','#16a34a','RW',['iso'=>'RW','iso3'=>'RWA','numeric'=>'646','phone_code'=>'+250','region'=>'Africa','pinned'=>0],0],
    ['SB','所罗门群岛','Solomon Islands','SB','#0ea5e9','SB',['iso'=>'SB','iso3'=>'SLB','numeric'=>'090','phone_code'=>'+677','region'=>'Oceania','pinned'=>0],0],
    ['SC','塞舌尔','Seychelles','SC','#16a34a','SC',['iso'=>'SC','iso3'=>'SYC','numeric'=>'690','phone_code'=>'+248','region'=>'Africa','pinned'=>0],0],
    ['SD','苏丹','Sudan','SD','#16a34a','SD',['iso'=>'SD','iso3'=>'SDN','numeric'=>'729','phone_code'=>'+249','region'=>'Africa','pinned'=>0],0],
    ['SE','瑞典','Sweden','SE','#2563eb','SE',['iso'=>'SE','iso3'=>'SWE','numeric'=>'752','phone_code'=>'+46','region'=>'Europe','pinned'=>0],0],
    ['SH','圣赫勒拿','St. Helena','SH','#16a34a','SH',['iso'=>'SH','iso3'=>'SHN','numeric'=>'654','phone_code'=>'+290','region'=>'Africa','pinned'=>0],0],
    ['SI','斯洛文尼亚','Slovenia','SI','#2563eb','SI',['iso'=>'SI','iso3'=>'SVN','numeric'=>'705','phone_code'=>'+386','region'=>'Europe','pinned'=>0],0],
    ['SJ','斯瓦尔巴和扬马延','Svalbard & Jan Mayen','SJ','#2563eb','SJ',['iso'=>'SJ','iso3'=>'SJM','numeric'=>'744','phone_code'=>'+47','region'=>'Europe','pinned'=>0],0],
    ['SK','斯洛伐克','Slovakia','SK','#2563eb','SK',['iso'=>'SK','iso3'=>'SVK','numeric'=>'703','phone_code'=>'+421','region'=>'Europe','pinned'=>0],0],
    ['SL','塞拉利昂','Sierra Leone','SL','#16a34a','SL',['iso'=>'SL','iso3'=>'SLE','numeric'=>'694','phone_code'=>'+232','region'=>'Africa','pinned'=>0],0],
    ['SM','圣马力诺','San Marino','SM','#2563eb','SM',['iso'=>'SM','iso3'=>'SMR','numeric'=>'674','phone_code'=>'+378','region'=>'Europe','pinned'=>0],0],
    ['SN','塞内加尔','Senegal','SN','#16a34a','SN',['iso'=>'SN','iso3'=>'SEN','numeric'=>'686','phone_code'=>'+221','region'=>'Africa','pinned'=>0],0],
    ['SO','索马里','Somalia','SO','#16a34a','SO',['iso'=>'SO','iso3'=>'SOM','numeric'=>'706','phone_code'=>'+252','region'=>'Africa','pinned'=>0],0],
    ['SR','苏里南','Suriname','SR','#f59e0b','SR',['iso'=>'SR','iso3'=>'SUR','numeric'=>'740','phone_code'=>'+597','region'=>'Americas','pinned'=>0],0],
    ['SS','南苏丹','South Sudan','SS','#16a34a','SS',['iso'=>'SS','iso3'=>'SSD','numeric'=>'728','phone_code'=>'+211','region'=>'Africa','pinned'=>0],0],
    ['ST','圣多美和普林西比','São Tomé & Príncipe','ST','#16a34a','ST',['iso'=>'ST','iso3'=>'STP','numeric'=>'678','phone_code'=>'+239','region'=>'Africa','pinned'=>0],0],
    ['SV','萨尔瓦多','El Salvador','SV','#f59e0b','SV',['iso'=>'SV','iso3'=>'SLV','numeric'=>'222','phone_code'=>'+503','region'=>'Americas','pinned'=>0],0],
    ['SX','荷属圣马丁','Sint Maarten','SX','#f59e0b','SX',['iso'=>'SX','iso3'=>'SXM','numeric'=>'534','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['SY','叙利亚','Syria','SY','#dc2626','SY',['iso'=>'SY','iso3'=>'SYR','numeric'=>'760','phone_code'=>'+963','region'=>'Asia','pinned'=>0],0],
    ['SZ','斯威士兰','Eswatini','SZ','#16a34a','SZ',['iso'=>'SZ','iso3'=>'SWZ','numeric'=>'748','phone_code'=>'+268','region'=>'Africa','pinned'=>0],0],
    ['TC','特克斯和凯科斯群岛','Turks & Caicos Islands','TC','#f59e0b','TC',['iso'=>'TC','iso3'=>'TCA','numeric'=>'796','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['TD','乍得','Chad','TD','#16a34a','TD',['iso'=>'TD','iso3'=>'TCD','numeric'=>'148','phone_code'=>'+235','region'=>'Africa','pinned'=>0],0],
    ['TF','法属南部领地','French Southern Territories','TF','#16a34a','TF',['iso'=>'TF','iso3'=>'ATF','numeric'=>'260','phone_code'=>'+262','region'=>'Africa','pinned'=>0],0],
    ['TG','多哥','Togo','TG','#16a34a','TG',['iso'=>'TG','iso3'=>'TGO','numeric'=>'768','phone_code'=>'+228','region'=>'Africa','pinned'=>0],0],
    ['TH','泰国','Thailand','TH','#dc2626','TH',['iso'=>'TH','iso3'=>'THA','numeric'=>'764','phone_code'=>'+66','region'=>'Asia','pinned'=>0],0],
    ['TJ','塔吉克斯坦','Tajikistan','TJ','#dc2626','TJ',['iso'=>'TJ','iso3'=>'TJK','numeric'=>'762','phone_code'=>'+992','region'=>'Asia','pinned'=>0],0],
    ['TK','托克劳','Tokelau','TK','#0ea5e9','TK',['iso'=>'TK','iso3'=>'TKL','numeric'=>'772','phone_code'=>'+690','region'=>'Oceania','pinned'=>0],0],
    ['TL','东帝汶','Timor-Leste','TL','#dc2626','TL',['iso'=>'TL','iso3'=>'TLS','numeric'=>'626','phone_code'=>'+670','region'=>'Asia','pinned'=>0],0],
    ['TM','土库曼斯坦','Turkmenistan','TM','#dc2626','TM',['iso'=>'TM','iso3'=>'TKM','numeric'=>'795','phone_code'=>'+993','region'=>'Asia','pinned'=>0],0],
    ['TN','突尼斯','Tunisia','TN','#16a34a','TN',['iso'=>'TN','iso3'=>'TUN','numeric'=>'788','phone_code'=>'+216','region'=>'Africa','pinned'=>0],0],
    ['TO','汤加','Tonga','TO','#0ea5e9','TO',['iso'=>'TO','iso3'=>'TON','numeric'=>'776','phone_code'=>'+676','region'=>'Oceania','pinned'=>0],0],
    ['TT','特立尼达和多巴哥','Trinidad & Tobago','TT','#f59e0b','TT',['iso'=>'TT','iso3'=>'TTO','numeric'=>'780','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['TV','图瓦卢','Tuvalu','TV','#0ea5e9','TV',['iso'=>'TV','iso3'=>'TUV','numeric'=>'798','phone_code'=>'+688','region'=>'Oceania','pinned'=>0],0],
    ['TW','台湾','Taiwan','TW','#dc2626','TW',['iso'=>'TW','iso3'=>'TWN','numeric'=>'158','phone_code'=>'+886','region'=>'Asia','pinned'=>0],0],
    ['TZ','坦桑尼亚','Tanzania','TZ','#16a34a','TZ',['iso'=>'TZ','iso3'=>'TZA','numeric'=>'834','phone_code'=>'+255','region'=>'Africa','pinned'=>0],0],
    ['UA','乌克兰','Ukraine','UA','#2563eb','UA',['iso'=>'UA','iso3'=>'UKR','numeric'=>'804','phone_code'=>'+380','region'=>'Europe','pinned'=>0],0],
    ['UG','乌干达','Uganda','UG','#16a34a','UG',['iso'=>'UG','iso3'=>'UGA','numeric'=>'800','phone_code'=>'+256','region'=>'Africa','pinned'=>0],0],
    ['UM','美国本土外小岛屿','U.S. Outlying Islands','UM','#0ea5e9','UM',['iso'=>'UM','iso3'=>'UMI','numeric'=>'581','phone_code'=>'+1','region'=>'Oceania','pinned'=>0],0],
    ['UY','乌拉圭','Uruguay','UY','#f59e0b','UY',['iso'=>'UY','iso3'=>'URY','numeric'=>'858','phone_code'=>'+598','region'=>'Americas','pinned'=>0],0],
    ['UZ','乌兹别克斯坦','Uzbekistan','UZ','#dc2626','UZ',['iso'=>'UZ','iso3'=>'UZB','numeric'=>'860','phone_code'=>'+998','region'=>'Asia','pinned'=>0],0],
    ['VA','梵蒂冈','Vatican City','VA','#2563eb','VA',['iso'=>'VA','iso3'=>'VAT','numeric'=>'336','phone_code'=>'+39','region'=>'Europe','pinned'=>0],0],
    ['VC','圣文森特和格林纳丁斯','St. Vincent & Grenadines','VC','#f59e0b','VC',['iso'=>'VC','iso3'=>'VCT','numeric'=>'670','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['VE','委内瑞拉','Venezuela','VE','#f59e0b','VE',['iso'=>'VE','iso3'=>'VEN','numeric'=>'862','phone_code'=>'+58','region'=>'Americas','pinned'=>0],0],
    ['VG','英属维尔京群岛','British Virgin Islands','VG','#f59e0b','VG',['iso'=>'VG','iso3'=>'VGB','numeric'=>'092','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['VI','美属维尔京群岛','U.S. Virgin Islands','VI','#f59e0b','VI',['iso'=>'VI','iso3'=>'VIR','numeric'=>'850','phone_code'=>'+1','region'=>'Americas','pinned'=>0],0],
    ['VN','越南','Vietnam','VN','#dc2626','VN',['iso'=>'VN','iso3'=>'VNM','numeric'=>'704','phone_code'=>'+84','region'=>'Asia','pinned'=>0],0],
    ['VU','瓦努阿图','Vanuatu','VU','#0ea5e9','VU',['iso'=>'VU','iso3'=>'VUT','numeric'=>'548','phone_code'=>'+678','region'=>'Oceania','pinned'=>0],0],
    ['WF','瓦利斯和富图纳','Wallis & Futuna','WF','#0ea5e9','WF',['iso'=>'WF','iso3'=>'WLF','numeric'=>'876','phone_code'=>'+681','region'=>'Oceania','pinned'=>0],0],
    ['WS','萨摩亚','Samoa','WS','#0ea5e9','WS',['iso'=>'WS','iso3'=>'WSM','numeric'=>'882','phone_code'=>'+685','region'=>'Oceania','pinned'=>0],0],
    ['YE','也门','Yemen','YE','#dc2626','YE',['iso'=>'YE','iso3'=>'YEM','numeric'=>'887','phone_code'=>'+967','region'=>'Asia','pinned'=>0],0],
    ['YT','马约特','Mayotte','YT','#16a34a','YT',['iso'=>'YT','iso3'=>'MYT','numeric'=>'175','phone_code'=>'+262','region'=>'Africa','pinned'=>0],0],
    ['ZA','南非','South Africa','ZA','#16a34a','ZA',['iso'=>'ZA','iso3'=>'ZAF','numeric'=>'710','phone_code'=>'+27','region'=>'Africa','pinned'=>0],0],
    ['ZM','赞比亚','Zambia','ZM','#16a34a','ZM',['iso'=>'ZM','iso3'=>'ZMB','numeric'=>'894','phone_code'=>'+260','region'=>'Africa','pinned'=>0],0],
    ['ZW','津巴布韦','Zimbabwe','ZW','#16a34a','ZW',['iso'=>'ZW','iso3'=>'ZWE','numeric'=>'716','phone_code'=>'+263','region'=>'Africa','pinned'=>0],0],
];
