<!doctype html><html><head><meta charset="utf-8"><title><?=qd_h($docFileTitle)?></title><?=qd_print_style()?></head><body>
<?php if((empty($documentReadOnly)&&!($format==='xls'||$format==='xlsx'||$format==='excel'))): ?><div class="toolbar"><b><?=qd_h($docFileTitle)?></b><div><button class="gray" onclick="history.back()">返回</button><button onclick="window.print()">打印 / 保存PDF</button></div></div><?php endif; ?>
<div class="paper">
  <?php if(!empty($documentState)): ?><div class="box" style="margin-bottom:5mm"><?=qd_h($documentState)?></div><?php endif; ?>
  <?php if($docVoided): ?><div class="doc-void-watermark">VOID</div><div class="doc-void-note"><b>该单证已作废</b> / This document is void. <?=qd_h($voidText)?></div><?php endif; ?>
  <div class="top">
    <div class="seller"><h1><?=qd_h($sellerName)?></h1><div class="txt"><?=qd_h($sellerText)?></div><div class="buyer"><b><?=qd_h($settings['buyer_label']??'Buyer / Consignee')?>:</b>
<?=qd_h(qd_customer_text($customer,$settings['buyer_label']??''))?></div><?php if(!empty($settings['show_notify_party']) && qd_s($settings['notify_party']??'')!==''): ?><div class="buyer"><b>Notify Party:</b>
<?=qd_h($settings['notify_party'])?></div><?php endif; ?></div>
    <div><div class="brandstamp"><?=qd_h(qd_header_stamp($order))?></div><div class="doc-title"><?=qd_h($docTitle)?></div><table class="terms"><?php foreach(qd_doc_terms($type,$order,$ship,$settings) as $r): $field=$r[2]??''; $editable=!empty($r[3]); $labelField=$r[4]??''; $labelEditable=!empty($r[5]); ?><tr><td<?=($labelEditable&&(empty($documentReadOnly)&&!($format==='xls'||$format==='xlsx'||$format==='excel')))?' class="doc-edit-cell" contenteditable="true" data-doc-edit="'.qd_h($labelField).'" data-placeholder="点击填写"':''?>><?=qd_h($r[0])?></td><td<?=($editable&&(empty($documentReadOnly)&&!($format==='xls'||$format==='xlsx'||$format==='excel')))?' class="doc-edit-cell" contenteditable="true" data-doc-edit="'.qd_h($field).'" data-placeholder="点击填写"':''?>><?=qd_h($r[1])?></td></tr><?php endforeach; ?></table></div>
  </div>
<?php if($type==='ci'): ?>
  <table class="doc-table"><colgroup><col style="width:7%"><col style="width:9%"><col style="width:9%"><col style="width:10%"><col style="width:10%"><col style="width:30%"><col style="width:6%"><col style="width:6%"><col style="width:7%"><col style="width:7%"><col style="width:7%"></colgroup><thead><tr><th>Picture</th><th>Order No.</th><th>Size</th><th>Customer<br>Model</th><th>Manufacturer<br>Code</th><th>Description</th><th>Color</th><th>QTY<br>(pcs)</th><th>Unit Price<br>(<?=qd_h($order['currency']??'USD')?>)</th><th>Amount<br>(<?=qd_h($order['currency']??'USD')?>)</th><th>HS Code</th></tr></thead><tbody>
  <?php foreach($ciItems as $i=>$it): $img=qd_img_src($it); ?><tr><td class="pic-cell"><?php if($img!==''): ?><img class="ci-img" src="<?=qd_h($img)?>"><?php endif; ?></td><td><?=qd_h($it['order_no']??'')?></td><td><?=qd_h($it['size']??'')?></td><td><?=qd_h($it['customer_code']??'')?></td><td><?=qd_h($it['product_code']??'')?></td><td class="desc"><?=qd_h(qd_desc($it))?></td><td><?=qd_h($it['color']??'')?></td><td><?=qd_qty($it['qty']??0)?></td><td><?=qd_money($it['unit_price']??0)?></td><td><?=qd_money($it['amount']??0)?></td><td<?=(!empty($documentReadOnly)||$format==='xls'||$format==='xlsx'||$format==='excel')?'':' class="material-edit" contenteditable="true" data-doc-edit="hs_code_'.qd_h($i).'"'?>><?=qd_h($it['hs_code']??'')?></td></tr><?php endforeach; ?>
  <tr><td colspan="7"></td><td><b><?=qd_qty(qd_total($ciItems,'qty'))?></b></td><td><b>Total:</b></td><td><b><?=qd_money(qd_total($ciItems,'amount'))?></b></td><td></td></tr></tbody></table>
  <div class="summary"><div class="box"><b>Total Qty:</b> <?=qd_qty(qd_total($ciItems,'qty'))?> PCS<br><b>Total Amount:</b> <?=qd_h($order['currency']??'USD')?> <?=qd_money(qd_total($ciItems,'amount'))?><br><b>Currency:</b> <?=qd_h($order['currency']??'USD')?></div><div class="box"><b>Invoice No:</b> <?=qd_h($ship['commercial_invoice_no']??'')?><br><b>PI No.:</b> <?=qd_h($order['_shipment_order_refs']??qd_order_no_at($order['order_no']??'',$order['quote_no']??''))?><br><b>Date:</b> <?=qd_h($ship['ship_date']??date('Y-m-d'))?></div></div>
  <?php /* V6.8.5.53: CI 不显示银行信息区 */ ?>
<?php else: ?>
  <table class="doc-table"><colgroup><col style="width:6%"><col style="width:9%"><col style="width:9%"><col style="width:10%"><col style="width:27%"><col style="width:6%"><col style="width:6%"><col style="width:6%"><col style="width:4.5%"><col style="width:4.5%"><col style="width:4.5%"><col style="width:5.5%"><col style="width:5.5%"><col style="width:5.5%"><col style="width:5%"></colgroup><thead><tr><th>Picture</th><th>Order No.</th><th>Customer<br>Model</th><th>Manufacturer<br>Code</th><th>Description</th><th>Color</th><th>QTY<br>(pcs)</th><th>PCS/<br>CTN</th><th>L<br>(cm)</th><th>W<br>(cm)</th><th>H<br>(cm)</th><th>CTNS</th><th>N.W.<br>(KG)</th><th>G.W.<br>(KG)</th><th>CBM</th></tr></thead><tbody>
  <?php foreach($plItems as $i=>$it): list($cl,$cw,$ch)=qd_carton_dims($it['carton_size']??''); $img=qd_img_src($it); $span=max(1,(int)($it['_carton_rowspan']??1)); ?><tr><td class="pic-cell"><?php if($img!==''): ?><img class="pl-img" src="<?=qd_h($img)?>"><?php endif; ?></td><td><?=qd_h($it['order_no']??'')?></td><td><?=qd_h($it['customer_code']??'')?></td><td><?=qd_h($it['product_code']??'')?></td><td class="desc"><?=qd_h(qd_desc($it))?></td><td><?=qd_h($it['color']??'')?></td><td><?=!empty($it['_packing_only'])?'—':qd_qty($it['qty']??0)?></td><?php if(empty($it['_carton_skip_pack'])): ?><td rowspan="<?=$span?>"><span class="nowrap" style="font-size:6pt"><?=qd_qty($it['pcs_per_ctn']??0)?></span></td><td rowspan="<?=$span?>"><?=qd_h($cl)?></td><td rowspan="<?=$span?>"><?=qd_h($cw)?></td><td rowspan="<?=$span?>"><?=qd_h($ch)?></td><td rowspan="<?=$span?>"><span class="nowrap" style="font-size:6pt"><?=qd_qty($it['cartons']??0)?></span></td><td rowspan="<?=$span?>"><span class="nowrap" style="font-size:6pt"><?=qd_qty($it['nw']??0,3)?></span></td><td rowspan="<?=$span?>"><span class="nowrap" style="font-size:6pt"><?=qd_qty($it['gw']??0,3)?></span></td><td rowspan="<?=$span?>"><span class="nowrap" style="font-size:6pt"><?=qd_qty($it['cbm']??0,4)?></span></td><?php endif; ?></tr><?php endforeach; ?>
  <tr><td colspan="6"></td><td><b><?=qd_qty(qd_total($plItems,'qty'))?></b></td><td></td><td colspan="3"><b>Total:</b></td><td><b><?=qd_qty(qd_total($plItems,'cartons'))?></b></td><td><b><?=qd_qty(qd_total($plItems,'nw'),3)?></b></td><td><b><?=qd_qty(qd_total($plItems,'gw'),3)?></b></td><td><b class="nowrap" style="font-size:6pt"><?=qd_qty(qd_total($plItems,'cbm'),4)?></b></td></tr></tbody></table>
  <div class="summary"><div class="box"><b>Total Qty:</b> <?=qd_qty(qd_total($plItems,'qty'))?> PCS<br><b>Total Cartons:</b> <?=qd_qty(qd_total($plItems,'cartons'))?> CTNS<br><b>Total N.W.:</b> <?=qd_qty(qd_total($plItems,'nw'),3)?> KG<br><b>Total G.W.:</b> <?=qd_qty(qd_total($plItems,'gw'),3)?> KG<br><b>Total CBM:</b> <?=qd_qty(qd_total($plItems,'cbm'),4)?></div><div class="box"><b>Packing List No:</b> <?=qd_h($ship['packing_list_no']??'')?><br><b>PI No.:</b> <?=qd_h($order['_shipment_order_refs']??qd_order_no_at($order['order_no']??'',$order['quote_no']??''))?><br><b>Date:</b> <?=qd_h($ship['ship_date']??date('Y-m-d'))?></div></div>
<?php endif; ?>
<?php if(!empty($documentNote)): ?><div class="box" style="margin-top:5mm"><?=qd_h($documentNote)?></div><?php endif; ?>
</div>

<?php if((empty($documentReadOnly)&&!($format==='xls'||$format==='xlsx'||$format==='excel'))): ?><script>
(function(){
  var prefix='artdon_ci_pl_edit_'+<?=json_encode((int)$shipmentId)?>+'_'+<?=json_encode($type)?>+'_';
  document.querySelectorAll('[data-doc-edit]').forEach(function(el){
    var key=prefix+el.getAttribute('data-doc-edit');
    try{var saved=localStorage.getItem(key); if(saved!==null) el.textContent=saved;}catch(e){}
    el.addEventListener('input',function(){try{localStorage.setItem(key,el.textContent.trim());}catch(e){}});
  });
})();
</script><?php endif; ?>
<?php if($format==='pdf'): ?><script>window.addEventListener('load',function(){setTimeout(function(){try{window.focus();window.print();}catch(e){}},450);});</script><?php endif; ?>
</body></html>
