<?php
declare(strict_types=1);require_once __DIR__.'/bootstrap.php';use Artdon\MaterialCenter\Services\PowerStandardizationService;
$user=mc_current_user();$ready=mc_table_exists('mc_materials');$q=trim((string)($_GET['q']??''));$rows=$user&&$ready?(new PowerStandardizationService())->formalRows($q):[];
header('Content-Type:text/html;charset=utf-8');header('Cache-Control:no-store');mc_page_start('正式电源库','library',$user);
?>
<div class="ui-page-head"><div><span class="ui-eyebrow">MM3 · STRUCTURED POWER MATERIALS</span><h1>正式电源库</h1><p>仅展示已经人工确认建立的结构化电源；当前试点默认不允许 BOM、报价或客户显示。</p></div><span class="ui-badge ui-badge-success"><?=count($rows)?> 条</span></div>
<?php if(!$user):?><?php mc_state('permission','需要统一登录','正式库复用广州 ERP 登录态。','../login.php','前往登录');?>
<?php elseif(!$ready):?><?php mc_state('config','正式物料结构尚未安装','请先执行 MM2–MM4 迁移。');?>
<?php else:?><form class="ui-toolbar ui-card" method="get"><input class="ui-input" name="q" value="<?=mc_h($q)?>" placeholder="搜索物料编号、品牌、型号、名称"><button class="ui-btn">搜索</button><a class="ui-btn ui-btn-secondary" href="./formal_power_supplies.php">重置</a><button class="ui-btn ui-btn-secondary" type="button" data-ui-table-settings="#formal-power-table">视图设置</button></form><div class="ui-batch-bar" data-batch-bar hidden><strong>已选择 <span data-selected-count>0</span> 项</strong><button class="ui-btn ui-btn-sm" type="button" data-open-batch>批量设置</button><button class="ui-btn ui-btn-secondary ui-btn-sm" type="button" data-cancel-selection>取消选择</button></div>
<?php if(!$rows):?><?php mc_state('empty','正式电源库暂无记录','请在电源页面设置草稿并完成确认、审批。','material/power.php','返回电源');?>
<?php else:?><section class="ui-card ui-table-panel"><div class="ui-table-wrap"><table class="ui-table" id="formal-power-table" data-ui-table><thead><tr><th class="ui-select-col"><label class="ui-check"><input type="checkbox" data-ui-select-all><span class="ui-check-box"></span></label></th><th data-sort>物料编号</th><th data-sort>品牌</th><th data-sort>型号</th><th data-sort>名称</th><th data-sort>功率档</th><th data-sort>安装</th><th data-sort>输出</th><th data-sort>电流选项</th><th data-sort>调光</th><th data-sort>状态</th></tr></thead><tbody><?php foreach($rows as$r):?><tr data-material-id="<?=$r['material_id']?>"><td class="ui-select-col"><label class="ui-check"><input type="checkbox" data-ui-row-select><span class="ui-check-box"></span></label></td><td><b><?=mc_h($r['material_code'])?></b></td><td><?=mc_h($r['brand'])?></td><td><?=mc_h($r['model'])?></td><td><?=mc_h($r['name'])?></td><td><?=mc_h($r['power_band'])?></td><td><?=mc_h($r['installation_type'])?></td><td><?=mc_h($r['output_type'])?></td><td><?=mc_h($r['current_options']?:$r['output_current_ma'])?>mA</td><td><?=mc_h($r['dimming_modes']?:'待确认')?></td><td><span class="ui-badge"><?=$r['is_pilot']?'试点':'正式'?> / <?=mc_h($r['status'])?></span></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;endif;?>
<aside class="ui-drawer ui-drawer-m" id="batch-drawer" role="dialog" aria-modal="true" aria-hidden="true" tabindex="-1"><div class="ui-drawer-header"><h2>批量设置</h2><button class="ui-btn ui-btn-secondary ui-btn-icon" data-ui-close>×</button></div><div class="ui-drawer-body"><form id="batch-form"><input type="hidden" name="csrf_token" value="<?=mc_h(function_exists('csrf_token')?csrf_token():'')?>"><label class="ui-field"><span class="ui-label">覆盖策略</span><select class="ui-select" name="policy"><option value="fill_empty">只填空值</option><option value="overwrite">覆盖原值</option></select></label><div data-batch-fields></div><button class="ui-btn ui-btn-secondary ui-btn-sm" type="button" data-add-batch-field>添加字段</button><div data-batch-preview></div></form></div><div class="ui-drawer-footer"><button class="ui-btn ui-btn-secondary" data-preview-batch>预览变化</button><button class="ui-btn" data-execute-batch disabled>确认执行</button></div></aside>
<?php mc_page_end('','assets/js/formal-power-supplies.js');?>
