<?php
require_once __DIR__.'/bootstrap.php';$dashboard=(new \Artdon\MaterialCenter\Services\MaterialDashboardService())->operational();$pageTitle='工作台';$pageDescription='物料主数据、待处理事项和近期变化。';$activeMenu='dashboard';include MC_ROOT.'/components/layout_top.php';
?>
<section class="mc-page"><div class="mc-page-header"><div><h1>物料中心工作台</h1><p>今天需要处理的物料任务和数据变化。</p></div><button class="mc-button mc-button--primary" data-open-modal="new-modal"><?=mc_icon('plus',16)?> 新建</button></div>
<div class="mc-dashboard-grid"><section class="mc-panel"><div class="mc-panel__header"><div><strong>待处理工作</strong><span>按优先级排序</span></div><a href="<?=mc_h(mc_url('material/power.php'))?>">查看全部</a></div><div class="mc-task-list">
<a href="<?=mc_h(mc_url('material/power.php?status=pending_review'))?>"><span class="mc-task-dot is-warning"></span><div><strong><?=intval($dashboard['power_pending'])?> 条电源记录待确认</strong><span>仅统计草稿和待审核；正式物料缺资料不阻断转正式</span></div><em>实时</em></a>
<a href="<?=mc_h(mc_url('material/chip.php?status=pending_review'))?>"><span class="mc-task-dot is-info"></span><div><strong><?=intval($dashboard['chip_pending'])?> 条芯片资料待补齐</strong><span>草稿、待审或缺少显指/色温</span></div><em>实时</em></a>
<a href="<?=mc_h(mc_url('adaptation_v2/index.php'))?>"><span class="mc-task-dot is-danger"></span><div><strong><?=intval($dashboard['conflicts'])?> 个产品适配存在冲突</strong><span>最近 30 天真实适配结果</span></div><em>30天</em></a>
<a href="<?=mc_h(mc_url('supplier/index.php'))?>"><span class="mc-task-dot is-neutral"></span><div><strong><?=intval($dashboard['price_changes'])?> 条供应商价格变化</strong><span>最近 7 天价格历史</span></div><em>本周</em></a></div></section>
<section class="mc-panel"><div class="mc-panel__header"><div><strong>最近变化</strong><span>来自物料中心真实操作日志</span></div><a href="<?=mc_h(mc_url('documents/index.php'))?>">操作日志</a></div><div class="mc-activity-list"><?php if(!$dashboard['activities']):?><div><span class="mc-avatar mc-avatar--small">—</span><p><strong>暂无操作记录</strong><small>完成业务操作后将在这里显示</small></p></div><?php else:foreach($dashboard['activities'] as $activity):$actor=$activity['actor_id']?'用户 #'.intval($activity['actor_id']):'系统';?><div><span class="mc-avatar mc-avatar--small"><?=mc_h(mb_substr($actor,0,1))?></span><p><strong><?=mc_h($actor)?></strong> <?=mc_h((string)$activity['action'])?> <?=mc_h((string)$activity['entity_type'])?> #<?=intval($activity['entity_id'])?><small><?=mc_h((string)$activity['created_at'])?></small></p></div><?php endforeach;endif;?></div></section></div>
<section class="mc-panel mc-quick-section"><div class="mc-panel__header"><div><strong>快速进入</strong><span>常用业务页面</span></div></div><div class="mc-quick-links"><a href="<?=mc_h(mc_url('material/power.php'))?>"><?=mc_icon('zap',20)?><span><strong>电源工作台</strong><small>来源、整理、确认、正式物料</small></span></a><a href="<?=mc_h(mc_url('adaptation_v2/index.php'))?>"><?=mc_icon('branch',20)?><span><strong>产品适配</strong><small>产品与物料兼容规则</small></span></a><a href="<?=mc_h(mc_url('supplier/index.php'))?>"><?=mc_icon('users',20)?><span><strong>供应商与价格</strong><small>采购价、MOQ与交期</small></span></a><a href="<?=mc_h(mc_url('data/index.php'))?>"><?=mc_icon('upload',20)?><span><strong>数据接入</strong><small>BOM、Excel与系统同步</small></span></a></div></section></section>
<?php include MC_ROOT.'/components/layout_bottom.php'; ?>
