<?php
require_once __DIR__.'/bootstrap.php';$pageTitle='工作台';$pageDescription='物料主数据、待处理事项和近期变化。';$activeMenu='dashboard';include MC_ROOT.'/components/layout_top.php';
?>
<section class="mc-page"><div class="mc-page-header"><div><h1>物料中心工作台</h1><p>今天需要处理的物料任务和数据变化。</p></div><button class="mc-button mc-button--primary" data-open-modal="new-modal"><?=mc_icon('plus',16)?> 新建</button></div>
<div class="mc-dashboard-grid"><section class="mc-panel"><div class="mc-panel__header"><div><strong>待处理工作</strong><span>按优先级排序</span></div><a href="<?=mc_h(mc_url('material/power.php'))?>">查看全部</a></div><div class="mc-task-list">
<a href="<?=mc_h(mc_url('material/power.php'))?>"><span class="mc-task-dot is-warning"></span><div><strong>12 条电源记录待确认</strong><span>缺少功率档或供应商质保</span></div><em>今天</em></a>
<a href="<?=mc_h(mc_url('material/chip.php'))?>"><span class="mc-task-dot is-info"></span><div><strong>6 条芯片资料待补齐</strong><span>缺少显指或色温范围</span></div><em>2天</em></a>
<a href="<?=mc_h(mc_url('adaptation/index.php'))?>"><span class="mc-task-dot is-danger"></span><div><strong>3 个产品适配存在冲突</strong><span>电源尺寸与灯体空间不匹配</span></div><em>紧急</em></a>
<a href="<?=mc_h(mc_url('supplier/index.php'))?>"><span class="mc-task-dot is-neutral"></span><div><strong>5 个供应商价格发生变化</strong><span>等待采购确认生效</span></div><em>本周</em></a></div></section>
<section class="mc-panel"><div class="mc-panel__header"><div><strong>最近变化</strong><span>来自物料中心和 BOM 来源</span></div><a href="<?=mc_h(mc_url('documents/index.php'))?>">操作日志</a></div><div class="mc-activity-list"><div><span class="mc-avatar mc-avatar--small">赵</span><p><strong>赵立伟</strong> 更新了电源 LF-GIR020YS 的质保信息<small>10分钟前</small></p></div><div><span class="mc-avatar mc-avatar--small">采</span><p><strong>采购部</strong> 导入了 18 条供应商价格<small>1小时前</small></p></div><div><span class="mc-avatar mc-avatar--small">系</span><p><strong>系统</strong> 从 BOM 读取到 7 条新物料记录<small>今天 09:15</small></p></div><div><span class="mc-avatar mc-avatar--small">工</span><p><strong>工程部</strong> 提交了 2 条临时配件<small>昨天</small></p></div></div></section></div>
<section class="mc-panel mc-quick-section"><div class="mc-panel__header"><div><strong>快速进入</strong><span>常用业务页面</span></div></div><div class="mc-quick-links"><a href="<?=mc_h(mc_url('material/power.php'))?>"><?=mc_icon('zap',20)?><span><strong>电源工作台</strong><small>来源、整理、确认、正式物料</small></span></a><a href="<?=mc_h(mc_url('adaptation/index.php'))?>"><?=mc_icon('branch',20)?><span><strong>产品适配</strong><small>产品与物料兼容规则</small></span></a><a href="<?=mc_h(mc_url('supplier/index.php'))?>"><?=mc_icon('users',20)?><span><strong>供应商与价格</strong><small>采购价、MOQ与交期</small></span></a><a href="<?=mc_h(mc_url('data/index.php'))?>"><?=mc_icon('upload',20)?><span><strong>数据接入</strong><small>BOM、Excel与系统同步</small></span></a></div></section></section>
<?php include MC_ROOT.'/components/layout_bottom.php'; ?>
