<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';use Artdon\MaterialCenter\Services\MaterialMasterService;
$user=mc_current_user();$ready=mc_table_exists('mc_material_lifecycle_events');$q=trim((string)($_GET['q']??''));$service=new MaterialMasterService();$rows=$user&&$ready?$service->rows($q):[];$categories=$user&&$ready?$service->categories():[];header('Content-Type:text/html;charset=utf-8');mc_page_start('全部物料','materials',$user);
?><div class="ui-page-head"><div><span class="ui-eyebrow">A9 · MATERIAL LIFECYCLE</span><h1>全部物料</h1><p>独立新建与完整生命周期；旧 BOM 始终只读。</p></div><button class="ui-btn" type="button" data-ui-modal-open="#material-modal" data-new-material>新建物料</button></div>
<?php if(!$user):?><?php mc_state('permission','需要统一登录','复用广州 ERP 统一账号。');?>
<?php elseif(!$ready):?><?php mc_state('config','生命周期尚未安装','请先执行 A9 迁移。');?>
<?php else:?><form class="ui-toolbar ui-card"><input class="ui-input" name="q" value="<?=mc_h($q)?>" placeholder="搜索编号、名称、品牌、型号"><button class="ui-btn">搜索</button><a class="ui-btn ui-btn-secondary" href="materials.php">重置</a><button class="ui-btn ui-btn-secondary" type="button" data-ui-table-settings="#materials-table">视图设置</button></form>
<?php if(!$rows):?><?php mc_state('empty','暂无物料','可以独立新建草稿物料；不会写入旧 BOM。');?>
<?php else:?><section class="ui-card ui-table-panel"><div class="ui-table-wrap"><table class="ui-table" id="materials-table" data-ui-table><thead><tr><th data-sort>物料编号</th><th>分类</th><th data-sort>名称</th><th>品牌</th><th>型号</th><th>来源</th><th data-sort>状态</th><th class="ui-action-col">操作</th></tr></thead><tbody><?php foreach($rows as$r):?><tr data-material='<?=mc_h(json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?>'><td><b><?=mc_h($r['material_code'])?></b></td><td><?=mc_h($r['category_name'])?></td><td><?=mc_h($r['name'])?></td><td><?=mc_h($r['brand'])?></td><td><?=mc_h($r['model'])?></td><td><?=mc_h($r['source'])?></td><td><span class="ui-badge"><?=mc_h($r['status'])?></span></td><td class="ui-action-col"><div class="ui-dropdown"><button class="ui-link-button" data-ui-dropdown-trigger>操作</button><div class="ui-menu" role="menu" aria-hidden="true"><?php foreach(['edit'=>'编辑草稿','revision_draft'=>'生成修订草稿','copy'=>'复制新增','submit'=>'提交审核','approve'=>'审核通过','disable'=>'停用','restore'=>'恢复','archive'=>'归档','references'=>'引用检查','delete_draft'=>'删除草稿']as$a=>$label):?><button data-material-action="<?=$a?>"><?=$label?></button><?php endforeach;?></div></div></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;endif;?>
<section class="ui-modal ui-modal-m" id="material-modal" role="dialog" aria-modal="true" aria-hidden="true" tabindex="-1" data-ui-dirty="false"><div class="ui-modal-header"><h2>物料草稿</h2><button class="ui-btn ui-btn-secondary ui-btn-icon" data-ui-close>×</button></div><form class="ui-modal-body standard-form" id="material-form"><input type="hidden" name="csrf_token" value="<?=mc_h(function_exists('csrf_token')?csrf_token():'')?>"><input type="hidden" name="id"><label class="ui-field"><span class="ui-label">分类 *</span><select class="ui-select" name="category_id" required><?php foreach($categories as$c):?><option value="<?=$c['id']?>"><?=mc_h($c['name'])?></option><?php endforeach;?></select></label><label class="ui-field"><span class="ui-label">名称 *</span><input class="ui-input" name="name" required></label><label class="ui-field"><span class="ui-label">品牌</span><input class="ui-input" name="brand"></label><label class="ui-field"><span class="ui-label">型号</span><input class="ui-input" name="model"></label><label class="ui-field"><span class="ui-label">单位 *</span><input class="ui-input" name="unit" required></label></form><div class="ui-modal-footer"><button class="ui-btn ui-btn-secondary" data-ui-close>取消</button><button class="ui-btn" type="submit" form="material-form">保存草稿</button></div></section><?php mc_page_end('','assets/js/materials.js');?>
