<?php
declare(strict_types=1);require_once __DIR__.'/bootstrap.php';use Artdon\MaterialCenter\Services\PowerStandardizationService;
$user=mc_current_user();$ready=mc_table_exists('mc_power_bands');$bands=$user&&$ready?(new PowerStandardizationService())->bands():[];
header('Content-Type:text/html;charset=utf-8');header('Cache-Control:no-store');mc_page_start('功率档管理','bands',$user);
?>
<div class="ui-page-head"><div><span class="ui-eyebrow">MAINTAINABLE POWER BANDS</span><h1>功率档管理</h1><p>边界存储在数据库中，解析只自动建议，最终允许人工确认或更正。</p></div><button class="ui-btn" type="button" data-new-band>新增功率档</button></div>
<?php if(!$user):?><?php mc_state('permission','需要统一登录','功率档管理复用广州 ERP 登录态。','../login.php','前往登录');?>
<?php elseif(!$ready):?><?php mc_state('config','功率档结构尚未安装','请先执行 MM2–MM4 迁移。');?>
<?php else:?><section class="ui-card ui-table-panel"><div class="ui-table-wrap"><table class="ui-table"><thead><tr><th>代码</th><th>名称</th><th>下限</th><th>上限</th><th>边界规则</th><th>状态</th><th class="ui-action-col">操作</th></tr></thead><tbody><?php foreach($bands as$b):?><tr><td><?=mc_h($b['code'])?></td><td><?=mc_h($b['name'])?></td><td><?=$b['min_power_w']?>W</td><td><?=$b['max_power_w']?>W</td><td><?=$b['min_power_w']?> ≤ P <?=$b['max_inclusive']?'≤':'<'?> <?=$b['max_power_w']?></td><td><?=mc_h($b['status'])?></td><td class="ui-action-col"><button class="ui-link-button" data-edit-band='<?=mc_h(json_encode($b,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?>'>编辑</button></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<div class="ui-modal" id="band-modal" role="dialog" aria-modal="true" aria-hidden="true" tabindex="-1" data-ui-dirty="false"><div class="ui-modal-header"><h2>维护功率档</h2><button class="ui-btn ui-btn-secondary ui-btn-icon" data-ui-close>×</button></div><form class="ui-modal-body" id="band-form"><input type="hidden" name="csrf_token" value="<?=mc_h(function_exists('csrf_token')?csrf_token():'')?>"><input type="hidden" name="id"><label class="ui-field"><span class="ui-label">代码</span><input class="ui-input" name="code" required></label><label class="ui-field"><span class="ui-label">名称</span><input class="ui-input" name="name" required></label><label class="ui-field"><span class="ui-label">下限 W</span><input class="ui-input" name="min_power_w" type="number" step=".01" required></label><label class="ui-field"><span class="ui-label">上限 W</span><input class="ui-input" name="max_power_w" type="number" step=".01" required></label><label class="ui-check"><input type="checkbox" name="max_inclusive" value="1"><span class="ui-check-box"></span><span>包含上限</span></label><label class="ui-field"><span class="ui-label">状态</span><select class="ui-select" name="status"><option value="active">启用</option><option value="inactive">停用</option></select></label></form><div class="ui-modal-footer"><button class="ui-btn ui-btn-secondary" data-ui-close>取消</button><button class="ui-btn" data-save-band>保存</button></div></div>
<?php mc_page_end('','assets/js/power-bands.js');?>
