<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';
use Artdon\MaterialCenter\Services\PowerStandardizationService;
$user=mc_current_user();$ready=mc_table_exists('mc_material_import_staging');$rows=[];$bands=[];
if($user&&$ready){$service=new PowerStandardizationService();$rows=$service->workbenchRows();$bands=$service->bands();}
header('Content-Type:text/html;charset=utf-8');header('Cache-Control:no-store');mc_page_start('电源标准化','standardize',$user);
?>
<div class="ui-page-head"><div><span class="ui-eyebrow">HUMAN CONFIRMATION REQUIRED</span><h1>电源标准化工作台</h1><p>解析结果只作为候选；人工确认后建立物料中心草稿，旧 BOM 数据始终不变。</p></div><button class="ui-btn" type="button" data-api-action="stage_pilot">同步 20–25W 试点</button></div>
<?php if(!$user):?><?php mc_state('permission','需要统一登录','工作台复用广州 ERP 登录态。','../login.php?redirect=/artdon_erp/material_center_v1/power_standardization.php','前往登录');?>
<?php elseif(!$ready):?><?php mc_state('config','MM2–MM4 尚未安装','请先由管理员执行可回滚数据库迁移。','','');?>
<?php elseif(!$rows):?><?php mc_state('empty','尚无待整理电源','可从“物料中心 → 电源”点击来源行的“整理”，或同步 20–25W 试点。','','');?>
<?php else:?>
<section class="ui-card ui-table-panel"><div class="ui-table-wrap"><table class="ui-table" id="standard-table" data-ui-table data-page-size="20"><thead><tr><th data-sort="number">源ID</th><th data-sort>品牌</th><th data-sort>型号</th><th>规格</th><th data-sort="number">最大功率</th><th data-sort>安装候选</th><th data-sort>质保候选</th><th data-sort>状态</th><th data-sort="number">重复风险</th><th class="ui-action-col">操作</th></tr></thead><tbody>
<?php foreach($rows as$row):?><tr><td><?= (int)$row['source_id']?></td><td><?=mc_h($row['raw_brand'])?></td><td><?=mc_h($row['raw_model'])?></td><td class="ui-cell-wrap"><?=mc_h($row['raw_spec'])?></td><td><?=mc_h($row['max_power']?:'待确认')?>W</td><td><?=mc_h(['internal'=>'内置','external'=>'外置','unknown'=>'待确认'][$row['installation_candidate']]??'待确认')?></td><td><?=mc_h($row['warranty_candidate']?$row['warranty_candidate'].'年':'待确认')?></td><td><span class="ui-badge"><?=$row['material_id']?'已映射':mc_h($row['mapping_status'])?></span></td><td><?= (int)$row['duplicate_risk']?></td><td class="ui-action-col"><button class="ui-link-button" type="button" data-review-id="<?= (int)$row['id']?>">审核</button></td></tr><?php endforeach;?>
</tbody></table></div></section>
<?php endif;?>
<aside class="ui-drawer ui-drawer-xl" id="standardization-drawer" role="dialog" aria-modal="true" aria-hidden="true" tabindex="-1" data-ui-dirty="false"><div class="ui-drawer-header"><div><span class="ui-eyebrow">PARSED → CONFIRMED</span><h2>人工确认电源字段</h2></div><button class="ui-btn ui-btn-secondary ui-btn-icon" type="button" data-ui-close aria-label="关闭">×</button></div><div class="ui-drawer-body"><div data-original class="ui-card ui-card-body"></div><form id="standard-form" class="standard-form"><input type="hidden" name="csrf_token" value="<?=mc_h(function_exists('csrf_token')?csrf_token():'')?>"><input type="hidden" name="staging_id"><label class="ui-field"><span class="ui-label">安装方式 *</span><select class="ui-select" name="installation_type" required><option value="unknown">待确认</option><option value="internal">内置</option><option value="external">外置</option><option value="remote">远置</option><option value="integrated">一体式</option><option value="track_builtin">导轨内置</option><option value="junction_box">接线盒内置</option></select></label><label class="ui-field"><span class="ui-label">输出类型 *</span><select class="ui-select" name="output_type" required><option value="unknown">待确认</option><option value="constant_current">恒流</option><option value="constant_voltage">恒压</option></select></label><label class="ui-field"><span class="ui-label">功率档 *</span><select class="ui-select" name="power_band_id" required><option value="">请选择</option><?php foreach($bands as$b):?><option value="<?=$b['id']?>"><?=mc_h($b['name'])?></option><?php endforeach;?></select></label><label class="ui-field"><span class="ui-label">供应商质保年限</span><select class="ui-select" name="supplier_warranty_years"><option value="">待确认</option><option value="3">3年</option><option value="5">5年</option></select></label>
<?php foreach(['nominal_power_w'=>'标称功率 W','max_output_power_w'=>'最大功率 W','input_voltage_min_v'=>'输入电压最小 V','input_voltage_max_v'=>'输入电压最大 V','output_voltage_min_v'=>'输出电压最小 V','output_voltage_max_v'=>'输出电压最大 V','length_mm'=>'长度 mm','width_mm'=>'宽度 mm','height_mm'=>'高度 mm','power_factor'=>'PF','efficiency'=>'效率'] as$key=>$label):?><label class="ui-field"><span class="ui-label"><?=$label?></span><input class="ui-input" type="number" step="0.01" name="<?=$key?>"><small class="ui-help" data-confidence="<?=$key?>">未解析</small></label><?php endforeach;?>
<fieldset class="standard-fieldset current-options-fieldset"><legend>输出电流选项 mA</legend><div class="current-options-head"><span>默认</span><span>电流值</span><span>操作</span></div><div data-current-options></div><button class="ui-btn ui-btn-secondary ui-btn-sm" type="button" data-add-current>增加一个电流</button><small class="ui-help" data-confidence="current_options_ma">一条电源可维护多个输出电流，选择其中一个作为默认值。</small></fieldset>
<fieldset class="standard-fieldset"><legend>调光方式</legend><?php foreach(['none'=>'不调光','dali'=>'DALI','dali_2'=>'DALI-2','triac'=>'Triac','0_10v'=>'0–10V','1_10v'=>'1–10V','push'=>'Push','dmx'=>'DMX','nfc'=>'NFC','multi'=>'多合一'] as$value=>$label):?><label class="ui-check"><input type="checkbox" name="dimming_modes[]" value="<?=$value?>"><span class="ui-check-box"></span><span><?=$label?></span></label><?php endforeach;?></fieldset><div data-duplicates class="ui-card ui-card-body">暂无重复候选</div><label class="ui-field"><span class="ui-label">关联已有物料 ID</span><input class="ui-input" name="existing_material_id" type="number" min="1"></label></form></div><div class="ui-drawer-footer standard-actions"><button class="ui-btn ui-btn-secondary" type="button" data-link-existing>关联已有</button><button class="ui-btn ui-btn-secondary" type="button" data-defer>暂不处理</button><button class="ui-btn" type="button" data-create-material>确认并建立草稿</button></div></aside>
<?php mc_page_end('','assets/js/power-standardization.js');?>
