<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';
use Artdon\MaterialCenter\Adapters\LegacyAuthAdapter;use Artdon\MaterialCenter\Adapters\LegacyProductAdapter;use Artdon\MaterialCenter\Security\PermissionService;use Artdon\MaterialCenter\Services\ProductPowerRuleService;
$context=(new LegacyAuthAdapter())->current();$user=mc_current_user();$ready=mc_table_exists('mc_product_power_rules');$allowed=$context&&(new PermissionService())->allows($context,'material_center.power.rules.view');$rules=[];$products=[];$bands=[];
if($allowed&&$ready){$rules=(new ProductPowerRuleService())->rules();$products=(new LegacyProductAdapter())->search('',100);$bands=db()->query("SELECT id,name FROM mc_power_bands WHERE status='active' ORDER BY sort_order")->fetchAll(PDO::FETCH_ASSOC);}
header('Content-Type:text/html;charset=utf-8');mc_page_start('产品电源规则','rules',$user);
?>
<div class="ui-page-head"><div><span class="ui-eyebrow">F9 · RULE FOUNDATION</span><h1>产品电源规则</h1><p>旧产品只读；规则独立保存到 mc_ 表，不进入报价。</p></div><button class="ui-btn" type="button" data-ui-modal-open="rule-modal">新建规则</button></div>
<?php if(!$context):?><?php mc_state('permission','需要统一登录','复用广州 ERP 账号。');?>
<?php elseif(!$ready):?><?php mc_state('config','F9 尚未安装','请先执行数据库迁移。');?>
<?php elseif(!$allowed):?><?php mc_state('permission','无权查看','需要产品电源规则查看权限。');?>
<?php elseif(!$rules):?><?php mc_state('empty','尚无产品电源规则','从真实旧产品中选择一项并建立草稿规则。');?>
<?php else:?><section class="ui-card ui-table-panel"><div class="ui-table-wrap"><table class="ui-table" data-ui-table><thead><tr><th>规则</th><th>旧产品ID</th><th>安装</th><th>输出</th><th>灯具功率</th><th>功率档</th><th>状态</th></tr></thead><tbody><?php foreach($rules as$r):?><tr><td><?=mc_h($r['rule_name'])?></td><td><?=intval($r['legacy_product_id'])?></td><td><?=mc_h($r['installation_type'])?></td><td><?=mc_h($r['output_type'])?></td><td><?=mc_h($r['lamp_power_w']??'待确认')?></td><td><?=mc_h($r['power_band']??'待确认')?></td><td><span class="ui-badge"><?=mc_h($r['status'])?></span></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<section class="ui-modal ui-modal-m" id="rule-modal" role="dialog" aria-modal="true" aria-hidden="true" tabindex="-1"><header class="ui-modal-header"><h2>建立产品电源规则</h2><button class="ui-btn ui-btn-secondary ui-btn-icon" type="button" data-ui-close>×</button></header><form id="rule-form" class="ui-modal-body standard-form"><input type="hidden" name="csrf_token" value="<?=mc_h(function_exists('csrf_token')?csrf_token():'')?>"><label class="ui-field"><span class="ui-label">旧产品（只读来源）*</span><select class="ui-select" name="legacy_product_id" required><option value="">请选择</option><?php foreach($products as$p):?><option value="<?=$p['id']?>"><?=mc_h(($p['model_no']?:'#'.$p['id']).' · '.($p['product_name']?:$p['item_name']))?></option><?php endforeach;?></select></label><label class="ui-field"><span class="ui-label">规则名称*</span><input class="ui-input" name="rule_name" required></label><label class="ui-field"><span class="ui-label">安装方式</span><select class="ui-select" name="installation_type"><option value="unknown">待确认</option><option value="internal">内置</option><option value="external">外置</option></select></label><label class="ui-field"><span class="ui-label">输出类型</span><select class="ui-select" name="output_type"><option value="unknown">待确认</option><option value="constant_current">恒流</option><option value="constant_voltage">恒压</option></select></label><label class="ui-field"><span class="ui-label">灯具功率 W</span><input class="ui-input" type="number" step=".01" name="lamp_power_w"></label><label class="ui-field"><span class="ui-label">功率档</span><select class="ui-select" name="power_band_id"><option value="">待确认</option><?php foreach($bands as$b):?><option value="<?=$b['id']?>"><?=mc_h($b['name'])?></option><?php endforeach;?></select></label><?php foreach(['output_current_min_ma'=>'最小电流 mA','output_current_max_ma'=>'最大电流 mA','output_voltage_min_v'=>'最小电压 V','output_voltage_max_v'=>'最大电压 V','max_length_mm'=>'最大长度 mm','max_width_mm'=>'最大宽度 mm','max_height_mm'=>'最大高度 mm','minimum_warranty_years'=>'最低供应商质保年']as$k=>$label):?><label class="ui-field"><span class="ui-label"><?=$label?></span><input class="ui-input" type="number" step=".01" name="<?=$k?>"></label><?php endforeach;?></form><footer class="ui-modal-footer"><button class="ui-btn ui-btn-secondary" type="button" data-ui-close>取消</button><button class="ui-btn" type="submit" form="rule-form">保存草稿规则</button></footer></section>
<?php mc_page_end('','assets/js/product-power-rules.js');?>
