<?php
declare(strict_types=1);

return [
    'version' => '20260801_004_phase5_workspace',
    'description' => 'Product adaptation V2 phase 5 single product configuration workspace',
    'up' => [
        "CREATE TABLE IF NOT EXISTS mc_pa2_product_configs (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            product_id BIGINT UNSIGNED NOT NULL,
            product_category_id BIGINT UNSIGNED NULL,
            source_template_id BIGINT UNSIGNED NULL,
            active_draft_version_id BIGINT UNSIGNED NULL,
            active_published_version_id BIGINT UNSIGNED NULL,
            status VARCHAR(40) NOT NULL DEFAULT 'draft',
            owner_user_id BIGINT UNSIGNED NULL,
            created_by BIGINT UNSIGNED NULL,
            updated_by BIGINT UNSIGNED NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            UNIQUE KEY uk_mc_pa2_product_config_product (product_id),
            KEY idx_mc_pa2_product_configs_category (product_category_id,status),
            KEY idx_mc_pa2_product_configs_template (source_template_id,status)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_pa2_product_config_versions (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            product_config_id BIGINT UNSIGNED NOT NULL,
            version_no VARCHAR(40) NOT NULL DEFAULT 'draft-1',
            source_template_id BIGINT UNSIGNED NULL,
            source_template_version_id BIGINT UNSIGNED NULL,
            status VARCHAR(40) NOT NULL DEFAULT 'draft',
            configuration_snapshot_json JSON NULL,
            technical_range_json JSON NULL,
            check_summary_json JSON NULL,
            created_by BIGINT UNSIGNED NULL,
            submitted_by BIGINT UNSIGNED NULL,
            approved_by BIGINT UNSIGNED NULL,
            published_by BIGINT UNSIGNED NULL,
            created_at DATETIME NOT NULL,
            submitted_at DATETIME NULL,
            approved_at DATETIME NULL,
            published_at DATETIME NULL,
            UNIQUE KEY uk_mc_pa2_product_config_version (product_config_id,version_no),
            KEY idx_mc_pa2_product_config_versions_config (product_config_id,status,created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_pa2_product_group_configs (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            product_config_version_id BIGINT UNSIGNED NOT NULL,
            group_code VARCHAR(80) NOT NULL,
            group_definition_id BIGINT UNSIGNED NOT NULL,
            display_name VARCHAR(180) NULL,
            group_type VARCHAR(40) NULL,
            effective_settings_json JSON NULL,
            status VARCHAR(40) NOT NULL DEFAULT 'missing',
            is_overridden TINYINT(1) NOT NULL DEFAULT 0,
            override_source VARCHAR(80) NULL,
            sort_order INT NOT NULL DEFAULT 100,
            created_by BIGINT UNSIGNED NULL,
            updated_by BIGINT UNSIGNED NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            UNIQUE KEY uk_mc_pa2_product_group_config (product_config_version_id,group_code),
            KEY idx_mc_pa2_product_group_configs_version (product_config_version_id,status,sort_order),
            KEY idx_mc_pa2_product_group_configs_definition (group_definition_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS mc_pa2_product_selected_options (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            product_group_config_id BIGINT UNSIGNED NOT NULL,
            option_type VARCHAR(40) NOT NULL DEFAULT 'attribute',
            material_id BIGINT UNSIGNED NULL,
            option_definition_id BIGINT UNSIGNED NULL,
            numeric_value DECIMAL(18,4) NULL,
            text_value TEXT NULL,
            boolean_value TINYINT(1) NULL,
            value_json JSON NULL,
            is_default TINYINT(1) NOT NULL DEFAULT 0,
            is_alternative TINYINT(1) NOT NULL DEFAULT 0,
            sort_order INT NOT NULL DEFAULT 100,
            created_by BIGINT UNSIGNED NULL,
            updated_by BIGINT UNSIGNED NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            KEY idx_mc_pa2_product_selected_group (product_group_config_id,sort_order),
            KEY idx_mc_pa2_product_selected_material (material_id),
            KEY idx_mc_pa2_product_selected_option (option_definition_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    ],
    'down' => [
        "DROP TABLE IF EXISTS mc_pa2_product_selected_options",
        "DROP TABLE IF EXISTS mc_pa2_product_group_configs",
        "DROP TABLE IF EXISTS mc_pa2_product_config_versions",
        "DROP TABLE IF EXISTS mc_pa2_product_configs",
    ],
];
